<?php

return [
    'name' => 'Retail',
    'slug' => 'retail',
    'type' => 'industry',
    'description' => 'Simple retail tools for small shops: sell at the counter, manage products and stock, receive payments, handle customers, returns, and daily reports.',
    'sub_industries' => [
        ['slug' => 'book-store', 'name' => 'Book Store', 'description' => 'Sell books and stationery, scan ISBN or barcode, watch stock, and reorder popular titles.', 'dashboard_features' => ['Make a Sale', 'Low stock titles', 'Daily book sales', 'Customer orders']],
        ['slug' => 'clothing-store', 'name' => 'Clothing Store', 'description' => 'Sell apparel by size or color, manage simple variants, returns, promotions, and store stock.', 'dashboard_features' => ['Make a Sale', 'Size and color stock', 'Returns tracking', 'Daily sales']],
        ['slug' => 'furniture-store', 'name' => 'Furniture Store', 'description' => 'Track showroom items, customer deposits, supplier orders, deliveries, and balances.', 'dashboard_features' => ['Make a Sale', 'Customer deposits', 'Delivery list', 'Stock on hand']],
        ['slug' => 'grocery-store', 'name' => 'Grocery Store', 'description' => 'Run fast checkout, track daily stock movement, watch expiry dates, and restock quickly.', 'dashboard_features' => ['Make a Sale', 'Daily grocery sales', 'Low stock items', 'Expiry alerts']],
        ['slug' => 'hardware-store', 'name' => 'Hardware Store', 'description' => 'Sell hardware items, handle units of measure, manage contractor customers, and count stock.', 'dashboard_features' => ['Make a Sale', 'Stock counts', 'Supplier restock', 'Customer balances']],
        ['slug' => 'toy-store', 'name' => 'Toy Store', 'description' => 'Sell toys and gifts, track seasonal demand, returns, customer purchases, and stock alerts.', 'dashboard_features' => ['Make a Sale', 'Seasonal items', 'Gift purchases', 'Low stock alerts']],
    ],
    'registration_sub_industries' => [
        'book-store',
        'clothing-store',
        'furniture-store',
        'grocery-store',
        'hardware-store',
        'toy-store',
    ],
    'features' => [
        'Make a Sale', 'Products & Pricing', 'Stock Control', 'Customer Records',
        'Mobile Money', 'Returns & Refunds', 'Simple Reports', 'Supplier Restock',
        'Website Catalog',
    ],
    'core_modules' => [
        'Finance', 'Accounting', 'Payments', 'CRM', 'HR', 'Inventory Core', 'Reporting', 'Notifications',
        'Authentication', 'User Management', 'Documents', 'Audit Logs', 'Dashboard Framework', 'Workflow Engine',
    ],
    'routes' => [
        'web' => [
            'dashboard' => 'retail.dashboard',
            'pos' => 'retail.pos.index',
            'products' => 'retail.products.index',
            'inventory' => 'retail.inventory.index',
            'warehousing' => 'retail.warehousing.index',
            'orders' => 'retail.orders.index',
            'customers' => 'retail.customers.index',
            'loyalty' => 'retail.loyalty.index',
            'promotions' => 'retail.promotions.index',
            'gift_cards' => 'retail.gift-cards.index',
            'returns' => 'retail.returns.index',
            'procurement' => 'retail.procurement.index',
            'suppliers' => 'retail.suppliers.index',
            'branches' => 'retail.branches.index',
            'ecommerce' => 'retail.ecommerce.index',
            'analytics' => 'retail.analytics.index',
            'reports' => 'retail.reports.index',
            'settings' => 'retail.settings.index',
        ],
    ],
    'api' => [
        'prefix' => '/api/v1/industries/retail',
        'resources' => ['dashboard', 'products', 'promotions', 'orders', 'loyalty', 'gift-cards', 'scan/product', 'scan/verify', 'scan/camera', 'scan/self-checkout', 'scan/history', 'scan/analytics'],
    ],
    'widgets' => [
        'retail-sales-today',
        'retail-average-basket',
        'retail-low-stock',
        'retail-loyalty-members',
        'retail-warehouse-fulfillment',
        'retail-smart-scans-total',
        'retail-smart-scans-failed',
        'retail-expired-products-blocked',
        'retail-fraud-attempts',
    ],
    'reports' => [
        'Daily Sales', 'Monthly Sales', 'Product Sales', 'Stock Levels',
        'Low Stock', 'Customer Purchases', 'Supplier Restock', 'Returns',
    ],
    'workflows' => [
        'Add products', 'Sell at the counter', 'Receive payment', 'Update stock',
        'Handle returns', 'Reorder low-stock items',
    ],
    'templates' => [
        'Retail dashboard', 'Daily sales report', 'Stock count', 'Return note',
    ],
    'permissions' => [
        'retail.view', 'retail.manage', 'retail.reports', 'retail.pos.view', 'retail.pos.manage',
        'retail.products.view', 'retail.products.manage', 'retail.inventory.view', 'retail.inventory.manage',
        'retail.categories.view', 'retail.categories.manage', 'retail.brands.view', 'retail.brands.manage',
        'retail.attributes.view', 'retail.attributes.manage', 'retail.variants.view', 'retail.variants.manage',
        'retail.pricing.manage', 'retail.inventory.adjust', 'retail.serials.manage', 'retail.batches.manage',
        'retail.warehousing.view', 'retail.warehousing.manage', 'retail.orders.view', 'retail.orders.manage',
        'retail.customers.view', 'retail.customers.manage', 'retail.loyalty.view', 'retail.loyalty.manage',
        'retail.promotions.view', 'retail.promotions.manage', 'retail.gift-cards.view', 'retail.gift-cards.manage',
        'retail.returns.view', 'retail.returns.manage', 'retail.procurement.view', 'retail.procurement.manage',
        'retail.suppliers.view', 'retail.suppliers.manage', 'retail.branches.view', 'retail.branches.manage',
        'retail.ecommerce.view', 'retail.ecommerce.manage', 'retail.analytics.view', 'retail.settings.manage',
        'retail.scanning.view', 'retail.scanning.manage', 'retail.scanning.self-checkout',
        'retail.scanning.reports', 'retail.scanning.override', 'retail.scanning.compliance',
        'etims.view', 'etims.manage', 'etims.reports', 'etims.retry',
    ],
    'roles' => [
        'Owner', 'Shop Manager', 'Cashier', 'Stock Clerk', 'Accountant',
    ],
    'menus' => [
        ['label' => 'Dashboard', 'route' => 'retail.dashboard', 'icon' => 'bi-speedometer2', 'permission' => 'retail.view', 'tables' => ['retail_product_profiles']],
        ['label' => 'Make a Sale', 'route' => 'retail.pos.index', 'icon' => 'bi-upc-scan', 'permission' => 'retail.pos.view'],
        ['label' => 'Products', 'route' => 'retail.products.index', 'icon' => 'bi-box-seam', 'permission' => 'retail.products.view', 'tables' => ['retail_product_profiles']],
        ['label' => 'Inventory', 'route' => 'retail.inventory.index', 'icon' => 'bi-stack', 'permission' => 'retail.inventory.view', 'tables' => ['retail_inventory_balances']],
        ['label' => 'Orders', 'route' => 'retail.orders.index', 'icon' => 'bi-bag-check', 'permission' => 'retail.orders.view', 'tables' => ['retail_orders']],
        ['label' => 'Customers', 'route' => 'retail.customers.index', 'icon' => 'bi-people', 'permission' => 'retail.customers.view', 'tables' => ['retail_customer_profiles']],
        ['label' => 'Returns', 'route' => 'retail.returns.index', 'icon' => 'bi-arrow-counterclockwise', 'permission' => 'retail.returns.view', 'tables' => ['retail_return_authorizations']],
        ['label' => 'Suppliers', 'route' => 'retail.suppliers.index', 'icon' => 'bi-truck', 'permission' => 'retail.suppliers.view'],
        ['label' => 'Website', 'route' => 'retail.ecommerce.index', 'icon' => 'bi-globe2', 'permission' => 'retail.ecommerce.view', 'tables' => ['retail_ecommerce_integrations']],
        ['label' => 'Reports', 'route' => 'retail.reports.index', 'icon' => 'bi-bar-chart', 'permission' => 'retail.reports'],
        ['label' => 'Settings', 'route' => 'retail.settings.index', 'icon' => 'bi-gear', 'permission' => 'retail.settings.manage'],
    ],
    'menu_structure' => [
        'Dashboard', 'Make a Sale', 'Products', 'Inventory', 'Orders',
        'Customers', 'Returns', 'Suppliers', 'Website', 'Reports',
    ],
    'integrations' => [
        'payments' => 'Split payments use existing payment methods and POS payment records.',
        'finance' => 'Accounting and ledger posting remain in the shared Finance and Accounting modules.',
        'crm' => 'Retail customers extend existing Clients instead of duplicating CRM.',
        'inventory' => 'Retail balances and warehouse bins extend Products and StockService movements.',
        'procurement' => 'Supplier and purchase workflows reuse shared ERP procurement models.',
        'reporting' => 'Retail report links resolve through the shared Reporting module.',
        'audit' => 'Retail services call IamService audit logging for material changes.',
        'documents' => 'Document generation stays in shared Documents and templates.',
        'scanning' => 'Smart scanning extends POS, Product Catalog, Promotions, Warehousing, Compliance, Inventory, and Reporting without replacing them.',
        'etims' => 'Fiscal invoices, receipt validation, QR payloads, offline queues, retries, and audit records are delegated to shared/compliance/etims.',
    ],
    'tenant_isolated' => true,
    'role_permissions' => true,
    'dynamic_menus' => true,
    'dashboard_widgets' => true,
    'api_endpoints' => true,
    'subscription_activated' => true,
];
