<?php

return [
    'name' => 'Retail',
    'slug' => 'retail',
    'type' => 'industry',
    'description' => 'Enterprise retail management for POS, catalog, inventory, warehousing, customers, loyalty, promotions, returns, orders, delivery, branches, ecommerce, analytics, and reports.',
    'sub_industries' => [
        ['slug' => 'standard', 'name' => 'Retail Standard', 'description' => 'Single-store retail operations with shared ERP services.'],
        ['slug' => 'multi-branch', 'name' => 'Multi-Branch Retail', 'description' => 'Branch-aware inventory, POS, staff, and performance operations.'],
        ['slug' => 'enterprise', 'name' => 'Enterprise Retail', 'description' => 'Enterprise retail controls, APIs, workflow hooks, analytics, and auditability.'],
    ],
    'features' => [
        'Point of Sale', 'Product Catalog', 'Retail Inventory', 'Warehousing', 'Customer Management',
        'Loyalty Programs', 'Promotions', 'Gift Cards', 'Returns & Refunds', 'Procurement',
        'Branch Management', 'Ecommerce Integration', 'Order Management', 'Delivery Management',
        'Employee Retail Operations', 'Smart Product Scanning & Verification', 'Retail Analytics', 'Retail Reports',
        'ETIMS Fiscal Compliance Integration',
    ],
    'core_modules' => [
        'Finance', 'Accounting', 'Payments', 'CRM', 'HR', 'Inventory Core', 'Reporting', 'Notifications',
        'Authentication', 'User Management', 'Documents', 'Audit Logs', 'Dashboard Framework', 'Workflow Engine',
    ],
    'routes' => [
        'web' => [
            'dashboard' => 'retail.dashboard',
            'pos' => 'retail.pos.index',
            'products' => 'retail.products.index',
            'inventory' => 'retail.inventory.index',
            'warehousing' => 'retail.warehousing.index',
            'orders' => 'retail.orders.index',
            'customers' => 'retail.customers.index',
            'loyalty' => 'retail.loyalty.index',
            'promotions' => 'retail.promotions.index',
            'gift_cards' => 'retail.gift-cards.index',
            'returns' => 'retail.returns.index',
            'procurement' => 'retail.procurement.index',
            'suppliers' => 'retail.suppliers.index',
            'branches' => 'retail.branches.index',
            'ecommerce' => 'retail.ecommerce.index',
            'analytics' => 'retail.analytics.index',
            'reports' => 'retail.reports.index',
            'settings' => 'retail.settings.index',
        ],
    ],
    'api' => [
        'prefix' => '/api/v1/industries/retail',
        'resources' => ['dashboard', 'products', 'promotions', 'orders', 'loyalty', 'gift-cards', 'scan/product', 'scan/verify', 'scan/camera', 'scan/self-checkout', 'scan/history', 'scan/analytics'],
    ],
    'widgets' => [
        'retail-sales-today',
        'retail-average-basket',
        'retail-low-stock',
        'retail-loyalty-members',
        'retail-warehouse-fulfillment',
        'retail-smart-scans-total',
        'retail-smart-scans-failed',
        'retail-expired-products-blocked',
        'retail-fraud-attempts',
    ],
    'reports' => [
        'Daily Sales', 'Monthly Sales', 'Product Sales', 'Cashier Sales',
        'Stock Levels', 'Reorder Reports', 'Valuation Reports',
        'Loyalty Reports', 'Purchase History', 'Customer Segments',
        'Supplier Performance', 'Purchase Reports',
        'Branch Revenue', 'Branch Profitability', 'Branch Inventory',
        'Scan History', 'Scan Analytics', 'Batch Traceability', 'Expiry Alerts', 'Fraud Attempts',
        'ETIMS Compliance Reports',
    ],
    'workflows' => [
        'POS sale approval', 'Return authorization approval', 'Stock transfer approval',
        'Purchase order approval', 'Promotion scheduling approval', 'Gift card issuance audit',
        'Smart scan compliance review', 'Batch recall workflow', 'Age verification override',
    ],
    'templates' => [
        'Retail dashboard', 'Sales report', 'Stock transfer', 'Return authorization', 'Supplier scorecard',
    ],
    'permissions' => [
        'retail.view', 'retail.manage', 'retail.reports', 'retail.pos.view', 'retail.pos.manage',
        'retail.products.view', 'retail.products.manage', 'retail.inventory.view', 'retail.inventory.manage',
        'retail.warehousing.view', 'retail.warehousing.manage', 'retail.orders.view', 'retail.orders.manage',
        'retail.customers.view', 'retail.customers.manage', 'retail.loyalty.view', 'retail.loyalty.manage',
        'retail.promotions.view', 'retail.promotions.manage', 'retail.gift-cards.view', 'retail.gift-cards.manage',
        'retail.returns.view', 'retail.returns.manage', 'retail.procurement.view', 'retail.procurement.manage',
        'retail.suppliers.view', 'retail.suppliers.manage', 'retail.branches.view', 'retail.branches.manage',
        'retail.ecommerce.view', 'retail.ecommerce.manage', 'retail.analytics.view', 'retail.settings.manage',
        'retail.scanning.view', 'retail.scanning.manage', 'retail.scanning.self-checkout',
        'retail.scanning.reports', 'retail.scanning.override', 'retail.scanning.compliance',
        'etims.view', 'etims.manage', 'etims.reports', 'etims.retry',
    ],
    'roles' => [
        'Super Admin', 'Retail Director', 'Store Manager', 'Branch Manager', 'Cashier',
        'Warehouse Manager', 'Warehouse Staff', 'Customer Service', 'Accountant', 'Auditor',
    ],
    'menus' => [
        ['label' => 'Dashboard', 'route' => 'retail.dashboard', 'icon' => 'bi-speedometer2', 'permission' => 'retail.view', 'tables' => ['retail_product_profiles']],
        ['label' => 'Point of Sale', 'route' => 'retail.pos.index', 'icon' => 'bi-upc-scan', 'permission' => 'retail.pos.view'],
        ['label' => 'Products', 'route' => 'retail.products.index', 'icon' => 'bi-box-seam', 'permission' => 'retail.products.view', 'tables' => ['retail_product_profiles']],
        ['label' => 'Inventory', 'route' => 'retail.inventory.index', 'icon' => 'bi-stack', 'permission' => 'retail.inventory.view', 'tables' => ['retail_inventory_balances']],
        ['label' => 'Warehousing', 'route' => 'retail.warehousing.index', 'icon' => 'bi-buildings', 'permission' => 'retail.warehousing.view', 'tables' => ['retail_warehouses']],
        ['label' => 'Orders', 'route' => 'retail.orders.index', 'icon' => 'bi-bag-check', 'permission' => 'retail.orders.view', 'tables' => ['retail_orders']],
        ['label' => 'Customers', 'route' => 'retail.customers.index', 'icon' => 'bi-people', 'permission' => 'retail.customers.view', 'tables' => ['retail_customer_profiles']],
        ['label' => 'Loyalty Programs', 'route' => 'retail.loyalty.index', 'icon' => 'bi-gem', 'permission' => 'retail.loyalty.view', 'tables' => ['retail_loyalty_accounts']],
        ['label' => 'Promotions', 'route' => 'retail.promotions.index', 'icon' => 'bi-percent', 'permission' => 'retail.promotions.view', 'tables' => ['retail_promotions']],
        ['label' => 'Gift Cards', 'route' => 'retail.gift-cards.index', 'icon' => 'bi-credit-card-2-front', 'permission' => 'retail.gift-cards.view', 'tables' => ['retail_gift_cards']],
        ['label' => 'Returns', 'route' => 'retail.returns.index', 'icon' => 'bi-arrow-counterclockwise', 'permission' => 'retail.returns.view', 'tables' => ['retail_return_authorizations']],
        ['label' => 'Procurement', 'route' => 'retail.procurement.index', 'icon' => 'bi-cart-check', 'permission' => 'retail.procurement.view'],
        ['label' => 'Suppliers', 'route' => 'retail.suppliers.index', 'icon' => 'bi-truck', 'permission' => 'retail.suppliers.view'],
        ['label' => 'Branches', 'route' => 'retail.branches.index', 'icon' => 'bi-diagram-3', 'permission' => 'retail.branches.view'],
        ['label' => 'Ecommerce', 'route' => 'retail.ecommerce.index', 'icon' => 'bi-cloud-arrow-up', 'permission' => 'retail.ecommerce.view', 'tables' => ['retail_ecommerce_integrations']],
        ['label' => 'Smart Scanning', 'route' => 'retail.scanning.index', 'icon' => 'bi-qr-code-scan', 'permission' => 'retail.scanning.view', 'tables' => ['scan_events', 'scan_devices']],
        ['label' => 'Analytics', 'route' => 'retail.analytics.index', 'icon' => 'bi-graph-up', 'permission' => 'retail.analytics.view'],
        ['label' => 'Reports', 'route' => 'retail.reports.index', 'icon' => 'bi-bar-chart', 'permission' => 'retail.reports'],
        ['label' => 'Settings', 'route' => 'retail.settings.index', 'icon' => 'bi-gear', 'permission' => 'retail.settings.manage'],
    ],
    'integrations' => [
        'payments' => 'Split payments use existing payment methods and POS payment records.',
        'finance' => 'Accounting and ledger posting remain in the shared Finance and Accounting modules.',
        'crm' => 'Retail customers extend existing Clients instead of duplicating CRM.',
        'inventory' => 'Retail balances and warehouse bins extend Products and StockService movements.',
        'procurement' => 'Supplier and purchase workflows reuse shared ERP procurement models.',
        'reporting' => 'Retail report links resolve through the shared Reporting module.',
        'audit' => 'Retail services call IamService audit logging for material changes.',
        'documents' => 'Document generation stays in shared Documents and templates.',
        'scanning' => 'Smart scanning extends POS, Product Catalog, Promotions, Warehousing, Compliance, Inventory, and Reporting without replacing them.',
        'etims' => 'Fiscal invoices, receipt validation, QR payloads, offline queues, retries, and audit records are delegated to shared/compliance/etims.',
    ],
    'tenant_isolated' => true,
    'role_permissions' => true,
    'dynamic_menus' => true,
    'dashboard_widgets' => true,
    'api_endpoints' => true,
    'subscription_activated' => true,
];
