<?php

$modules = [
    'Dashboard',
    'Members',
    'Membership',
    'Contributions',
    'Savings',
    'Merry-Go-Round',
    'Table Banking',
    'Loans',
    'Loan Guarantors',
    'Fines & Penalties',
    'Welfare Fund',
    'Investment Management',
    'Share Capital',
    'Meetings',
    'Attendance',
    'Elections & Leadership',
    'Voting',
    'Expenses',
    'Cash & Bank',
    'M-PESA Payments',
    'Member Statements',
    'Dividends / Profit Distribution',
    'Documents',
    'Communication',
    'Reports',
    'Audit',
    'Settings',
];

$subIndustries = [
    ['slug' => 'standard', 'name' => 'Chama Standard', 'modules' => ['Members', 'Membership', 'Contributions', 'Savings', 'Loans', 'Fines & Penalties', 'Welfare Fund', 'Meetings', 'Member Statements', 'Finance', 'Reports', 'Communication']],
    ['slug' => 'merry-go-round', 'name' => 'Merry-Go-Round', 'modules' => ['Members', 'Contributions', 'Merry-Go-Round', 'Payouts', 'Meetings', 'Fines & Penalties', 'Finance', 'Member Statements', 'Communication']],
    ['slug' => 'table-banking', 'name' => 'Table Banking', 'modules' => ['Members', 'Savings', 'Table Banking', 'Loans', 'Loan Guarantors', 'Loan Repayments', 'Fines & Penalties', 'Meetings', 'Cashbook', 'Finance', 'Reports']],
    ['slug' => 'savings-group', 'name' => 'Savings Group', 'modules' => ['Members', 'Membership', 'Contributions', 'Savings', 'Member Statements', 'M-PESA Payments', 'Meetings', 'Reports']],
    ['slug' => 'investment-group', 'name' => 'Investment Group', 'modules' => ['Members', 'Contributions', 'Share Capital', 'Investment Management', 'Investment Income', 'Expenses', 'Dividends / Profit Distribution', 'Finance', 'Meetings', 'Voting']],
    ['slug' => 'welfare-group', 'name' => 'Welfare Group', 'modules' => ['Members', 'Contributions', 'Welfare Fund', 'Claims', 'Meetings', 'Finance', 'Communication']],
    ['slug' => 'self-help-group', 'name' => 'Self-Help Group', 'modules' => ['Members', 'Contributions', 'Savings', 'Loans', 'Welfare Fund', 'Meetings', 'Attendance', 'Reports']],
    ['slug' => 'village-savings-group', 'name' => 'Village Savings Group', 'modules' => ['Members', 'Savings', 'Contributions', 'Loans', 'Fines & Penalties', 'Meetings', 'Attendance', 'Cashbook']],
    ['slug' => 'women-group', 'name' => 'Women Group', 'modules' => ['Members', 'Contributions', 'Savings', 'Loans', 'Welfare Fund', 'Meetings', 'Leadership', 'Communication']],
    ['slug' => 'youth-group', 'name' => 'Youth Group', 'modules' => ['Members', 'Contributions', 'Savings', 'Loans', 'Projects', 'Meetings', 'Voting', 'Reports']],
    ['slug' => 'family-investment-group', 'name' => 'Family Investment Group', 'modules' => ['Members', 'Share Capital', 'Investment Management', 'Investment Income', 'Dividends / Profit Distribution', 'Meetings', 'Documents', 'Voting']],
    ['slug' => 'community-group', 'name' => 'Community Group', 'modules' => ['Members', 'Contributions', 'Welfare Fund', 'Meetings', 'Attendance', 'Leadership', 'Voting', 'Communication']],
    ['slug' => 'enterprise', 'name' => 'Enterprise Chama', 'modules' => array_merge($modules, ['Advanced Approval Workflows', 'Executive Dashboard', 'Advanced Audit', 'Advanced Investment Analytics', 'Multi-Account Finance', 'Member Risk Analytics'])],
    ['slug' => 'multi-branch', 'name' => 'Multi-Branch / Umbrella Group', 'modules' => array_merge($modules, ['Parent Group', 'Chapter Groups', 'Branch Permissions', 'Consolidated Reporting'])],
];

foreach ($subIndustries as &$subIndustry) {
    $subIndustry['description'] = 'Chama operating profile for '.$subIndustry['name'].' with module activation tailored to group savings, lending, meetings, and member transparency.';
    $subIndustry['dashboard_features'] = array_slice(array_map(fn (string $module) => $module.' dashboard', $subIndustry['modules']), 0, 6);
}
unset($subIndustry);

$permissions = [
    'chama.view',
    'chama.dashboard',
    'members.view',
    'members.create',
    'members.approve',
    'members.update',
    'contributions.view',
    'contributions.manage',
    'savings.view',
    'savings.manage',
    'merry_go_round.manage',
    'table_banking.manage',
    'loans.view',
    'loans.apply',
    'loans.review',
    'loans.approve',
    'loans.disburse',
    'loan_repayments.manage',
    'guarantors.manage',
    'fines.manage',
    'welfare.manage',
    'investments.view',
    'investments.manage',
    'shares.manage',
    'dividends.manage',
    'meetings.manage',
    'attendance.manage',
    'minutes.manage',
    'elections.manage',
    'voting.manage',
    'chama.finance',
    'chama.reports',
    'chama.audit',
    'chama.settings',
];

return [
    'name' => 'Chama Management',
    'slug' => 'chama',
    'type' => 'industry',
    'description' => 'Complete Chama management for merry-go-rounds, table banking, savings groups, investment groups, welfare groups, member statements, loans, meetings, and dividends.',
    'modules' => $modules,
    'features' => $modules,
    'core_modules' => ['CRM', 'Finance', 'Accounting', 'Cost Accounting', 'Payments', 'Documents', 'Reporting', 'Portal', 'Notifications', 'Communication', 'Audit Logs', 'PWA'],
    'routes' => [
        'web' => [
            'dashboard' => 'chama.dashboard',
            'members' => 'chama.dashboard',
            'contributions' => 'chama.dashboard',
            'loans' => 'chama.dashboard',
            'reports' => 'chama.reports.csv',
        ],
        'api' => '/api/v1/industries/chama',
    ],
    'api' => [
        'prefix' => '/api/v1/industries/chama',
        'resources' => ['dashboard', 'members/{member}/statement'],
    ],
    'widgets' => [
        'chama-overview',
        'chama-contributions',
        'chama-savings',
        'chama-loans',
        'chama-welfare',
        'chama-investments',
        'chama-risk-alerts',
        'chama-meetings',
    ],
    'reports' => [
        'Balance Sheet',
        'Income & Expenditure',
        'Cash Flow',
        'Cashbook',
        'Trial Balance',
        'Member Balances',
        'Contribution Report',
        'Savings Report',
        'Loan Portfolio',
        'Loan Arrears',
        'Interest Income',
        'Fine Collection',
        'Welfare Report',
        'Investment Report',
        'Dividend Report',
        'Share Capital Report',
        'Member Register',
        'Contribution Compliance',
        'Guarantor Exposure',
        'Meeting Attendance',
        'Merry-Go-Round Payout History',
        'Table Banking Reconciliation',
    ],
    'workflows' => [
        'Member Application',
        'Member Approval',
        'Contribution Scheduling',
        'Contribution Collection',
        'Merry-Go-Round Collection',
        'Merry-Go-Round Payout',
        'Table Banking Session',
        'Loan Application',
        'Guarantor Confirmation',
        'Loan Review',
        'Loan Approval',
        'Loan Disbursement',
        'Loan Repayment',
        'Welfare Claim',
        'Investment Approval',
        'Dividend Distribution',
        'Meeting Minutes',
        'Voting',
        'Member Exit',
        'Financial Reversal',
    ],
    'templates' => [
        'Member Application',
        'Membership Agreement',
        'Chama Constitution',
        'Contribution Receipt',
        'Member Statement',
        'Loan Agreement',
        'Guarantor Form',
        'Welfare Claim Form',
        'Meeting Minutes',
        'Dividend Statement',
        'Audit Report',
    ],
    'permissions' => $permissions,
    'roles' => [
        'Chama Administrator',
        'Chairperson',
        'Vice Chairperson',
        'Treasurer',
        'Secretary',
        'Committee Member',
        'Loan Officer',
        'Investment Officer',
        'Auditor',
        'Member',
        'Viewer',
    ],
    'menus' => [
        ['label' => 'Dashboard', 'route' => 'chama.dashboard', 'icon' => 'bi-speedometer2', 'permission' => 'chama.dashboard', 'tables' => ['chama_members'], 'section' => 'dashboard'],
        ['label' => 'Members', 'route' => 'chama.dashboard', 'icon' => 'bi-people', 'permission' => 'members.view', 'tables' => ['chama_members'], 'section' => 'members'],
        ['label' => 'Contributions', 'route' => 'chama.dashboard', 'icon' => 'bi-wallet2', 'permission' => 'contributions.view', 'tables' => ['chama_contributions'], 'section' => 'contributions'],
        ['label' => 'Savings', 'route' => 'chama.dashboard', 'icon' => 'bi-piggy-bank', 'permission' => 'savings.view', 'tables' => ['chama_savings_accounts'], 'section' => 'savings'],
        ['label' => 'Merry-Go-Round', 'route' => 'chama.dashboard', 'icon' => 'bi-arrow-repeat', 'permission' => 'merry_go_round.manage', 'tables' => ['chama_merry_go_round_cycles'], 'section' => 'merry-go-round'],
        ['label' => 'Table Banking', 'route' => 'chama.dashboard', 'icon' => 'bi-table', 'permission' => 'table_banking.manage', 'tables' => ['chama_table_banking_sessions'], 'section' => 'table-banking'],
        ['label' => 'Loans', 'route' => 'chama.dashboard', 'icon' => 'bi-cash-coin', 'permission' => 'loans.view', 'tables' => ['chama_loans'], 'section' => 'loans'],
        ['label' => 'Fines', 'route' => 'chama.dashboard', 'icon' => 'bi-exclamation-triangle', 'permission' => 'fines.manage', 'tables' => ['chama_fines'], 'section' => 'fines'],
        ['label' => 'Welfare', 'route' => 'chama.dashboard', 'icon' => 'bi-heart', 'permission' => 'welfare.manage', 'tables' => ['chama_welfare_requests'], 'section' => 'welfare'],
        ['label' => 'Shares', 'route' => 'chama.dashboard', 'icon' => 'bi-pie-chart', 'permission' => 'shares.manage', 'tables' => ['chama_share_transactions'], 'section' => 'shares'],
        ['label' => 'Investments', 'route' => 'chama.dashboard', 'icon' => 'bi-graph-up-arrow', 'permission' => 'investments.view', 'tables' => ['chama_investments'], 'section' => 'investments'],
        ['label' => 'Meetings', 'route' => 'chama.dashboard', 'icon' => 'bi-calendar-event', 'permission' => 'meetings.manage', 'tables' => ['chama_meetings'], 'section' => 'meetings'],
        ['label' => 'Voting', 'route' => 'chama.dashboard', 'icon' => 'bi-check2-square', 'permission' => 'voting.manage', 'tables' => ['chama_ballots'], 'section' => 'voting'],
        ['label' => 'Finance', 'route' => 'finance.index', 'icon' => 'bi-bank', 'permission' => 'chama.finance'],
        ['label' => 'Documents', 'route' => 'chama.dashboard', 'icon' => 'bi-folder2-open', 'permission' => 'members.view', 'tables' => ['chama_documents'], 'section' => 'documents'],
        ['label' => 'Communication', 'route' => 'communication.center', 'icon' => 'bi-chat-dots', 'permission' => 'communication.view', 'tables' => ['communication_channels']],
        ['label' => 'Reports', 'route' => 'chama.dashboard', 'icon' => 'bi-bar-chart', 'permission' => 'chama.reports', 'tables' => ['chama_members'], 'section' => 'reports'],
        ['label' => 'Settings', 'route' => 'chama.dashboard', 'icon' => 'bi-gear', 'permission' => 'chama.settings', 'tables' => ['chama_rules'], 'section' => 'settings'],
    ],
    'dashboard_features' => [
        'Total Members',
        'Total Contributions',
        'Total Savings',
        'Outstanding Loans',
        'Welfare Fund Balance',
        'Investment Value',
        'M-PESA Collections',
        'Contribution Compliance',
    ],
    'menu_structure' => [
        'Dashboard',
        'Members',
        'Applications',
        'Member Statements',
        'Contribution Types',
        'Contribution Schedule',
        'Contribution Collections',
        'Contribution Arrears',
        'Savings',
        'Merry-Go-Round Cycles',
        'Merry-Go-Round Rounds',
        'Merry-Go-Round Payouts',
        'Table Banking Sessions',
        'Table Banking Cashbook',
        'Table Banking Reconciliation',
        'Loan Products',
        'Loan Applications',
        'Active Loans',
        'Loan Repayments',
        'Loan Arrears',
        'Guarantors',
        'Fines',
        'Welfare',
        'Shares',
        'Investments',
        'Dividends',
        'Meetings',
        'Attendance',
        'Minutes',
        'Leadership',
        'Voting',
        'Finance',
        'Payments',
        'Documents',
        'Communication',
        'Reports',
        'Settings',
    ],
    'sub_industries' => $subIndustries,
    'registration_sub_industries' => array_column($subIndustries, 'slug'),
    'integrations' => [
        'crm' => 'Members can link to shared Client records while Chama-specific KYC and financial details stay in tenant-scoped member profiles.',
        'finance' => 'Posted Chama payments, fines, interest, expenses, and distributions can post through the existing FinanceService and reversal flow.',
        'payments' => 'M-PESA, cash, bank, card, and other payment methods reuse the existing payment infrastructure and keep ambiguous receipts unallocated.',
        'documents' => 'Constitutions, KYC, loan agreements, guarantor forms, minutes, and investment files reuse document templates and file storage.',
        'communication' => 'Announcements and record discussions reuse the shared Communication module.',
        'pwa' => 'Dashboard forms use mobile-friendly controls for contribution collection, loan requests, guarantor confirmation, attendance, and voting.',
    ],
    'tenant_isolated' => true,
    'role_permissions' => true,
    'dynamic_menus' => true,
    'dashboard_widgets' => true,
    'api_endpoints' => true,
    'subscription_activated' => true,
];
