@extends('layouts.app')
@section('title',$project->project_name)
@section('content')
<div class="d-flex gap-2 justify-content-end mb-3">
    <a class="btn btn-outline-dark" href="{{ route('projects.edit',$project) }}"><i class="bi bi-pencil"></i> Edit</a>
    <form method="post" action="{{ route('projects.destroy',$project) }}" onsubmit="return confirm('Delete this project?')">@csrf @method('DELETE')<button class="btn btn-outline-danger"><i class="bi bi-trash"></i></button></form>
</div>
@unless($erpEnabled)
<div class="row g-4">
    <div class="col-lg-4"><div class="card"><div class="card-body"><h2 class="h5">Overview</h2><p class="mb-1"><a href="{{ route('clients.show',$project->client) }}">{{ $project->client->name }}</a></p><p class="mb-1">Site: {{ $project->site?->site_name ?: '-' }}</p><p class="mb-1">Contact: {{ $project->contact?->full_name ?: '-' }}</p><p class="mb-0"><span class="status-pill">{{ $project->status }}</span></p><hr><h3 class="h6">Scope</h3><p class="text-muted">{{ $project->scope }}</p></div></div></div>
    <div class="col-lg-8"><div class="card"><div class="card-body"><h2 class="h5">Documents</h2><h3 class="h6 mt-3">Invoices</h3>@forelse($project->invoices as $invoice)<div class="border-top py-2"><a href="{{ route('invoices.show',$invoice) }}">{{ $invoice->invoice_number }}</a><span class="float-end">{{ number_format($invoice->total,2) }} · {{ $invoice->payment_status }}</span></div>@empty<div class="text-muted">No invoices yet.</div>@endforelse<h3 class="h6 mt-3">Quotations</h3>@forelse($project->quotations as $quotation)<div class="border-top py-2"><a href="{{ route('quotations.show',$quotation) }}">{{ $quotation->quotation_number }}</a><span class="float-end">{{ number_format($quotation->total,2) }} · {{ $quotation->status }}</span></div>@empty<div class="text-muted">No quotations yet.</div>@endforelse</div></div></div>
</div>
@if(\Illuminate\Support\Facades\Schema::hasTable('letters'))
<div class="card mt-4"><div class="card-body"><h2 class="h5">Letters</h2>@forelse($project->letters as $letter)<div class="border-top py-2"><a href="{{ route('letters.show',$letter) }}">{{ $letter->letter_number }}</a><span class="float-end">{{ $letter->status }}</span><div class="small text-muted">{{ $letter->subject }}</div></div>@empty<div class="text-muted">No letters yet.</div>@endforelse<a class="btn btn-outline-warning btn-sm mt-2" href="{{ route('letters.from-project',$project) }}"><i class="bi bi-envelope-paper"></i> Generate Handover Letter</a></div></div>
@endif
@else
@php
    $revenue = $project->revenue();
    $expectedCost = $project->expectedCost();
    $actualCost = $project->actualCost();
    $collected = $project->collected();
    $actualProfit = $revenue - $actualCost;
    $expectedProfit = $revenue - $expectedCost;
    $margin = $revenue > 0 ? ($actualProfit / $revenue) * 100 : 0;
@endphp
<ul class="nav nav-tabs mb-3" role="tablist">
    @foreach(['overview'=>'Overview','costs'=>'Costs','procurement'=>'Procurement','documents'=>'Documents','profit'=>'Profit','payments'=>'Payments','handover'=>'Handover'] as $key => $label)
        <li class="nav-item"><button class="nav-link {{ $loop->first ? 'active' : '' }}" data-bs-toggle="tab" data-bs-target="#tab-{{ $key }}" type="button">{{ $label }}</button></li>
    @endforeach
</ul>
<div class="tab-content">
    <div class="tab-pane fade show active" id="tab-overview"><div class="row g-4"><div class="col-lg-4"><div class="card"><div class="card-body"><h2 class="h5">Overview</h2><p class="mb-1"><a href="{{ route('clients.show',$project->client) }}">{{ $project->client->name }}</a></p><p class="mb-1">Site: {{ $project->site?->site_name ?: '-' }}</p><p class="mb-1">Contact: {{ $project->contact?->full_name ?: '-' }}</p><p class="mb-0"><span class="status-pill">{{ $project->status }}</span></p><hr><h3 class="h6">Scope</h3><p class="text-muted">{{ $project->scope }}</p></div></div></div><div class="col-lg-8"><div class="card"><div class="card-body"><h2 class="h5">Documents</h2><h3 class="h6 mt-3">Invoices</h3>@forelse($project->invoices as $invoice)<div class="border-top py-2"><a href="{{ route('invoices.show',$invoice) }}">{{ $invoice->invoice_number }}</a><span class="float-end">{{ number_format($invoice->total,2) }} · {{ $invoice->payment_status }}</span></div>@empty<div class="text-muted">No invoices yet.</div>@endforelse<h3 class="h6 mt-3">Quotations</h3>@forelse($project->quotations as $quotation)<div class="border-top py-2"><a href="{{ route('quotations.show',$quotation) }}">{{ $quotation->quotation_number }}</a><span class="float-end">{{ number_format($quotation->total,2) }} · {{ $quotation->status }}</span></div>@empty<div class="text-muted">No quotations yet.</div>@endforelse</div></div></div></div></div>
    <div class="tab-pane fade" id="tab-costs"><div class="row g-4"><div class="col-lg-7"><div class="card"><div class="card-body"><h2 class="h5">Costs & Expenses</h2>@foreach($project->costs as $cost)<div class="border-top py-2">{{ $cost->category }} - {{ $cost->description }}<span class="float-end">{{ number_format($cost->expected_amount,2) }} / {{ number_format($cost->actual_amount,2) }}</span></div>@endforeach @foreach($project->expenses as $expense)<div class="border-top py-2">{{ $expense->category }} - {{ $expense->description }}<span class="float-end">{{ number_format($expense->amount,2) }}</span></div>@endforeach</div></div></div><div class="col-lg-5"><div class="card"><div class="card-body"><h2 class="h5">Add Cost</h2><form method="post" action="{{ route('projects.costs.store',$project) }}">@csrf<div class="row g-2"><div class="col-md-6"><input class="form-control" name="category" placeholder="Equipment/Labour/Transport" required></div><div class="col-md-6"><input class="form-control" name="description" placeholder="Description" required></div><div class="col-md-6"><input class="form-control" name="expected_amount" type="number" step="0.01" placeholder="Expected"></div><div class="col-md-6"><input class="form-control" name="actual_amount" type="number" step="0.01" placeholder="Actual"></div></div><button class="btn btn-outline-warning btn-sm mt-2">Save Cost</button></form><hr><h2 class="h5">Add Expense</h2><form method="post" action="{{ route('projects.expenses.store',$project) }}">@csrf<input class="form-control mb-2" name="expense_date" type="date" value="{{ now()->format('Y-m-d') }}" required><input class="form-control mb-2" name="category" placeholder="Category" required><textarea class="form-control mb-2" name="description" placeholder="Description"></textarea><input class="form-control mb-2" name="amount" type="number" step="0.01" required><button class="btn btn-outline-warning btn-sm">Save Expense</button></form></div></div></div></div></div>
    <div class="tab-pane fade" id="tab-procurement"><div class="card"><div class="card-body"><h2 class="h5">Procurement</h2>@foreach($project->supplierQuotes as $quote)<div class="border-top py-2">Quote {{ $quote->quote_number }} - {{ $quote->supplier?->name }}<span class="float-end">{{ number_format($quote->amount,2) }} · {{ $quote->status }}</span></div>@endforeach @foreach($project->purchaseOrders as $po)<div class="border-top py-2">PO {{ $po->po_number }} - {{ $po->supplier?->name }}<span class="float-end">{{ number_format($po->amount,2) }} · {{ $po->status }}</span></div>@endforeach @foreach($project->supplierInvoices as $si)<div class="border-top py-2">Supplier Invoice {{ $si->invoice_number }}<span class="float-end">{{ number_format($si->total,2) }} · {{ $si->status }}</span></div>@endforeach<a class="btn btn-outline-warning btn-sm mt-3" href="{{ route('erp.procurement') }}">Open Procurement</a></div></div></div>
    <div class="tab-pane fade" id="tab-documents"><div class="row g-4"><div class="col-lg-7"><div class="card"><div class="card-body"><h2 class="h5">Project Documents</h2>@forelse($project->documents as $document)<div class="border-top py-2">{{ $document->title }}<span class="float-end">{{ $document->document_type }} · {{ $document->status }} <a class="btn btn-sm btn-outline-warning ms-2" href="{{ route('erp.project-documents.download',$document) }}">Export</a></span></div>@empty<div class="text-muted">No project documents.</div>@endforelse @if(\Illuminate\Support\Facades\Schema::hasTable('letters'))<h3 class="h6 mt-4">Letters</h3>@forelse($project->letters as $letter)<div class="border-top py-2"><a href="{{ route('letters.show',$letter) }}">{{ $letter->letter_number }}</a><span class="float-end">{{ $letter->status }}</span><div class="small text-muted">{{ $letter->subject }}</div></div>@empty<div class="text-muted">No letters yet.</div>@endforelse<a class="btn btn-outline-warning btn-sm mt-2" href="{{ route('letters.from-project',$project) }}"><i class="bi bi-envelope-paper"></i> Generate Handover Letter</a>@endif</div></div></div><div class="col-lg-5"><div class="card"><div class="card-body"><h2 class="h5">Generate Document</h2><form method="post" action="{{ route('projects.documents.store',$project) }}">@csrf<select class="form-select mb-2" name="document_template_id"><option value="">Template</option>@foreach($templates as $template)<option value="{{ $template->id }}">{{ $template->name }}</option>@endforeach</select><input class="form-control mb-2" name="document_type" placeholder="Warranty/Proposal/Report/Handover" required><input class="form-control mb-2" name="title" placeholder="Title" required><textarea class="form-control mb-2" name="content" rows="5" placeholder="Optional content or use template"></textarea><select class="form-select mb-2" name="status"><option>Draft</option><option>Final</option></select><button class="btn btn-outline-warning btn-sm">Save Document</button></form></div></div></div></div></div>
    <div class="tab-pane fade" id="tab-profit"><div class="card"><div class="card-body"><h2 class="h5">Profit</h2><div class="row g-3"><div class="col-md-3"><strong>Revenue</strong><div>{{ number_format($revenue,2) }}</div></div><div class="col-md-3"><strong>Expected Profit</strong><div>{{ number_format($expectedProfit,2) }}</div></div><div class="col-md-3"><strong>Actual Profit</strong><div>{{ number_format($actualProfit,2) }}</div></div><div class="col-md-3"><strong>Collected Profit</strong><div>{{ number_format($collected - $actualCost,2) }}</div></div><div class="col-md-3"><strong>Margin %</strong><div>{{ number_format($margin,2) }}%</div></div></div></div></div></div>
    <div class="tab-pane fade" id="tab-payments"><div class="card"><div class="card-body"><h2 class="h5">Payments</h2>@foreach($project->invoices as $invoice)<div class="border-top py-2"><a href="{{ route('invoices.show',$invoice) }}">{{ $invoice->invoice_number }}</a><span class="float-end">Paid {{ number_format($invoice->amount_paid,2) }} / {{ number_format($invoice->total,2) }}</span></div>@endforeach @foreach($project->receiptAllocations as $allocation)<div class="border-top py-2">Receipt allocation {{ $allocation->receipt?->receipt_number }}<span class="float-end">{{ number_format($allocation->amount,2) }}</span></div>@endforeach</div></div></div>
    <div class="tab-pane fade" id="tab-handover"><div class="row g-4"><div class="col-lg-7"><div class="card"><div class="card-body"><h2 class="h5">Handover</h2>@forelse($project->handovers as $handover)<div class="border-top py-2">{{ $handover->handover_date?->format('d M Y') ?: '-' }}<span class="float-end">{{ $handover->status }}</span><div class="small text-muted">{{ $handover->signature_name }}</div></div>@empty<div class="text-muted">No handover records.</div>@endforelse</div></div></div><div class="col-lg-5"><div class="card"><div class="card-body"><h2 class="h5">Add Handover</h2><form method="post" action="{{ route('projects.handovers.store',$project) }}">@csrf<input class="form-control mb-2" type="date" name="handover_date"><select class="form-select mb-2" name="status"><option>Draft</option><option>Signed</option><option>Accepted</option></select><input class="form-control mb-2" name="signature_name" placeholder="Signature name"><textarea class="form-control mb-2" name="notes" placeholder="Notes"></textarea><input class="form-control mb-2" name="checklist[]" value="Checklist"><input class="form-control mb-2" name="checklist[]" value="Signoff"><input class="form-control mb-2" name="checklist[]" value="Topology"><input class="form-control mb-2" name="checklist[]" value="Warranty"><input class="form-control mb-2" name="checklist[]" value="Acceptance"><button class="btn btn-outline-warning btn-sm">Save Handover</button></form></div></div></div></div></div>
</div>
@endunless
@endsection
