@extends('layouts.app')
@section('title', $title)
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-3"><div><div class="small text-uppercase fw-bold text-success">NGO &amp; Non-Profit</div><h1 class="h3 mb-0">{{ $title }}</h1></div><a href="{{ route('ngo.dashboard') }}" class="btn btn-outline-dark">Dashboard</a></div>
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif

@if($kind === 'programs')
    @if(auth()->user()->hasPermission('ngo.programs.manage'))<div class="card p-3 mb-3"><h2 class="h5">Create program</h2><form method="post" action="{{ route('ngo.programs.store') }}" class="row g-2">@csrf
        <div class="col-md-4"><label class="form-label">Program name</label><input name="name" class="form-control" required></div><div class="col-md-2"><label class="form-label">Code</label><input name="code" class="form-control"></div>
        <div class="col-md-3"><label class="form-label">Sector</label><select name="ngo_sector_id" class="form-select"><option value="">Select sector</option>@foreach($sectors as $sector)<option value="{{ $sector->id }}">{{ $sector->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Donor</label><select name="donor_id" class="form-select"><option value="">Select donor</option>@foreach($donors as $donor)<option value="{{ $donor->id }}">{{ $donor->name }}</option>@endforeach</select></div>
        <div class="col-md-4"><label class="form-label">Funding source</label><input name="funding_source" class="form-control"></div><div class="col-md-4"><label class="form-label">Location</label><input name="location" class="form-control"></div><div class="col-md-4"><label class="form-label">Program manager</label><select name="manager_id" class="form-select"><option value="">Unassigned</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select></div>
        <div class="col-md-3"><label class="form-label">Start</label><input name="starts_on" type="date" class="form-control"></div><div class="col-md-3"><label class="form-label">End</label><input name="ends_on" type="date" class="form-control"></div><div class="col-md-3"><label class="form-label">Budget</label><input name="budget" type="number" step="0.01" min="0" class="form-control" value="0"></div><div class="col-md-3"><label class="form-label">Currency</label><input name="currency" class="form-control" maxlength="3" value="KES" required></div>
        <div class="col-md-3"><label class="form-label">Status</label><select name="status" class="form-select">@foreach(['Planning','Active','Suspended','Completed','Closed'] as $status)<option>{{ $status }}</option>@endforeach</select></div><div class="col-md-9"><label class="form-label">Description</label><input name="description" class="form-control"></div><div class="col-12"><button class="btn btn-success">Save program</button></div>
    </form><div class="border-top mt-3 pt-3"><a href="{{ route('ngo.sectors.index') }}">Configure program sectors</a></div></div>@endif
    <div class="card p-3"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Program</th><th>Sector</th><th>Donor</th><th>Period</th><th>Budget</th><th>Status</th></tr></thead><tbody>@forelse($programs as $program)<tr><td><strong>{{ $program->name }}</strong><div class="small text-muted">{{ $program->program_number }} @if($program->code)· {{ $program->code }}@endif</div></td><td>{{ $program->sector?->name ?: '—' }}</td><td>{{ $program->donor?->name ?: $program->funding_source ?: '—' }}</td><td>{{ $program->starts_on?->format('d M Y') ?: '—' }} – {{ $program->ends_on?->format('d M Y') ?: '—' }}</td><td>{{ $program->currency }} {{ number_format((float)$program->budget,2) }}</td><td><span class="status-pill">{{ $program->status }}</span></td></tr>@empty<tr><td colspan="6" class="text-muted">No programs yet.</td></tr>@endforelse</tbody></table></div>{{ $programs->links() }}</div>
@elseif($kind === 'donors')
    @if(auth()->user()->hasPermission('ngo.donors.manage'))<div class="card p-3 mb-3"><h2 class="h5">Add donor</h2><form method="post" action="{{ route('ngo.donors.store') }}" class="row g-2">@csrf
        <div class="col-md-4"><label class="form-label">Donor name</label><input name="name" class="form-control" required></div><div class="col-md-4"><label class="form-label">Organization</label><input name="organization" class="form-control"></div><div class="col-md-4"><label class="form-label">Donor type</label><select name="type" class="form-select">@foreach(['Individual','Corporate','Foundation','Government','International Agency','Development Partner','NGO Partner','Anonymous'] as $type)<option>{{ $type }}</option>@endforeach</select></div>
        <div class="col-md-3"><label class="form-label">Country</label><input name="country" class="form-control"></div><div class="col-md-3"><label class="form-label">Email</label><input name="email" type="email" class="form-control"></div><div class="col-md-3"><label class="form-label">Phone</label><input name="phone" class="form-control"></div><div class="col-md-3"><label class="form-label">Website</label><input name="website" type="url" class="form-control"></div>
        <div class="col-md-9"><label class="form-label">Address / notes</label><input name="address" class="form-control"></div><div class="col-md-3"><label class="form-label">Status</label><select name="status" class="form-select"><option>Active</option><option>Inactive</option></select></div><div class="col-12"><button class="btn btn-success">Save donor</button></div>
    </form></div>@endif
    <div class="card p-3"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Donor</th><th>Type</th><th>Country</th><th>Contact</th><th>Programs</th><th>Status</th></tr></thead><tbody>@forelse($donors as $donor)<tr><td><strong>{{ $donor->name }}</strong><div class="small text-muted">{{ $donor->organization ?: $donor->donor_number }}</div></td><td>{{ $donor->type }}</td><td>{{ $donor->country ?: '—' }}</td><td>{{ $donor->email ?: $donor->phone ?: '—' }}</td><td>{{ $donor->programs_count }}</td><td>{{ $donor->status }}</td></tr>@empty<tr><td colspan="6" class="text-muted">No donors recorded yet.</td></tr>@endforelse</tbody></table></div>{{ $donors->links() }}</div>
@elseif($kind === 'sectors')
    @if(auth()->user()->hasPermission('ngo.programs.manage'))<div class="card p-3 mb-3"><h2 class="h5">Add configurable sector</h2><form method="post" action="{{ route('ngo.sectors.store') }}" class="row g-2">@csrf<div class="col-md-5"><input name="name" class="form-control" placeholder="Sector name" required></div><div class="col-md-4"><input name="code" class="form-control" placeholder="Code (optional)"></div><div class="col-md-3"><button class="btn btn-success w-100">Add sector</button></div></form></div>@endif
    <div class="card p-3"><div class="table-responsive"><table class="table"><thead><tr><th>Sector</th><th>Code</th><th>Status</th></tr></thead><tbody>@forelse($sectors as $sector)<tr><td>{{ $sector->name }}</td><td>{{ $sector->code ?: '—' }}</td><td>{{ $sector->is_active ? 'Active' : 'Inactive' }}</td></tr>@empty<tr><td colspan="3" class="text-muted">No sectors configured. Add the sectors relevant to your organization.</td></tr>@endforelse</tbody></table></div>{{ $sectors->links() }}</div>
@elseif($kind === 'activities')
    @if(auth()->user()->hasPermission('ngo.activities.manage'))<div class="card p-3 mb-3"><h2 class="h5">Plan activity</h2><form method="post" action="{{ route('ngo.activities.store') }}" class="row g-2">@csrf
        <div class="col-md-4"><label class="form-label">Activity</label><input name="name" class="form-control" required></div><div class="col-md-2"><label class="form-label">Type</label><input name="activity_type" class="form-control" placeholder="Training / visit"></div><div class="col-md-3"><label class="form-label">Program</label><select name="program_id" class="form-select"><option value="">No program</option>@foreach($programs as $program)<option value="{{ $program->id }}">{{ $program->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Shared project</label><select name="project_id" class="form-select"><option value="">No project</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->project_name }}</option>@endforeach</select></div>
        <div class="col-md-3"><label class="form-label">Location</label><input name="location" class="form-control"></div><div class="col-md-2"><label class="form-label">Start</label><input name="starts_on" type="date" class="form-control"></div><div class="col-md-2"><label class="form-label">End</label><input name="ends_on" type="date" class="form-control"></div><div class="col-md-2"><label class="form-label">Budget</label><input name="budget" type="number" min="0" step="0.01" class="form-control" value="0"></div><div class="col-md-3"><label class="form-label">Status</label><select name="status" class="form-select">@foreach(['Planned','In Progress','Completed','Delayed','Cancelled'] as $status)<option>{{ $status }}</option>@endforeach</select></div>
        <div class="col-md-9"><input name="description" class="form-control" placeholder="Description"></div><div class="col-md-3"><select name="responsible_user_id" class="form-select"><option value="">Responsible person</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select></div><div class="col-12"><button class="btn btn-success">Save activity</button></div>
    </form></div>@endif
    <div class="card p-3"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Activity</th><th>Program / Project</th><th>Location</th><th>Dates</th><th>Status</th></tr></thead><tbody>@forelse($activities as $activity)<tr><td><strong>{{ $activity->name }}</strong><div class="small text-muted">{{ $activity->activity_type }}</div></td><td>{{ $activity->program?->name ?: '—' }}<div class="small text-muted">{{ $activity->project?->project_name }}</div></td><td>{{ $activity->location ?: '—' }}</td><td>{{ $activity->starts_on?->format('d M Y') ?: '—' }} – {{ $activity->ends_on?->format('d M Y') ?: '—' }}</td><td>{{ $activity->status }}</td></tr>@empty<tr><td colspan="5" class="text-muted">No activities planned.</td></tr>@endforelse</tbody></table></div>{{ $activities->links() }}</div>
@elseif($kind === 'beneficiaries')
    @if(auth()->user()->hasPermission('ngo.beneficiaries.manage'))<div class="card p-3 mb-3"><h2 class="h5">Register beneficiary</h2><form method="post" action="{{ route('ngo.beneficiaries.store') }}" class="row g-2">@csrf
        <div class="col-md-4"><label class="form-label">Name / group name</label><input name="name" class="form-control" required></div><div class="col-md-3"><label class="form-label">Type</label><select name="type" class="form-select">@foreach(['Individual','Household','Community','Institution','School','Health Facility','Farmer Group','Youth Group',"Women's Group",'Organization'] as $type)<option>{{ $type }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Phone</label><input name="phone" class="form-control"></div><div class="col-md-3"><label class="form-label">Registration stage</label><select name="registration_status" class="form-select">@foreach(['Registered','Verified','Eligible','Enrolled','Follow-up','Exited','Graduated'] as $status)<option>{{ $status }}</option>@endforeach</select></div>
        <div class="col-md-6"><label class="form-label">Assign to program</label><select name="program_id" class="form-select"><option value="">No program yet</option>@foreach($programs as $program)<option value="{{ $program->id }}">{{ $program->name }}</option>@endforeach</select></div>
        @if($sensitive)<div class="col-md-2"><label class="form-label">Gender</label><input name="gender" class="form-control"></div><div class="col-md-2"><label class="form-label">Date of birth</label><input name="date_of_birth" type="date" class="form-control"></div>@endif
        <div class="col-md-2"><label class="form-label">Country</label><input name="country" class="form-control"></div><div class="col-md-2"><label class="form-label">County / State</label><input name="county" class="form-control"></div><div class="col-md-2"><label class="form-label">District</label><input name="district" class="form-control"></div><div class="col-md-2"><label class="form-label">Ward</label><input name="ward" class="form-control"></div><div class="col-md-2"><label class="form-label">Community</label><input name="community" class="form-control"></div><div class="col-md-2"><label class="form-label">Village</label><input name="village" class="form-control"></div><div class="col-12"><button class="btn btn-success">Register</button></div>
    </form></div>@endif
    <div class="card p-3"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Beneficiary</th><th>Type</th><th>Programs</th><th>Location</th>@if($sensitive)<th>Gender / DOB</th>@endif<th>Registration</th><th>Status</th></tr></thead><tbody>@forelse($beneficiaries as $beneficiary)<tr><td><strong>{{ $beneficiary->name }}</strong><div class="small text-muted">{{ $beneficiary->beneficiary_number }} @if($beneficiary->phone)· {{ $beneficiary->phone }}@endif</div></td><td>{{ $beneficiary->type }}</td><td>{{ $beneficiary->programs->pluck('name')->join(', ') ?: '—' }}</td><td>{{ collect([$beneficiary->county, $beneficiary->district, $beneficiary->community, $beneficiary->village])->filter()->join(', ') ?: '—' }}</td>@if($sensitive)<td>{{ $beneficiary->gender ?: '—' }} · {{ $beneficiary->date_of_birth?->format('d M Y') ?: '—' }}</td>@endif<td>{{ $beneficiary->registered_on?->format('d M Y') }}</td><td>{{ $beneficiary->registration_status }}</td></tr>@empty<tr><td colspan="7" class="text-muted">No beneficiaries registered.</td></tr>@endforelse</tbody></table></div>{{ $beneficiaries->links() }}</div>
@elseif($kind === 'reports')
    <div class="row g-3 mb-3">@foreach(['Programs' => $programCount, 'Activities' => $activityCount, 'Active beneficiaries' => $beneficiaryCount, 'Active donors' => $donorCount] as $label => $value)<div class="col-sm-6 col-xl-3"><div class="card p-3"><div class="small text-uppercase fw-bold text-muted">{{ $label }}</div><div class="h3 mb-0">{{ number_format($value) }}</div></div></div>@endforeach</div>
    <div class="row g-3"><div class="col-md-6"><div class="card p-3"><h2 class="h5">Programs by status</h2>@forelse($programsByStatus as $row)<div class="d-flex justify-content-between border-bottom py-2"><span>{{ $row->status }}</span><strong>{{ $row->total }}</strong></div>@empty<p class="text-muted mb-0">No program data yet.</p>@endforelse</div></div><div class="col-md-6"><div class="card p-3"><h2 class="h5">Activities by status</h2>@forelse($activitiesByStatus as $row)<div class="d-flex justify-content-between border-bottom py-2"><span>{{ $row->status }}</span><strong>{{ $row->total }}</strong></div>@empty<p class="text-muted mb-0">No activity data yet.</p>@endforelse</div></div></div>
@endif
@endsection
