<?php

return [
    'name' => 'Hospitality',
    'slug' => 'hospitality',
    'type' => 'industry',
    'description' => 'Run reservations, rooms, housekeeping, front desk, guest profiles, restaurant POS, events, billing, and loyalty.',
    'sub_industries' => [
        'Hotel',
        'Resort',
        'Lodge',
        'Guest House',
        'Serviced Apartments',
        'Boutique Hotel',
        'Enterprise Hospitality',
        'Restaurant Group',
        'Conference Center',
        'Event Venue',
        'Holiday Apartments',
    ],
    'registration_sub_industries' => [
        'Hotel',
        'Resort',
        'Lodge',
        'Guest House',
        'Boutique Hotel',
        'Enterprise Hospitality',
        'Restaurant Group',
        'Conference Center',
        'Event Venue',
    ],
    'features' => [
        'Hotel Reservations',
        'Room Management',
        'Products',
        'Stock Management',
        'Housekeeping',
        'Front Desk',
        'Guest Profiles',
        'Staff Management',
        'Suppliers',
        'Procurement',
        'Restaurant POS',
        'Event Booking',
        'Billing',
        'Customer Loyalty',
    ],
    'core_modules' => [
        'CRM',
        'Clients',
        'Contacts',
        'Projects',
        'Quotations',
        'Invoices',
        'Receipts',
        'Finance',
        'Accounting',
        'Cost Centers',
        'Documents',
        'Letters',
        'Administration',
        'IAM',
        'Reporting',
        'Portal',
        'Notifications',
    ],
    'routes' => [
        'web' => [
            'dashboard' => 'hospitality.dashboard',
            'reservations' => 'hospitality.reservations.index',
            'rooms' => 'hospitality.rooms.index',
            'products' => 'products.index',
            'guests' => 'hospitality.guests.index',
            'staff' => 'hospitality.staff.index',
            'suppliers' => 'hospitality.suppliers.index',
            'procurement' => 'erp.procurement',
            'front_desk' => 'hospitality.front-desk.index',
            'check_in' => 'hospitality.check-ins.index',
            'check_out' => 'hospitality.check-outs.index',
            'housekeeping' => 'hospitality.housekeeping.index',
            'maintenance' => 'hospitality.maintenance.index',
            'restaurant' => 'hospitality.restaurant.index',
            'events' => 'hospitality.events.index',
            'reports' => 'hospitality.reports.index',
        ],
    ],
    'api' => [
        'prefix' => '/api/v1/industries/hospitality',
    ],
    'widgets' => [
        'Occupancy Rate',
        'Available Rooms',
        "Today's Check-ins",
        "Today's Check-outs",
        'Revenue Today',
        'Monthly Revenue',
        'Pending Reservations',
        'Guest Satisfaction',
        'Maintenance Requests',
        'Restaurant Sales',
    ],
    'kpi_cards' => [
        'Executive KPIs',
        'Risk Alerts',
        'Workflow Performance',
        'Compliance Status',
    ],
    'reports' => [
        'Occupancy Reports',
        'Revenue Reports',
        'Guest Reports',
        'Reservation Reports',
        'Housekeeping Reports',
        'Maintenance Reports',
        'Restaurant Reports',
        'Event Reports',
        'Loyalty Reports',
    ],
    'permissions' => [
        'hospitality.view',
        'hospitality.manage',
        'hospitality.reports',
        'hospitality.reservations.view',
        'hospitality.reservations.manage',
        'hospitality.rooms.view',
        'hospitality.rooms.manage',
        'hospitality.guests.view',
        'hospitality.guests.manage',
        'hospitality.housekeeping.view',
        'hospitality.housekeeping.manage',
        'hospitality.maintenance.view',
        'hospitality.maintenance.manage',
        'hospitality.restaurant.view',
        'hospitality.restaurant.manage',
        'hospitality.events.view',
        'hospitality.events.manage',
        'hospitality.billing.manage',
        'hospitality.finance.post',
    ],
    'roles' => [
        'Hotel Manager',
        'Front Desk Officer',
        'Reservations Officer',
        'Housekeeping Supervisor',
        'Housekeeping Staff',
        'Maintenance Officer',
        'Restaurant Manager',
        'Restaurant Staff',
        'Events Coordinator',
        'Finance Officer',
    ],
    'menus' => [
        ['label' => 'Dashboard', 'route' => 'hospitality.dashboard', 'icon' => 'bi-speedometer2'],
        ['label' => 'Reservations', 'route' => 'hospitality.reservations.index', 'icon' => 'bi-calendar-check'],
        ['label' => 'Rooms', 'route' => 'hospitality.rooms.index', 'icon' => 'bi-door-open'],
        ['label' => 'Products / Stock', 'route' => 'products.index', 'icon' => 'bi-box-seam'],
        ['label' => 'Guests', 'route' => 'hospitality.guests.index', 'icon' => 'bi-person-heart'],
        ['label' => 'Staff', 'route' => 'hospitality.staff.index', 'icon' => 'bi-people'],
        ['label' => 'Suppliers', 'route' => 'hospitality.suppliers.index', 'icon' => 'bi-truck'],
        ['label' => 'Procurement', 'route' => 'erp.procurement', 'icon' => 'bi-cart-check'],
        ['label' => 'Front Desk', 'route' => 'hospitality.front-desk.index', 'icon' => 'bi-building-check'],
        ['label' => 'Check-In', 'route' => 'hospitality.check-ins.index', 'icon' => 'bi-box-arrow-in-right'],
        ['label' => 'Check-Out', 'route' => 'hospitality.check-outs.index', 'icon' => 'bi-box-arrow-right'],
        ['label' => 'Housekeeping', 'route' => 'hospitality.housekeeping.index', 'icon' => 'bi-brush'],
        ['label' => 'Maintenance', 'route' => 'hospitality.maintenance.index', 'icon' => 'bi-tools'],
        ['label' => 'Restaurant', 'route' => 'hospitality.restaurant.index', 'icon' => 'bi-cup-hot'],
        ['label' => 'Events', 'route' => 'hospitality.events.index', 'icon' => 'bi-calendar-event'],
        ['label' => 'Billing', 'route' => 'finance.index', 'icon' => 'bi-bank'],
        ['label' => 'Loyalty Program', 'route' => 'hospitality.guests.index', 'icon' => 'bi-gem'],
        ['label' => 'Reports', 'route' => 'hospitality.reports.index', 'icon' => 'bi-bar-chart'],
    ],
    'tenant_isolated' => true,
    'role_permissions' => true,
    'dynamic_menus' => true,
    'dashboard_widgets' => true,
    'api_endpoints' => true,
    'subscription_activated' => true,
    'integrations' => [
        'crm' => 'Guest profiles sync to existing Clients and Contacts.',
        'finance' => 'Invoices, receipts, and journal entries flow through existing finance services and model hooks.',
        'restaurant' => 'Restaurant orders link to the existing POS module.',
    ],
];
