<div class="col-md-6"><label class="form-label">Name</label><input class="form-control" name="name" value="{{ old('name',$product->name) }}" required></div>
<div class="col-md-6"><label class="form-label">Product type</label><select class="form-select" name="product_type">@foreach(($productTypes ?? \App\Models\Product::PRODUCT_TYPES) as $value => $label)<option value="{{ $value }}" @selected(old('product_type',$product->product_type ?? 'simple') === $value)>{{ $label }}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">Category</label><select class="form-select" name="product_category_id"><option value="">None</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('product_category_id',$product->product_category_id)==$category->id)>{{ method_exists($category, 'path') ? $category->path() : $category->name }}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">Brand</label><select class="form-select" name="product_brand_id"><option value="">Generic / No Brand</option>@foreach(($brands ?? []) as $brand)<option value="{{ $brand->id }}" @selected(old('product_brand_id',$product->product_brand_id)==$brand->id)>{{ $brand->name }}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">SKU</label><input class="form-control" name="sku" value="{{ old('sku',$product->sku) }}"></div>
<div class="col-md-6"><label class="form-label">Barcode</label><input class="form-control" name="barcode" value="{{ old('barcode',$product->barcode) }}"></div>
<div class="col-md-4"><label class="form-label">Retail price</label><input class="form-control" type="number" step="0.01" inputmode="decimal" name="price" value="{{ old('price',$product->price ?? 0) }}" required></div>
<div class="col-md-4"><label class="form-label">Wholesale</label><input class="form-control" type="number" step="0.01" inputmode="decimal" name="wholesale_price" value="{{ old('wholesale_price',$product->wholesale_price) }}"></div>
<div class="col-md-4"><label class="form-label">Promo price</label><input class="form-control" type="number" step="0.01" inputmode="decimal" name="promotional_price" value="{{ old('promotional_price',$product->promotional_price) }}"></div>
<div class="col-md-6"><label class="form-label">Cost price</label><input class="form-control" type="number" step="0.01" inputmode="decimal" name="cost_price" value="{{ old('cost_price',$product->cost_price ?? 0) }}"></div>
<div class="col-md-6"><label class="form-label">Tax class</label><input class="form-control" name="tax_class" value="{{ old('tax_class',$product->tax_class) }}"></div>
<div class="col-md-4"><label class="form-label">Stock</label><input class="form-control" type="number" min="0" step="0.001" inputmode="decimal" name="stock_quantity" value="{{ old('stock_quantity',$product->stock_quantity ?? 0) }}"></div>
<div class="col-md-4"><label class="form-label">Unit</label><select class="form-select" name="stock_unit">@foreach($stockUnits as $value => $label)<option value="{{ $value }}" @selected(old('stock_unit',$product->stock_unit ?? 'pcs') === $value)>{{ $label }}</option>@endforeach</select></div>
<div class="col-md-4"><label class="form-label">Reorder level</label><input class="form-control" type="number" min="0" step="0.001" inputmode="decimal" name="reorder_level" value="{{ old('reorder_level',$product->reorder_level ?? 0) }}"></div>
<div class="col-12"><label class="form-label">Description</label><textarea class="form-control" name="description" rows="2">{{ old('description',$product->description) }}</textarea></div>
<div class="col-md-3"><label class="form-check"><input class="form-check-input" type="checkbox" name="track_inventory" value="1" @checked(old('track_inventory',$product->track_inventory ?? true))> <span class="form-check-label">Track stock</span></label></div>
<div class="col-md-3"><label class="form-check"><input class="form-check-input" type="checkbox" name="is_serialized" value="1" @checked(old('is_serialized',$product->is_serialized ?? false))> <span class="form-check-label">Serials</span></label></div>
<div class="col-md-3"><label class="form-check"><input class="form-check-input" type="checkbox" name="is_batch_tracked" value="1" @checked(old('is_batch_tracked',$product->is_batch_tracked ?? false))> <span class="form-check-label">Batches</span></label></div>
<div class="col-md-3"><label class="form-check"><input class="form-check-input" type="checkbox" name="is_expiry_tracked" value="1" @checked(old('is_expiry_tracked',$product->is_expiry_tracked ?? false))> <span class="form-check-label">Expiry</span></label></div>
<div class="col-12"><label class="form-check"><input class="form-check-input" type="checkbox" name="is_active" value="1" @checked(old('is_active',$product->is_active ?? true))> <span class="form-check-label">Active</span></label></div>
