<div class="col-md-6"><label class="form-label">Name</label><input class="form-control" name="name" value="{{ old('name',$product->name) }}" required></div>
<div class="col-md-6"><label class="form-label">Category</label><select class="form-select" name="product_category_id"><option value="">None</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('product_category_id',$product->product_category_id)==$category->id)>{{ $category->name }}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">SKU</label><input class="form-control" name="sku" value="{{ old('sku',$product->sku) }}"></div>
<div class="col-md-6"><label class="form-label">Price</label><input class="form-control" type="number" step="0.01" name="price" value="{{ old('price',$product->price ?? 0) }}" required></div>
<div class="col-md-6"><label class="form-label">Cost price</label><input class="form-control" type="number" step="0.01" name="cost_price" value="{{ old('cost_price',$product->cost_price ?? 0) }}"></div>
<div class="col-md-4"><label class="form-label">Stock</label><input class="form-control" type="number" min="0" step="0.001" name="stock_quantity" value="{{ old('stock_quantity',$product->stock_quantity ?? 0) }}"></div>
<div class="col-md-4"><label class="form-label">Unit</label><select class="form-select" name="stock_unit">@foreach($stockUnits as $value => $label)<option value="{{ $value }}" @selected(old('stock_unit',$product->stock_unit ?? 'pcs') === $value)>{{ $label }}</option>@endforeach</select></div>
<div class="col-md-4"><label class="form-label">Reorder level</label><input class="form-control" type="number" min="0" step="0.001" name="reorder_level" value="{{ old('reorder_level',$product->reorder_level ?? 0) }}"></div>
<div class="col-12"><label class="form-label">Description</label><textarea class="form-control" name="description" rows="2">{{ old('description',$product->description) }}</textarea></div>
<div class="col-12"><label class="form-check"><input class="form-check-input" type="checkbox" name="is_active" value="1" @checked(old('is_active',$product->is_active ?? true))> <span class="form-check-label">Active</span></label></div>
