@extends('layouts.app')
@section('title','Create User')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-3"><div><h1 class="h3 mb-1">Create user</h1><p class="text-muted mb-0">Enterprise user provisioning and invitation</p></div><a href="{{route('administration.index')}}" class="btn btn-outline-secondary">Back</a></div>
@if($errors->any())<div class="alert alert-danger">{{$errors->first()}}</div>@endif
<div class="card p-4"><div class="progress mb-4" style="height:8px"><div id="wizard-progress" class="progress-bar bg-warning" style="width:20%"></div></div>
<form method="post" action="{{route('administration.users.store')}}" id="user-wizard" enctype="multipart/form-data">@csrf
<section class="wizard-step"><h2 class="h5">1. Employee information</h2><div class="row g-3"><div class="col-md-6"><label class="form-label">Name</label><input class="form-control" name="name" value="{{old('name')}}" required></div><div class="col-md-6"><label class="form-label">Email</label><input class="form-control" type="email" name="email" value="{{old('email')}}" required></div><div class="col-md-6"><label class="form-label">Username</label><input class="form-control" name="username" value="{{old('username')}}" placeholder="Auto if blank"></div><div class="col-md-6"><label class="form-label">Phone</label><input class="form-control" name="phone" value="{{old('phone')}}"></div><div class="col-md-6"><label class="form-label">Employee number</label><input class="form-control" name="employee_number" value="{{old('employee_number')}}"></div><div class="col-md-6"><label class="form-label">Job title</label><input class="form-control" name="job_title" value="{{old('job_title')}}"></div><div class="col-md-6"><label class="form-label">Photo</label><input class="form-control" type="file" name="photo" accept="image/*"></div><div class="col-md-6"><label class="form-label">Signature</label><input class="form-control" type="file" name="signature" accept="image/*"></div></div></section>
<section class="wizard-step d-none"><h2 class="h5">2. Organization</h2><div class="row g-3"><div class="col-md-4"><label class="form-label">Branch</label><select class="form-select" name="branch_id"><option value="">None</option>@foreach($branches as $x)<option value="{{$x->id}}">{{$x->name}}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Department</label><select class="form-select" name="department_id"><option value="">None</option>@foreach($departments as $x)<option value="{{$x->id}}">{{$x->name}}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Manager</label><select class="form-select" name="manager_id"><option value="">None</option>@foreach($users as $x)<option value="{{$x->id}}">{{$x->name}}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Teams</label><select class="form-select" name="team_ids[]" multiple>@foreach($teams as $x)<option value="{{$x->id}}">{{$x->name}}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Approval level</label><input class="form-control" name="approval_level" placeholder="e.g. Level 2 / Up to KES 500,000"></div></div><p class="text-muted mt-3 mb-0">The active business is assigned automatically. Clone mode replaces organization and teams with the source user's setup.</p></section>
<section class="wizard-step d-none"><h2 class="h5">3. Access</h2><div class="row g-3 mb-3">@foreach([['default','Use Default Role','Recommended predefined access'],['clone','Copy Existing User','Clone role, organization and preferences'],['custom','Create Custom Role','Build reusable module permissions']] as [$value,$label,$help])<div class="col-md-4"><label class="card p-3 h-100"><span><input type="radio" name="setup_mode" value="{{$value}}" {{$value==='default'?'checked':''}}> <strong>{{$label}}</strong></span><small class="text-muted mt-2">{{$help}}</small></label></div>@endforeach</div><div data-mode="default"><label class="form-label">System role</label><select class="form-select" name="iam_role_id">@foreach($roles as $r)<option value="{{$r->id}}">{{$r->name}}</option>@endforeach</select></div><div data-mode="clone" class="d-none"><label class="form-label">User to copy</label><select class="form-select" name="clone_user_id"><option value="">Select user</option>@foreach($users as $x)<option value="{{$x->id}}">{{$x->name}} — {{$x->job_title}}</option>@endforeach</select></div><div data-mode="custom" class="d-none"><label class="form-label">Reusable role name</label><input class="form-control mb-3" name="custom_role_name">@foreach($permissions as $module=>$items)<div class="border rounded p-3 mb-2"><strong>{{$module}}</strong><div class="row mt-2">@foreach($items as $p)<label class="col-md-4 mb-2"><input type="checkbox" name="permissions[]" value="{{$p->id}}"> {{$p->name}}</label>@endforeach</div></div>@endforeach</div></section>
<section class="wizard-step d-none"><h2 class="h5">4. Review</h2><div id="review" class="border rounded p-3"></div><p class="text-muted mt-3">An invitation link will be emailed and will expire according to the security policy.</p></section>
<section class="wizard-step d-none text-center py-4"><h2 class="h4">5. Create user</h2><p>Provision the account and send the secure invitation now.</p><button class="btn btn-warning btn-lg" type="submit">Create user & send invitation</button></section>
<div class="d-flex justify-content-between mt-4"><button type="button" id="prev" class="btn btn-outline-secondary d-none">Previous</button><button type="button" id="next" class="btn btn-warning ms-auto">Next</button></div></form></div>
<script>
document.addEventListener('DOMContentLoaded',()=>{const steps=[...document.querySelectorAll('.wizard-step')],prev=document.querySelector('#prev'),next=document.querySelector('#next'),progress=document.querySelector('#wizard-progress'),form=document.querySelector('#user-wizard');let current=0;function show(){steps.forEach((s,i)=>s.classList.toggle('d-none',i!==current));prev.classList.toggle('d-none',current===0);next.classList.toggle('d-none',current===steps.length-1);progress.style.width=((current+1)/steps.length*100)+'%';if(current===3){const get=n=>form.elements[n]?.selectedOptions?.[0]?.text||form.elements[n]?.value||'Not set';document.querySelector('#review').innerHTML=`<strong>${get('name')}</strong><br>${get('email')}<br>${get('job_title')}<hr>Branch: ${get('branch_id')}<br>Department: ${get('department_id')}<br>Access method: ${get('setup_mode')}`;}}next.onclick=()=>{if(current===0&&!form.reportValidity())return;if(current<steps.length-1){current++;show()}};prev.onclick=()=>{if(current){current--;show()}};document.querySelectorAll('[name=setup_mode]').forEach(x=>x.onchange=()=>document.querySelectorAll('[data-mode]').forEach(p=>p.classList.toggle('d-none',p.dataset.mode!==x.value)));show();});
</script>
@endsection
