<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\AdministrationController;
use App\Http\Controllers\BusinessController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\CompanySettingsController;
use App\Http\Controllers\CostAccountingController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ErpController;
use App\Http\Controllers\FinanceController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\LandingController;
use App\Http\Controllers\LetterController;
use App\Http\Controllers\OnboardingController;
use App\Http\Controllers\PosOrderController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PortalController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\QuotationController;
use App\Http\Controllers\ReceiptController;
use App\Http\Controllers\RegistrationController;
use Illuminate\Support\Facades\Route;

Route::get('/', LandingController::class)->name('landing');
Route::get('/activate/{token}', [AdministrationController::class, 'activateForm'])->name('administration.activate');
Route::post('/activate/{token}', [AdministrationController::class, 'activate'])->name('administration.activate.store');
Route::get('/account-recovery/{token}', [AdministrationController::class, 'recoveryForm'])->name('administration.recovery');
Route::post('/account-recovery/{token}', [AdministrationController::class, 'recover'])->name('administration.recovery.store');

Route::get('/invoice/{token}', [InvoiceController::class, 'publicShow'])->name('public.invoices.show');
Route::get('/invoice/{token}/download', [InvoiceController::class, 'publicDownload'])->name('public.invoices.download');
Route::get('/track-order/{key}', [PosOrderController::class, 'track'])->name('public.orders.track');
Route::get('/verify/letter/{letter}', [LetterController::class, 'publicVerify'])->name('public.letters.verify');
Route::get('/portal/activate/{token}', [PortalController::class, 'activateForm'])->name('portal.activate');
Route::post('/portal/activate/{token}', [PortalController::class, 'activate'])->name('portal.activate.store');
Route::get('/hospitality/menu', [\Modules\Hospitality\Controllers\HospitalityFrontController::class, 'menu'])->name('public.hospitality.menu');
Route::post('/hospitality/menu/reserve', [\Modules\Hospitality\Controllers\HospitalityFrontController::class, 'reserve'])->name('public.hospitality.reserve');

Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthController::class, 'loginForm'])->name('login');
    Route::post('/login', [AuthController::class, 'login'])->name('login.store');
    Route::post('/login/otp', [AuthController::class, 'requestOtp'])->name('login.otp.request');
    Route::post('/login/otp/verify', [AuthController::class, 'verifyOtp'])->name('login.otp.verify');
    Route::post('/login/magic', [AuthController::class, 'requestMagicLink'])->name('login.magic.request');
    Route::get('/login/magic/{token}', [AuthController::class, 'consumeMagicLink'])->name('login.magic.consume');
    Route::get('/forgot-password', [AuthController::class, 'forgotForm'])->name('password.request');
    Route::post('/forgot-password', [AuthController::class, 'forgot'])->name('password.email');
    Route::get('/reset-password/{token}', [AuthController::class, 'resetForm'])->name('password.reset');
    Route::post('/reset-password', [AuthController::class, 'reset'])->name('password.update');
    Route::get('/register', fn () => redirect()->route('register.account'))->name('register');
    Route::get('/register/industry-dashboard', [RegistrationController::class, 'industryDashboard'])->name('register.industry-dashboard');
    Route::get('/register/account', [RegistrationController::class, 'account'])->name('register.account');
    Route::post('/register/account', [RegistrationController::class, 'storeAccount'])->name('register.account.store');
    Route::get('/register/company', [RegistrationController::class, 'company'])->name('register.company');
    Route::post('/register/company', [RegistrationController::class, 'storeCompany'])->name('register.company.store');
    Route::get('/register/plan', [RegistrationController::class, 'plan'])->name('register.plan');
    Route::post('/register/plan', [RegistrationController::class, 'storePlan'])->name('register.plan.store');
});

Route::middleware('auth')->group(function () {
    Route::get('/logout', [AuthController::class, 'logout'])->name('logout.get');
    Route::post('/logout', [AuthController::class, 'logout'])->name('logout');
    Route::get('/welcome', [RegistrationController::class, 'welcome'])->name('register.welcome');
    Route::get('/email/verify', [RegistrationController::class, 'verificationNotice'])->name('verification.notice');
    Route::post('/email/verification-notification', [RegistrationController::class, 'resendVerification'])->middleware('throttle:6,1')->name('verification.send');
    Route::get('/email/verify/{id}/{hash}', [RegistrationController::class, 'verifyEmail'])->middleware(['signed', 'throttle:6,1'])->name('verification.verify');
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::put('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::get('/portal', [PortalController::class, 'dashboard'])->name('portal.dashboard');

    Route::middleware(['admin', 'subscription.active'])->group(function () {
    Route::get('/onboarding/tenant', [OnboardingController::class, 'create'])->name('onboarding.tenant');
    Route::post('/onboarding/tenant', [OnboardingController::class, 'store'])->name('onboarding.tenant.store');
    Route::post('/businesses', [BusinessController::class, 'store'])->name('businesses.store');
    Route::post('/businesses/switch', [BusinessController::class, 'switch'])->name('businesses.switch');
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::middleware('permission:administration.view')->prefix('administration')->name('administration.')->group(function(){
        Route::get('/', [AdministrationController::class, 'index'])->name('index');
        Route::get('/users/create', [AdministrationController::class, 'createUser'])->name('users.create');
        Route::post('/users', [AdministrationController::class, 'storeUser'])->name('users.store');
        Route::put('/users/{user}', [AdministrationController::class, 'updateUser'])->name('users.update');
        Route::post('/users/{user}/status', [AdministrationController::class, 'status'])->name('users.status');
        Route::post('/users/{user}/unlock', [AdministrationController::class, 'unlock'])->name('users.unlock');
        Route::post('/users/{user}/force-reset', [AdministrationController::class, 'forceReset'])->name('users.force-reset');
        Route::post('/users/{user}/resend', [AdministrationController::class, 'resend'])->name('users.resend');
        Route::post('/access', [AdministrationController::class, 'assignAccess'])->name('access.assign');
        Route::post('/invitations/{invitation}/cancel', [AdministrationController::class, 'cancelInvitation'])->name('invitations.cancel');
        Route::post('/invitations/{invitation}/renew', [AdministrationController::class, 'renewInvitation'])->name('invitations.renew');
        Route::post('/roles', [AdministrationController::class, 'storeRole'])->name('roles.store');
        Route::post('/departments', [AdministrationController::class, 'storeDepartment'])->name('departments.store');
        Route::post('/branches', [AdministrationController::class, 'storeBranch'])->name('branches.store');
        Route::post('/teams', [AdministrationController::class, 'storeTeam'])->name('teams.store');
        Route::post('/workflows', [AdministrationController::class, 'storeWorkflow'])->name('workflows.store');
        Route::put('/security', [AdministrationController::class, 'security'])->name('security.update');
        Route::post('/devices/{device}/revoke', [AdministrationController::class, 'revokeDevice'])->name('devices.revoke');
        Route::put('/mail-settings', [AdministrationController::class, 'updateMail'])->middleware('permission:security.manage')->name('mail.update');
        Route::post('/mail-settings/test', [AdministrationController::class, 'testMail'])->middleware('permission:security.manage')->name('mail.test');
        Route::delete('/users/{user}', [AdministrationController::class, 'destroyUser'])->middleware('permission:users.deactivate')->name('users.destroy');
        Route::post('/users/{user}/logout-sessions', [AdministrationController::class, 'logoutSessions'])->middleware('permission:security.manage')->name('users.logout-sessions');
        Route::post('/users/{user}/recovery-link', [AdministrationController::class, 'recoveryLink'])->middleware('permission:security.manage')->name('users.recovery-link');
        Route::get('/users/{user}/activity', [AdministrationController::class, 'userActivity'])->middleware('permission:audit.view')->name('users.activity');
    });
    Route::get('/finance', [FinanceController::class, 'index'])->middleware('permission:finance.view')->name('finance.index');
    Route::post('/finance/accounts', [FinanceController::class, 'storeAccount'])->middleware('permission:finance.coa.manage')->name('finance.accounts.store');
    Route::put('/finance/accounts/{account}', [FinanceController::class, 'updateAccount'])->middleware('permission:finance.coa.manage')->name('finance.accounts.update');
    Route::post('/finance/accounts/{account}/deactivate', [FinanceController::class, 'deactivateAccount'])->middleware('permission:finance.coa.manage')->name('finance.accounts.deactivate');
    Route::post('/finance/journals', [FinanceController::class, 'storeJournal'])->middleware('permission:finance.gl.post')->name('finance.journals.store');
    Route::post('/finance/journals/{journal}/reverse', [FinanceController::class, 'reverse'])->middleware('permission:finance.gl.reverse')->name('finance.journals.reverse');
    Route::post('/finance/journals/{journal}/unreverse', [FinanceController::class, 'unreverse'])->middleware('permission:finance.gl.unreverse')->name('finance.journals.unreverse');
    Route::post('/finance/sync', [FinanceController::class, 'sync'])->middleware('permission:finance.gl.post')->name('finance.sync');
    Route::post('/finance/banks', [FinanceController::class, 'storeBank'])->middleware('permission:finance.banking.manage')->name('finance.banks.store');
    Route::post('/finance/bank-transactions', [FinanceController::class, 'storeBankTransaction'])->middleware('permission:finance.banking.manage')->name('finance.bank-transactions.store');
    Route::post('/finance/bank-transactions/{transaction}/reconcile', [FinanceController::class, 'reconcile'])->middleware('permission:finance.reconciliation.manage')->name('finance.bank-transactions.reconcile');
    Route::post('/finance/assets', [FinanceController::class, 'storeAsset'])->middleware('permission:finance.assets.manage')->name('finance.assets.store');
    Route::post('/finance/periods/close', [FinanceController::class, 'closePeriod'])->middleware('permission:finance.periods.manage')->name('finance.periods.close');
    Route::get('/accounting', [CostAccountingController::class, 'index'])->name('accounting.index');
    Route::post('/accounting/departments', [CostAccountingController::class, 'storeDepartment'])->name('accounting.departments.store');
    Route::put('/accounting/departments/{department}', [CostAccountingController::class, 'updateDepartment'])->name('accounting.departments.update');
    Route::post('/accounting/departments/{department}/archive', [CostAccountingController::class, 'archiveDepartment'])->name('accounting.departments.archive');
    Route::post('/accounting/cost-centers', [CostAccountingController::class, 'storeCostCenter'])->name('accounting.cost-centers.store');
    Route::put('/accounting/cost-centers/{costCenter}', [CostAccountingController::class, 'updateCostCenter'])->name('accounting.cost-centers.update');
    Route::post('/accounting/cost-centers/{costCenter}/archive', [CostAccountingController::class, 'archiveCostCenter'])->name('accounting.cost-centers.archive');
    Route::post('/accounting/budgets', [CostAccountingController::class, 'storeBudget'])->name('accounting.budgets.store');
    Route::put('/accounting/budgets/{budget}', [CostAccountingController::class, 'updateBudget'])->name('accounting.budgets.update');
    Route::post('/accounting/budgets/{budget}/approve', [CostAccountingController::class, 'approveBudget'])->name('accounting.budgets.approve');
    Route::post('/accounting/allocations', [CostAccountingController::class, 'storeAllocation'])->name('accounting.allocations.store');
    Route::post('/accounting/industry', [CostAccountingController::class, 'seedIndustry'])->name('accounting.industry.store');
    Route::post('/accounting/alerts/{alert}/acknowledge', [CostAccountingController::class, 'acknowledgeAlert'])->name('accounting.alerts.acknowledge');
    Route::get('/accounting/reports/{type}', [CostAccountingController::class, 'projectReport'])->name('accounting.reports.show');

    Route::prefix('communication')->name('communication.')->group(function () {
        Route::get('/', [\Shared\Communication\Controllers\CommunicationCenterController::class, 'index'])->middleware('permission:communication.view')->name('center');
        Route::post('/channels', [\Shared\Communication\Controllers\CommunicationCenterController::class, 'channel'])->middleware('permission:communication.create_channel')->name('channels.store');
        Route::post('/channels/{channel}/read', [\Shared\Communication\Controllers\CommunicationCenterController::class, 'markRead'])->middleware('permission:communication.view')->name('channels.read');
        Route::get('/attachments/{attachment}/download', [\Shared\Communication\Controllers\CommunicationCenterController::class, 'downloadAttachment'])->middleware('permission:communication.view')->name('attachments.download');
        Route::post('/messages', [\Shared\Communication\Controllers\CommunicationCenterController::class, 'message'])->middleware('permission:communication.send')->name('messages.store');
        Route::post('/messages/{message}/reactions', [\Shared\Communication\Controllers\CommunicationCenterController::class, 'react'])->middleware('permission:communication.send')->name('messages.reactions.store');
        Route::post('/messages/{message}/save', [\Shared\Communication\Controllers\CommunicationCenterController::class, 'save'])->middleware('permission:communication.view')->name('messages.save');
        Route::delete('/messages/{message}/save', [\Shared\Communication\Controllers\CommunicationCenterController::class, 'unsave'])->middleware('permission:communication.view')->name('messages.unsave');
        Route::post('/messages/{message}/pin', [\Shared\Communication\Controllers\CommunicationCenterController::class, 'pin'])->middleware('permission:communication.manage_channel')->name('messages.pin');
        Route::delete('/messages/{message}/pin', [\Shared\Communication\Controllers\CommunicationCenterController::class, 'unpin'])->middleware('permission:communication.manage_channel')->name('messages.unpin');
        Route::put('/messages/{message}', [\Shared\Communication\Controllers\CommunicationCenterController::class, 'updateMessage'])->middleware('permission:communication.send')->name('messages.update');
        Route::delete('/messages/{message}', [\Shared\Communication\Controllers\CommunicationCenterController::class, 'deleteMessage'])->middleware('permission:communication.delete_own')->name('messages.destroy');
        Route::post('/announcements', [\Shared\Communication\Controllers\CommunicationCenterController::class, 'announcement'])->middleware('permission:communication.announcements.create')->name('announcements.store');
        Route::post('/announcements/{announcement}/acknowledge', [\Shared\Communication\Controllers\CommunicationCenterController::class, 'acknowledge'])->middleware('permission:communication.view')->name('announcements.acknowledge');
        Route::put('/settings', [\Shared\Communication\Controllers\CommunicationCenterController::class, 'settings'])->middleware('permission:communication.settings')->name('settings.update');
    });

    Route::prefix('compliance/etims')->name('etims.')->group(function () {
        Route::get('/', [\Shared\Compliance\Etims\Controllers\EtimsComplianceController::class, 'index'])->middleware('permission:etims.view')->name('dashboard');
        Route::post('/retry', [\Shared\Compliance\Etims\Controllers\EtimsComplianceController::class, 'retryWeb'])->middleware('permission:etims.retry')->name('retry');
    });

    Route::get('/settings', [CompanySettingsController::class, 'edit'])->name('settings.edit');
    Route::put('/settings', [CompanySettingsController::class, 'update'])->name('settings.update');
    Route::post('/settings/payment-methods', [CompanySettingsController::class, 'storePaymentMethod'])->name('payment-methods.store');
    Route::delete('/settings/payment-methods/{paymentMethod}', [CompanySettingsController::class, 'deletePaymentMethod'])->name('payment-methods.destroy');
    Route::post('/settings/terms', [CompanySettingsController::class, 'storeTerms'])->name('terms.store');
    Route::delete('/settings/terms/{termsCondition}', [CompanySettingsController::class, 'deleteTerms'])->name('terms.destroy');
    Route::post('/settings/signatories', [CompanySettingsController::class, 'storeSignatory'])->name('signatories.store');
    Route::delete('/settings/signatories/{signatory}', [CompanySettingsController::class, 'deleteSignatory'])->name('signatories.destroy');

    Route::resource('clients', ClientController::class);
    Route::post('/clients/{client}/contacts', [ClientController::class, 'storeContact'])->name('clients.contacts.store');
    Route::post('/clients/{client}/sites', [ClientController::class, 'storeSite'])->name('clients.sites.store');
    Route::post('/clients/{client}/projects', [ClientController::class, 'storeProject'])->name('clients.projects.store');
    Route::post('/clients/{client}/merge', [ClientController::class, 'merge'])->name('clients.merge');
    Route::resource('projects', ProjectController::class);
    Route::get('/letters/delivery/{letter}', [LetterController::class, 'deliveryForm'])->name('letters.delivery');
    Route::post('/letters/{letter}/deliver', [LetterController::class, 'deliver'])->name('letters.deliver');
    Route::post('/letters/{letter}/submit', [LetterController::class, 'submit'])->name('letters.submit');
    Route::post('/letters/{letter}/approve', [LetterController::class, 'approve'])->name('letters.approve');
    Route::post('/letters/{letter}/archive', [LetterController::class, 'archive'])->name('letters.archive');
    Route::get('/letters/{letter}/download/{format?}', [LetterController::class, 'download'])->name('letters.download');
    Route::get('/letters/{letter}/preview', [LetterController::class, 'preview'])->name('letters.preview');
    Route::post('/letters/images', [LetterController::class, 'uploadImage'])->name('letters.images.store');
    Route::post('/letter-templates', [LetterController::class, 'storeTemplate'])->name('letters.templates.store');
    Route::get('/invoices/{invoice}/letters/balance', [LetterController::class, 'fromInvoice'])->name('letters.from-invoice');
    Route::get('/receipts/{receipt}/letters/acknowledgement', [LetterController::class, 'fromReceipt'])->name('letters.from-receipt');
    Route::get('/projects/{project}/letters/handover', [LetterController::class, 'fromProject'])->name('letters.from-project');
    Route::get('/warranties/{warranty}/letters/warranty', [LetterController::class, 'fromWarranty'])->name('letters.from-warranty');
    Route::resource('letters', LetterController::class)->except(['destroy']);
    Route::get('/erp/profit', [ErpController::class, 'profit'])->name('erp.profit');
    Route::get('/erp/procurement', [ErpController::class, 'procurement'])->name('erp.procurement');
    Route::get('/erp/warranties', [ErpController::class, 'warranties'])->name('erp.warranties');
    Route::get('/erp/portal', [ErpController::class, 'portal'])->name('erp.portal');
    Route::get('/erp/templates', [ErpController::class, 'templates'])->name('erp.templates');
    Route::get('/erp/reports', [ErpController::class, 'reports'])->name('erp.reports');
    Route::post('/projects/{project}/costs', [ErpController::class, 'storeProjectCost'])->name('projects.costs.store');
    Route::post('/projects/{project}/expenses', [ErpController::class, 'storeProjectExpense'])->name('projects.expenses.store');
    Route::post('/projects/{project}/documents', [ErpController::class, 'storeProjectDocument'])->name('projects.documents.store');
    Route::get('/erp/project-documents/{projectDocument}/download', [ErpController::class, 'downloadProjectDocument'])->name('erp.project-documents.download');
    Route::post('/projects/{project}/handovers', [ErpController::class, 'storeHandover'])->name('projects.handovers.store');
    Route::post('/erp/suppliers', [ErpController::class, 'storeSupplier'])->name('erp.suppliers.store');
    Route::post('/erp/supplier-quotes', [ErpController::class, 'storeSupplierQuote'])->name('erp.supplier-quotes.store');
    Route::post('/erp/purchase-orders', [ErpController::class, 'storePurchaseOrder'])->name('erp.purchase-orders.store');
    Route::post('/erp/goods-received', [ErpController::class, 'storeGoodsReceived'])->name('erp.goods-received.store');
    Route::post('/erp/supplier-invoices', [ErpController::class, 'storeSupplierInvoice'])->name('erp.supplier-invoices.store');
    Route::post('/erp/supplier-invoices/{supplierInvoice}/payments', [ErpController::class, 'storeSupplierPayment'])->name('erp.supplier-payments.store');
    Route::post('/erp/warranties', [ErpController::class, 'storeWarranty'])->name('erp.warranties.store');
    Route::post('/erp/warranties/{warranty}/claims', [ErpController::class, 'storeWarrantyClaim'])->name('erp.warranty-claims.store');
    Route::post('/erp/portal/invitations', [ErpController::class, 'storePortalInvite'])->name('erp.portal-invitations.store');
    Route::post('/erp/templates', [ErpController::class, 'storeTemplate'])->name('erp.templates.store');
    Route::put('/erp/users/{user}/auth-settings', [ErpController::class, 'updateAuthSettings'])->name('erp.users.auth-settings');
    Route::resource('products', ProductController::class)->only(['index', 'store', 'update', 'destroy']);
    Route::post('/products/import', [ProductController::class, 'import'])->name('products.import');
    Route::get('/products/export', [ProductController::class, 'export'])->name('products.export');
    Route::post('/products/{product}/stock', [ProductController::class, 'updateStock'])->name('products.stock.update');
    Route::post('/product-categories', [ProductController::class, 'storeCategory'])->name('product-categories.store');
    Route::resource('pos-orders', PosOrderController::class)->only(['index', 'create', 'store', 'show', 'edit', 'update', 'destroy']);
    Route::post('/pos-orders/import', [PosOrderController::class, 'import'])->name('pos-orders.import');
    Route::post('/pos-orders/{posOrder}/approve', [PosOrderController::class, 'approve'])->name('pos-orders.approve');
    Route::post('/pos-orders/{posOrder}/payments', [PosOrderController::class, 'recordPayment'])->name('pos-orders.payments.store');
    Route::get('/pos-orders-report', [PosOrderController::class, 'report'])->name('pos-orders.report');

    Route::prefix('retail')->name('retail.')->middleware('module.enabled:retail')->group(function () {
        Route::get('/', \Modules\Retail\Controllers\RetailDashboardController::class)->middleware('permission:retail.view')->name('dashboard');
        Route::get('/pos', [\Modules\Retail\Controllers\RetailPosController::class, 'index'])->middleware('permission:retail.pos.view')->name('pos.index');
        Route::post('/pos/sales', [\Modules\Retail\Controllers\RetailPosController::class, 'store'])->middleware('permission:retail.pos.manage')->name('pos.sales.store');
        Route::post('/pos/drawers', [\Modules\Retail\Controllers\RetailPosController::class, 'openDrawer'])->middleware('permission:retail.pos.manage')->name('pos.drawers.open');
        Route::post('/pos/drawers/{drawer}/close', [\Modules\Retail\Controllers\RetailPosController::class, 'closeDrawer'])->middleware('permission:retail.pos.manage')->name('pos.drawers.close');
        Route::post('/pos/orders/{posOrder}/void', [\Modules\Retail\Controllers\RetailPosController::class, 'void'])->middleware('permission:retail.pos.manage')->name('pos.orders.void');
        Route::get('/products', [\Modules\Retail\Controllers\RetailCatalogController::class, 'index'])->middleware('permission:retail.products.view')->name('products.index');
        Route::post('/products/profile', [\Modules\Retail\Controllers\RetailCatalogController::class, 'storeProfile'])->middleware('permission:retail.products.manage')->name('products.profile');
        Route::get('/inventory', [\Modules\Retail\Controllers\RetailInventoryController::class, 'index'])->middleware('permission:retail.inventory.view')->name('inventory.index');
        Route::post('/inventory/adjust', [\Modules\Retail\Controllers\RetailInventoryController::class, 'adjust'])->middleware('permission:retail.inventory.manage')->name('inventory.adjust');
        Route::post('/inventory/reserve', [\Modules\Retail\Controllers\RetailInventoryController::class, 'reserve'])->middleware('permission:retail.inventory.manage')->name('inventory.reserve');
        Route::post('/inventory/transfer', [\Modules\Retail\Controllers\RetailInventoryController::class, 'transfer'])->middleware('permission:retail.inventory.manage')->name('inventory.transfer');
        Route::post('/inventory/replenishment', [\Modules\Retail\Controllers\RetailInventoryController::class, 'replenish'])->middleware('permission:retail.inventory.manage')->name('inventory.replenishment');
        Route::post('/inventory/replenishment/{plan}/purchase-order', [\Modules\Retail\Controllers\RetailInventoryController::class, 'purchaseOrder'])->middleware('permission:retail.procurement.manage')->name('inventory.replenishment.purchase-order');
        Route::post('/inventory/cycle-counts', [\Modules\Retail\Controllers\RetailInventoryController::class, 'cycleCount'])->middleware('permission:retail.warehousing.manage')->name('inventory.cycle-counts.store');
        Route::get('/warehousing', [\Modules\Retail\Controllers\RetailWarehouseController::class, 'index'])->middleware('permission:retail.warehousing.view')->name('warehousing.index');
        Route::post('/warehousing', [\Modules\Retail\Controllers\RetailWarehouseController::class, 'store'])->middleware('permission:retail.warehousing.manage')->name('warehousing.store');
        Route::post('/warehousing/zones', [\Modules\Retail\Controllers\RetailWarehouseController::class, 'storeZone'])->middleware('permission:retail.warehousing.manage')->name('warehousing.zones.store');
        Route::post('/warehousing/bins', [\Modules\Retail\Controllers\RetailWarehouseController::class, 'storeBin'])->middleware('permission:retail.warehousing.manage')->name('warehousing.bins.store');
        Route::get('/orders', [\Modules\Retail\Controllers\RetailOrderController::class, 'index'])->middleware('permission:retail.orders.view')->name('orders.index');
        Route::post('/orders', [\Modules\Retail\Controllers\RetailOrderController::class, 'store'])->middleware('permission:retail.orders.manage')->name('orders.store');
        Route::post('/orders/customers', [\Modules\Retail\Controllers\RetailOrderController::class, 'storeCustomer'])->middleware('permission:retail.customers.manage')->name('orders.customers.store');
        Route::post('/orders/{order}/fulfillment', [\Modules\Retail\Controllers\RetailOrderController::class, 'routeFulfillment'])->middleware('permission:retail.orders.manage')->name('orders.fulfillment.route');
        Route::get('/deliveries', [\Modules\Retail\Controllers\RetailDeliveryController::class, 'index'])->middleware('permission:retail.orders.view')->name('deliveries.index');
        Route::post('/deliveries', [\Modules\Retail\Controllers\RetailDeliveryController::class, 'store'])->middleware('permission:retail.orders.manage')->name('deliveries.store');
        Route::get('/customers', [\Modules\Retail\Controllers\RetailCustomerController::class, 'index'])->middleware('permission:retail.customers.view')->name('customers.index');
        Route::post('/customers/profile', [\Modules\Retail\Controllers\RetailCustomerController::class, 'storeProfile'])->middleware('permission:retail.customers.manage')->name('customers.profile');
        Route::post('/customers/offers', [\Modules\Retail\Controllers\RetailCustomerController::class, 'storeOffer'])->middleware('permission:retail.promotions.manage')->name('customers.offers.store');
        Route::get('/loyalty-programs', [\Modules\Retail\Controllers\RetailLoyaltyController::class, 'index'])->middleware('permission:retail.loyalty.view')->name('loyalty.index');
        Route::post('/loyalty-programs/enroll', [\Modules\Retail\Controllers\RetailLoyaltyController::class, 'enroll'])->middleware('permission:retail.loyalty.manage')->name('loyalty.enroll');
        Route::get('/promotions', [\Modules\Retail\Controllers\RetailPromotionController::class, 'index'])->middleware('permission:retail.promotions.view')->name('promotions.index');
        Route::post('/promotions', [\Modules\Retail\Controllers\RetailPromotionController::class, 'store'])->middleware('permission:retail.promotions.manage')->name('promotions.store');
        Route::get('/gift-cards', [\Modules\Retail\Controllers\RetailGiftCardController::class, 'index'])->middleware('permission:retail.gift-cards.view')->name('gift-cards.index');
        Route::post('/gift-cards', [\Modules\Retail\Controllers\RetailGiftCardController::class, 'issue'])->middleware('permission:retail.gift-cards.manage')->name('gift-cards.issue');
        Route::post('/gift-cards/{giftCard}/recharge', [\Modules\Retail\Controllers\RetailGiftCardController::class, 'recharge'])->middleware('permission:retail.gift-cards.manage')->name('gift-cards.recharge');
        Route::get('/returns', [\Modules\Retail\Controllers\RetailReturnController::class, 'index'])->middleware('permission:retail.returns.view')->name('returns.index');
        Route::post('/returns', [\Modules\Retail\Controllers\RetailReturnController::class, 'store'])->middleware('permission:retail.returns.manage')->name('returns.store');
        Route::post('/returns/{returnAuthorization}/approve', [\Modules\Retail\Controllers\RetailReturnController::class, 'approve'])->middleware('permission:retail.returns.manage')->name('returns.approve');
        Route::get('/procurement', [\Modules\Retail\Controllers\RetailOperationsController::class, 'procurement'])->middleware('permission:retail.procurement.view')->name('procurement.index');
        Route::get('/suppliers', [\Modules\Retail\Controllers\RetailOperationsController::class, 'suppliers'])->middleware('permission:retail.suppliers.view')->name('suppliers.index');
        Route::post('/suppliers', [\Modules\Retail\Controllers\RetailOperationsController::class, 'storeSupplier'])->middleware('permission:retail.suppliers.manage')->name('suppliers.store');
        Route::post('/suppliers/{supplier}/contracts', [\Modules\Retail\Controllers\RetailOperationsController::class, 'storeSupplierContract'])->middleware('permission:retail.suppliers.manage')->name('suppliers.contracts.store');
        Route::get('/branches', [\Modules\Retail\Controllers\RetailOperationsController::class, 'branches'])->middleware('permission:retail.branches.view')->name('branches.index');
        Route::post('/branches', [\Modules\Retail\Controllers\RetailOperationsController::class, 'storeBranch'])->middleware('permission:retail.branches.manage')->name('branches.store');
        Route::get('/ecommerce', [\Modules\Retail\Controllers\RetailOperationsController::class, 'ecommerce'])->middleware('permission:retail.ecommerce.view')->name('ecommerce.index');
        Route::post('/ecommerce', [\Modules\Retail\Controllers\RetailOperationsController::class, 'storeEcommerce'])->middleware('permission:retail.ecommerce.manage')->name('ecommerce.store');
        Route::post('/ecommerce/{integration}/sync', [\Modules\Retail\Controllers\RetailOperationsController::class, 'syncEcommerce'])->middleware('permission:retail.ecommerce.manage')->name('ecommerce.sync');
        Route::get('/analytics', [\Modules\Retail\Controllers\RetailOperationsController::class, 'analytics'])->middleware('permission:retail.analytics.view')->name('analytics.index');
        Route::get('/reports', [\Modules\Retail\Controllers\RetailOperationsController::class, 'reports'])->middleware('permission:retail.reports')->name('reports.index');
        Route::get('/smart-scanning', [\Modules\Retail\Controllers\SmartScanningController::class, 'index'])->middleware('permission:retail.scanning.view')->name('scanning.index');
        Route::post('/smart-scanning/scan', [\Modules\Retail\Controllers\SmartScanningController::class, 'scan'])->middleware('permission:retail.scanning.manage')->name('scanning.scan');
        Route::get('/smart-scanning/devices', [\Modules\Retail\Controllers\SmartScanningController::class, 'devices'])->middleware('permission:retail.scanning.view')->name('scanning.devices');
        Route::post('/smart-scanning/devices', [\Modules\Retail\Controllers\SmartScanningController::class, 'storeDevice'])->middleware('permission:retail.scanning.manage')->name('scanning.devices.store');
        Route::get('/smart-scanning/batches', [\Modules\Retail\Controllers\SmartScanningController::class, 'batches'])->middleware('permission:retail.scanning.compliance')->name('scanning.batches');
        Route::post('/smart-scanning/batches', [\Modules\Retail\Controllers\SmartScanningController::class, 'storeBatch'])->middleware('permission:retail.scanning.compliance')->name('scanning.batches.store');
        Route::post('/smart-scanning/batches/{batch}/recall', [\Modules\Retail\Controllers\SmartScanningController::class, 'recall'])->middleware('permission:retail.scanning.compliance')->name('scanning.batches.recall');
        Route::get('/settings', [\Modules\Retail\Controllers\RetailOperationsController::class, 'settings'])->middleware('permission:retail.settings.manage')->name('settings.index');
        Route::post('/settings/tax-jurisdictions', [\Modules\Retail\Controllers\RetailOperationsController::class, 'storeTaxJurisdiction'])->middleware('permission:retail.settings.manage')->name('settings.tax-jurisdictions.store');
    });

    Route::prefix('hospitality')->name('hospitality.')->middleware('module.enabled:hospitality')->group(function () {
        Route::get('/', \Modules\Hospitality\Controllers\HospitalityDashboardController::class)->name('dashboard');
        Route::get('/reservations', [\Modules\Hospitality\Controllers\ReservationController::class, 'index'])->name('reservations.index');
        Route::post('/reservations', [\Modules\Hospitality\Controllers\ReservationController::class, 'store'])->name('reservations.store');
        Route::put('/reservations/{reservation}', [\Modules\Hospitality\Controllers\ReservationController::class, 'update'])->name('reservations.update');
        Route::get('/rooms', [\Modules\Hospitality\Controllers\RoomController::class, 'index'])->name('rooms.index');
        Route::post('/room-types', [\Modules\Hospitality\Controllers\RoomController::class, 'storeType'])->name('room-types.store');
        Route::post('/rooms', [\Modules\Hospitality\Controllers\RoomController::class, 'store'])->name('rooms.store');
        Route::patch('/rooms/{room}/status', [\Modules\Hospitality\Controllers\RoomController::class, 'updateStatus'])->name('rooms.status');
        Route::get('/guests', [\Modules\Hospitality\Controllers\GuestController::class, 'index'])->name('guests.index');
        Route::post('/guests', [\Modules\Hospitality\Controllers\GuestController::class, 'store'])->name('guests.store');
        Route::post('/guests/{guest}/loyalty', [\Modules\Hospitality\Controllers\GuestController::class, 'enrollLoyalty'])->name('guests.loyalty');
        Route::get('/staff', [\Modules\Hospitality\Controllers\StaffController::class, 'index'])->name('staff.index');
        Route::post('/staff', [\Modules\Hospitality\Controllers\StaffController::class, 'store'])->name('staff.store');
        Route::patch('/staff/{staff}', [\Modules\Hospitality\Controllers\StaffController::class, 'update'])->name('staff.update');
        Route::get('/suppliers', [\Modules\Hospitality\Controllers\SupplierController::class, 'index'])->name('suppliers.index');
        Route::post('/suppliers', [\Modules\Hospitality\Controllers\SupplierController::class, 'store'])->name('suppliers.store');
        Route::get('/front-desk', [\Modules\Hospitality\Controllers\FrontDeskController::class, 'index'])->name('front-desk.index');
        Route::get('/check-ins', [\Modules\Hospitality\Controllers\CheckInController::class, 'index'])->name('check-ins.index');
        Route::post('/check-ins', [\Modules\Hospitality\Controllers\CheckInController::class, 'store'])->name('check-ins.store');
        Route::get('/check-outs', [\Modules\Hospitality\Controllers\CheckOutController::class, 'index'])->name('check-outs.index');
        Route::post('/check-outs', [\Modules\Hospitality\Controllers\CheckOutController::class, 'store'])->name('check-outs.store');
        Route::get('/housekeeping', [\Modules\Hospitality\Controllers\HousekeepingController::class, 'index'])->name('housekeeping.index');
        Route::post('/housekeeping', [\Modules\Hospitality\Controllers\HousekeepingController::class, 'store'])->name('housekeeping.store');
        Route::patch('/housekeeping/{task}', [\Modules\Hospitality\Controllers\HousekeepingController::class, 'update'])->name('housekeeping.update');
        Route::get('/maintenance', [\Modules\Hospitality\Controllers\MaintenanceController::class, 'index'])->name('maintenance.index');
        Route::post('/maintenance', [\Modules\Hospitality\Controllers\MaintenanceController::class, 'store'])->name('maintenance.store');
        Route::patch('/maintenance/{maintenanceRequest}', [\Modules\Hospitality\Controllers\MaintenanceController::class, 'update'])->name('maintenance.update');
        Route::get('/restaurant', [\Modules\Hospitality\Controllers\RestaurantController::class, 'index'])->name('restaurant.index');
        Route::post('/restaurant/menu-import', [\Modules\Hospitality\Controllers\RestaurantController::class, 'importMenu'])->name('restaurant.menu-import');
        Route::post('/restaurant/tables', [\Modules\Hospitality\Controllers\RestaurantController::class, 'storeTable'])->name('restaurant.tables.store');
        Route::patch('/restaurant/tables/{table}/status', [\Modules\Hospitality\Controllers\RestaurantController::class, 'updateTableStatus'])->name('restaurant.tables.status');
        Route::post('/restaurant/units', [\Modules\Hospitality\Controllers\RestaurantController::class, 'storeUnit'])->name('restaurant.units.store');
        Route::post('/restaurant/ingredients', [\Modules\Hospitality\Controllers\RestaurantController::class, 'storeIngredient'])->name('restaurant.ingredients.store');
        Route::post('/restaurant/recipes', [\Modules\Hospitality\Controllers\RestaurantController::class, 'storeRecipe'])->name('restaurant.recipes.store');
        Route::post('/restaurant/purchases', [\Modules\Hospitality\Controllers\RestaurantController::class, 'storePurchase'])->name('restaurant.purchases.store');
        Route::patch('/restaurant/orders/{order}/production', [\Modules\Hospitality\Controllers\RestaurantController::class, 'updateProduction'])->name('restaurant.production.update');
        Route::post('/restaurant', [\Modules\Hospitality\Controllers\RestaurantController::class, 'store'])->name('restaurant.store');
        Route::get('/events', [\Modules\Hospitality\Controllers\EventBookingController::class, 'index'])->name('events.index');
        Route::post('/events', [\Modules\Hospitality\Controllers\EventBookingController::class, 'store'])->name('events.store');
        Route::get('/reports', [\Modules\Hospitality\Controllers\HospitalityReportController::class, 'index'])->name('reports.index');
        Route::get('/reports/live', [\Modules\Hospitality\Controllers\HospitalityReportController::class, 'live'])->name('reports.live');
    });

    Route::prefix('fitness')->name('fitness.')->middleware('module.enabled:fitness')->group(function () {
        Route::get('/', \Modules\Fitness\Controllers\FitnessDashboardController::class)->middleware('permission:fitness.view')->name('dashboard');
        Route::get('/memberships', [\Modules\Fitness\Controllers\MembershipPlanController::class, 'index'])->middleware('permission:fitness.memberships.view')->name('memberships.index');
        Route::post('/membership-plans', [\Modules\Fitness\Controllers\MembershipPlanController::class, 'store'])->middleware('permission:fitness.memberships.create')->name('membership-plans.store');
        Route::patch('/membership-plans/{membershipPlan}', [\Modules\Fitness\Controllers\MembershipPlanController::class, 'update'])->middleware('permission:fitness.memberships.edit')->name('membership-plans.update');
        Route::get('/members', [\Modules\Fitness\Controllers\MemberController::class, 'index'])->middleware('permission:fitness.members.view')->name('members.index');
        Route::post('/members', [\Modules\Fitness\Controllers\MemberController::class, 'store'])->middleware('permission:fitness.members.create')->name('members.store');
        Route::get('/members/{member}/card', [\Modules\Fitness\Controllers\MemberController::class, 'card'])->middleware('permission:fitness.members.view')->name('members.card');
        Route::patch('/members/{member}', [\Modules\Fitness\Controllers\MemberController::class, 'update'])->middleware('permission:fitness.members.edit')->name('members.update');
        Route::post('/member-memberships', [\Modules\Fitness\Controllers\MemberMembershipController::class, 'store'])->middleware('permission:fitness.memberships.create')->name('member-memberships.store');
        Route::post('/member-memberships/{memberMembership}/renew', [\Modules\Fitness\Controllers\MemberMembershipController::class, 'renew'])->middleware('permission:fitness.memberships.edit')->name('member-memberships.renew');
        Route::post('/member-memberships/{memberMembership}/freeze', [\Modules\Fitness\Controllers\MemberMembershipController::class, 'freeze'])->middleware('permission:fitness.memberships.edit')->name('member-memberships.freeze');
        Route::post('/member-memberships/{memberMembership}/invoice', [\Modules\Fitness\Controllers\MemberMembershipController::class, 'invoice'])->middleware('permission:fitness.payments.manage')->name('member-memberships.invoice');
        Route::post('/member-memberships/{memberMembership}/payments', [\Modules\Fitness\Controllers\MemberMembershipController::class, 'payment'])->middleware('permission:fitness.payments.manage')->name('member-memberships.payments.store');
        Route::post('/member-memberships/{memberMembership}/record-payment', [\Modules\Fitness\Controllers\MemberMembershipController::class, 'recordAndEmailPayment'])->middleware('permission:fitness.payments.manage')->name('member-memberships.record-payment');
        Route::get('/trainers', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'trainers'])->middleware('permission:fitness.trainers.view')->name('trainers.index');
        Route::post('/trainers', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'storeTrainer'])->middleware('permission:fitness.trainers.manage')->name('trainers.store');
        Route::get('/attendance', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'attendance'])->middleware('permission:fitness.attendance.view')->name('attendance.index');
        Route::get('/attendance/export', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'attendanceCsv'])->middleware('permission:fitness.attendance.view')->name('attendance.export');
        Route::get('/check-in', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'checkInIndex'])->middleware('permission:fitness.attendance.view')->name('check-in.index');
        Route::post('/check-in', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'checkIn'])->middleware('permission:fitness.attendance.manage')->name('check-in.store');
        Route::post('/check-out', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'checkOut'])->middleware('permission:fitness.attendance.manage')->name('check-out.store');
        Route::get('/classes', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'classes'])->middleware('permission:fitness.classes.view')->name('classes.index');
        Route::post('/classes', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'storeClass'])->middleware('permission:fitness.classes.manage')->name('classes.store');
        Route::post('/class-sessions', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'storeClassSession'])->middleware('permission:fitness.classes.manage')->name('class-sessions.store');
        Route::post('/class-bookings', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'bookClass'])->middleware('permission:fitness.classes.manage')->name('class-bookings.store');
        Route::patch('/class-bookings/{booking}/attendance', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'markClassAttendance'])->middleware('permission:fitness.classes.manage')->name('class-bookings.attendance');
        Route::get('/programs', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'programs'])->middleware('permission:fitness.programs.view')->name('programs.index');
        Route::post('/programs', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'storeProgram'])->middleware('permission:fitness.programs.manage')->name('programs.store');
        Route::post('/program-assignments', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'assignProgram'])->middleware('permission:fitness.programs.manage')->name('program-assignments.store');
        Route::get('/exercises', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'exercises'])->middleware('permission:fitness.exercises.view')->name('exercises.index');
        Route::post('/exercises', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'storeExercise'])->middleware('permission:fitness.exercises.manage')->name('exercises.store');
        Route::get('/health-profiles', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'healthProfiles'])->middleware('permission:fitness.health.view')->name('health-profiles.index');
        Route::post('/health-profiles', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'storeHealthProfile'])->middleware('permission:fitness.health.manage')->name('health-profiles.store');
        Route::get('/assessments', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'assessments'])->middleware('permission:fitness.assessments.view')->name('assessments.index');
        Route::post('/assessments', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'storeAssessment'])->middleware('permission:fitness.assessments.manage')->name('assessments.store');
        Route::get('/personal-training', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'personalTraining'])->middleware('permission:fitness.personal-training.view')->name('personal-training.index');
        Route::post('/pt-packages', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'storePtPackage'])->middleware('permission:fitness.personal-training.manage')->name('pt-packages.store');
        Route::post('/pt-sessions', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'storePtSession'])->middleware('permission:fitness.personal-training.manage')->name('pt-sessions.store');
        Route::get('/nutrition', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'nutrition'])->middleware('permission:fitness.nutrition.view')->name('nutrition.index');
        Route::post('/nutrition-plans', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'storeNutritionPlan'])->middleware('permission:fitness.nutrition.manage')->name('nutrition-plans.store');
        Route::post('/nutrition-assignments', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'assignNutritionPlan'])->middleware('permission:fitness.nutrition.manage')->name('nutrition-assignments.store');
        Route::get('/nutrition-assignments/{assignment}/download', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'downloadNutritionAssignment'])->middleware('permission:fitness.nutrition.view')->name('nutrition-assignments.download');
        Route::get('/challenges', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'challenges'])->middleware('permission:fitness.challenges.view')->name('challenges.index');
        Route::post('/challenges', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'storeChallenge'])->middleware('permission:fitness.challenges.manage')->name('challenges.store');
        Route::post('/challenge-participants', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'joinChallenge'])->middleware('permission:fitness.challenges.manage')->name('challenge-participants.store');
        Route::get('/equipment', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'equipment'])->middleware('permission:fitness.equipment.view')->name('equipment.index');
        Route::post('/equipment', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'storeEquipment'])->middleware('permission:fitness.equipment.manage')->name('equipment.store');
        Route::post('/equipment-maintenance', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'storeMaintenance'])->middleware('permission:fitness.equipment.manage')->name('equipment-maintenance.store');
        Route::get('/reports', [\Modules\Fitness\Controllers\FitnessOperationsController::class, 'reports'])->middleware('permission:fitness.reports')->name('reports.index');
    });

    Route::prefix('salon-spa')->name('salon.')->middleware('module.enabled:salon')->group(function () {
        Route::get('/', \Modules\Salon\Controllers\SalonDashboardController::class)->middleware('permission:salon.view')->name('dashboard');
        Route::get('/appointments', [\Modules\Salon\Controllers\SalonOperationsController::class, 'appointments'])->middleware('permission:salon.appointments.view')->name('appointments.index');
        Route::post('/appointments', [\Modules\Salon\Controllers\SalonOperationsController::class, 'storeAppointment'])->middleware('permission:salon.appointments.manage')->name('appointments.store');
        Route::post('/appointments/{appointment}/complete', [\Modules\Salon\Controllers\SalonOperationsController::class, 'completeAppointment'])->middleware('permission:salon.appointments.manage')->name('appointments.complete');
        Route::get('/clients', [\Modules\Salon\Controllers\SalonOperationsController::class, 'clients'])->middleware('permission:salon.loyalty.view')->name('clients.index');
        Route::post('/clients', [\Modules\Salon\Controllers\SalonOperationsController::class, 'storeClient'])->middleware('permission:salon.loyalty.manage')->name('clients.store');
        Route::get('/staff', [\Modules\Salon\Controllers\SalonOperationsController::class, 'staff'])->middleware('permission:salon.staff.view')->name('staff.index');
        Route::post('/staff', [\Modules\Salon\Controllers\SalonOperationsController::class, 'storeStaff'])->middleware('permission:salon.staff.manage')->name('staff.store');
        Route::get('/services', [\Modules\Salon\Controllers\SalonOperationsController::class, 'services'])->middleware('permission:salon.services.view')->name('services.index');
        Route::post('/services', [\Modules\Salon\Controllers\SalonOperationsController::class, 'storeService'])->middleware('permission:salon.services.manage')->name('services.store');
        Route::get('/pos', [\Modules\Salon\Controllers\SalonOperationsController::class, 'pos'])->middleware('permission:salon.pos.view')->name('pos.index');
        Route::get('/memberships', [\Modules\Salon\Controllers\SalonOperationsController::class, 'memberships'])->middleware('permission:salon.memberships.view')->name('memberships.index');
        Route::post('/membership-plans', [\Modules\Salon\Controllers\SalonOperationsController::class, 'storeMembershipPlan'])->middleware('permission:salon.memberships.manage')->name('membership-plans.store');
        Route::post('/memberships', [\Modules\Salon\Controllers\SalonOperationsController::class, 'storeMembership'])->middleware('permission:salon.memberships.manage')->name('memberships.store');
        Route::post('/memberships/{membership}/points', [\Modules\Salon\Controllers\SalonOperationsController::class, 'awardMembershipPoints'])->middleware('permission:salon.loyalty.manage')->name('memberships.points.store');
        Route::get('/loyalty', [\Modules\Salon\Controllers\SalonOperationsController::class, 'loyalty'])->middleware('permission:salon.loyalty.view')->name('loyalty.index');
        Route::post('/loyalty/{profile}/points', [\Modules\Salon\Controllers\SalonOperationsController::class, 'awardLoyaltyPoints'])->middleware('permission:salon.loyalty.manage')->name('loyalty.points.store');
        Route::post('/gift-cards', [\Modules\Salon\Controllers\SalonOperationsController::class, 'storeGiftCard'])->middleware('permission:salon.loyalty.manage')->name('gift-cards.store');
        Route::get('/consultations', [\Modules\Salon\Controllers\SalonOperationsController::class, 'consultations'])->middleware('permission:salon.consultations.view')->name('consultations.index');
        Route::post('/consultations', [\Modules\Salon\Controllers\SalonOperationsController::class, 'storeConsultation'])->middleware('permission:salon.consultations.manage')->name('consultations.store');
        Route::get('/treatments', [\Modules\Salon\Controllers\SalonOperationsController::class, 'treatments'])->middleware('permission:salon.treatments.view')->name('treatments.index');
        Route::post('/treatments', [\Modules\Salon\Controllers\SalonOperationsController::class, 'storeTreatment'])->middleware('permission:salon.treatments.manage')->name('treatments.store');
        Route::get('/inventory-usage', [\Modules\Salon\Controllers\SalonOperationsController::class, 'inventory'])->middleware('permission:salon.inventory.view')->name('inventory.index');
        Route::post('/inventory-usage', [\Modules\Salon\Controllers\SalonOperationsController::class, 'storeInventoryConsumption'])->middleware('permission:salon.inventory.manage')->name('inventory.consumption.quick-store');
        Route::post('/appointments/{appointment}/product-consumption', [\Modules\Salon\Controllers\SalonOperationsController::class, 'storeConsumption'])->middleware('permission:salon.inventory.manage')->name('inventory.consumption.store');
        Route::get('/commissions', [\Modules\Salon\Controllers\SalonOperationsController::class, 'commissions'])->middleware('permission:salon.commissions.view')->name('commissions.index');
        Route::post('/commissions', [\Modules\Salon\Controllers\SalonOperationsController::class, 'storeCommission'])->middleware('permission:salon.commissions.manage')->name('commissions.store');
        Route::post('/commissions/{commission}/status', [\Modules\Salon\Controllers\SalonOperationsController::class, 'updateCommissionStatus'])->middleware('permission:salon.commissions.manage')->name('commissions.status');
        Route::get('/wellness', [\Modules\Salon\Controllers\SalonOperationsController::class, 'wellness'])->middleware('permission:salon.wellness.view')->name('wellness.index');
        Route::post('/wellness/programs', [\Modules\Salon\Controllers\SalonOperationsController::class, 'storeWellnessProgram'])->middleware('permission:salon.wellness.manage')->name('wellness.programs.store');
        Route::post('/wellness/enrollments', [\Modules\Salon\Controllers\SalonOperationsController::class, 'storeWellnessEnrollment'])->middleware('permission:salon.wellness.manage')->name('wellness.enrollments.store');
        Route::get('/reports', [\Modules\Salon\Controllers\SalonOperationsController::class, 'reports'])->middleware('permission:salon.reports')->name('reports.index');
    });

    Route::prefix('real-estate')->name('real-estate.')->middleware('module.enabled:real-estate')->group(function () {
        Route::get('/', \Modules\RealEstate\Controllers\RealEstateDashboardController::class)->middleware('permission:real-estate.view')->name('dashboard');
        Route::post('/properties', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'storeProperty'])->middleware('permission:real-estate.properties.manage')->name('properties.store');
        Route::post('/units', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'storeUnit'])->middleware('permission:real-estate.units.manage')->name('units.store');
        Route::post('/tenants', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'storeTenant'])->middleware('permission:real-estate.tenants.manage')->name('tenants.store');
        Route::post('/tenants/{tenant}/unit-assignment', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'assignTenantUnit'])->middleware('permission:real-estate.leases.manage')->name('tenants.unit-assignment.store');
        Route::post('/tenants/{tenant}/notice', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'startTenantNotice'])->middleware('permission:real-estate.tenants.offboard')->name('tenants.notice');
        Route::post('/tenants/{tenant}/offboarding', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'progressTenantExit'])->middleware('permission:real-estate.tenants.offboard')->name('tenants.offboarding');
        Route::post('/tenants/{tenant}/archive', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'archiveTenant'])->middleware('permission:real-estate.tenants.offboard')->name('tenants.archive');
        Route::post('/tenants/{tenant}/restore', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'restoreTenant'])->middleware('permission:real-estate.tenants.offboard')->name('tenants.restore');
        Route::post('/tenants/{tenant}/billing-alerts', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'updateTenantBillingAlerts'])->middleware('permission:real-estate.billing.manage')->name('tenants.billing-alerts.update');
        Route::delete('/tenants/{tenant}', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'destroyTenant'])->middleware('permission:real-estate.tenants.delete')->name('tenants.destroy');
        Route::post('/buyers', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'storeBuyer'])->middleware('permission:real-estate.buyers.manage')->name('buyers.store');
        Route::post('/agents', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'storeAgent'])->middleware('permission:real-estate.agents.manage')->name('agents.store');
        Route::delete('/agents/{agent}', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'destroyAgent'])->middleware('permission:real-estate.agents.manage')->name('agents.destroy');
        Route::post('/listings', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'storeListing'])->middleware('permission:real-estate.listings.manage')->name('listings.store');
        Route::post('/listings/{listing}/approve', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'approveListing'])->middleware('permission:real-estate.listings.approve')->name('listings.approve');
        Route::delete('/listings/{listing}', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'destroyListing'])->middleware('permission:real-estate.listings.manage')->name('listings.destroy');
        Route::post('/leases', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'storeLease'])->middleware('permission:real-estate.leases.manage')->name('leases.store');
        Route::post('/leases/{lease}/bill', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'billLease'])->middleware('permission:real-estate.billing.manage')->name('leases.bill');
        Route::post('/payments', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'recordClientPayment'])->middleware('permission:real-estate.billing.manage')->name('payments.store');
        Route::post('/sales', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'storeSale'])->middleware('permission:real-estate.sales.manage')->name('sales.store');
        Route::delete('/sales/{sale}', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'destroySale'])->middleware('permission:real-estate.sales.manage')->name('sales.destroy');
        Route::post('/sales/{sale}/commissions', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'createCommission'])->middleware('permission:real-estate.commissions.manage')->name('sales.commissions.store');
        Route::post('/maintenance', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'storeMaintenance'])->middleware('permission:real-estate.maintenance.manage')->name('maintenance.store');
        Route::post('/service-requests', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'storeServiceRequest'])->middleware('permission:real-estate.service-requests.manage')->name('service-requests.store');
        Route::post('/utility-types', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'storeUtilityType'])->middleware('permission:real-estate.utilities.manage')->name('utility-types.store');
        Route::post('/utility-meters', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'storeUtilityMeter'])->middleware('permission:real-estate.utilities.manage')->name('utility-meters.store');
        Route::post('/utility-readings', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'storeUtilityReading'])->middleware('permission:real-estate.utilities.manage')->name('utility-readings.store');
        Route::post('/utility-bills', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'storeUtilityBill'])->middleware('permission:real-estate.utilities.manage')->name('utility-bills.store');
        Route::post('/amenities', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'storeAmenity'])->middleware('permission:real-estate.amenities.manage')->name('amenities.store');
        Route::post('/amenity-bookings', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'storeAmenityBooking'])->middleware('permission:real-estate.amenities.manage')->name('amenity-bookings.store');
        Route::post('/tenants/{tenant}/statements', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'generateTenantStatement'])->middleware('permission:real-estate.tenant-ledger.manage')->name('tenant-statements.store');
        Route::post('/records/{type}', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'storeSimpleRecord'])->middleware('permission:real-estate.manage')->name('records.store');
        Route::post('/documents', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'storeDocument'])->middleware('permission:real-estate.documents.manage')->name('documents.store');
        Route::get('/documents/{document}/download', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'downloadDocument'])->middleware('permission:real-estate.documents.view')->name('documents.download');
        Route::delete('/documents/{document}', [\Modules\RealEstate\Controllers\RealEstateOperationsController::class, 'destroyDocument'])->middleware('permission:real-estate.documents.manage')->name('documents.destroy');
        Route::get('/reports', [\Modules\RealEstate\Controllers\RealEstateReportController::class, 'index'])->middleware('permission:real-estate.reports')->name('reports.index');
        Route::get('/reports/{type}.csv', [\Modules\RealEstate\Controllers\RealEstateReportController::class, 'csv'])->middleware('permission:real-estate.reports')->name('reports.csv');
    });

    Route::prefix('agriculture')->name('agriculture.')->middleware('module.enabled:agriculture')->group(function () {
        Route::get('/', \Modules\Agriculture\Controllers\AgricultureDashboardController::class)->middleware('permission:agriculture.view')->name('dashboard');
        Route::post('/records/{type}', [\Modules\Agriculture\Controllers\AgricultureOperationsController::class, 'store'])->middleware('permission:agriculture.view')->name('records.store');
        Route::get('/documents/{document}/download', [\Modules\Agriculture\Controllers\AgricultureOperationsController::class, 'downloadDocument'])->middleware('permission:agriculture.view')->name('documents.download');
        Route::delete('/documents/{document}', [\Modules\Agriculture\Controllers\AgricultureOperationsController::class, 'destroyDocument'])->middleware('permission:agriculture.documents.manage')->name('documents.destroy');
        Route::get('/reports', [\Modules\Agriculture\Controllers\AgricultureReportController::class, 'index'])->middleware('permission:agriculture.reports')->name('reports.index');
        Route::get('/reports/{type}.csv', [\Modules\Agriculture\Controllers\AgricultureReportController::class, 'csv'])->whereIn('type', ['farms', 'fields', 'crop-plans', 'activities', 'harvests', 'livestock', 'veterinary', 'inputs', 'equipment', 'equipment-maintenance', 'sales', 'finance', 'compliance'])->middleware('permission:agriculture.reports')->name('reports.csv');
    });

    Route::prefix('construction')->name('construction.')->middleware('module.enabled:construction')->group(function () {
        Route::get('/', \Modules\Construction\Controllers\ConstructionDashboardController::class)->middleware('permission:construction.dashboard')->name('dashboard');
        Route::get('/projects', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'projects'])->middleware('permission:projects.manage')->name('projects');
        Route::post('/projects', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'storeProject'])->middleware('permission:projects.manage')->name('projects.store');
        Route::get('/boqs', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'boqs'])->middleware('permission:boq.view')->name('boqs');
        Route::post('/boqs', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'storeBoq'])->middleware('permission:boq.create')->name('boqs.store');
        Route::post('/boqs/{boq}/items', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'storeBoqItem'])->middleware('permission:boq.update')->name('boqs.items.store');
        Route::post('/boq-items/{item}/rate-components', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'storeRateComponent'])->middleware('permission:boq.update')->name('boq-items.rate-components.store');
        Route::post('/estimates', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'storeEstimate'])->middleware('permission:estimates.manage')->name('estimates.store');
        Route::post('/estimates/{estimate}/to-tender', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'estimateToTender'])->middleware('permission:tenders.manage')->name('estimates.to-tender');
        Route::post('/estimates/{estimate}/to-quotation', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'estimateToQuotation'])->middleware('permission:estimates.manage')->name('estimates.to-quotation');
        Route::get('/tenders', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'tenders'])->middleware('permission:tenders.manage')->name('tenders');
        Route::post('/tenders', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'storeTender'])->middleware('permission:tenders.manage')->name('tenders.store');
        Route::post('/tenders/{tender}/to-project', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'tenderToProject'])->middleware('permission:projects.manage')->name('tenders.to-project');
        Route::get('/site', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'site'])->middleware('permission:sites.manage')->name('site');
        Route::post('/sites', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'storeSite'])->middleware('permission:sites.manage')->name('sites.store');
        Route::post('/site-reports', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'storeDailyReport'])->middleware('permission:site_reports.create')->name('site-reports.store');
        Route::post('/diaries', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'storeDiary'])->middleware('permission:site_reports.create')->name('diaries.store');
        Route::post('/rfis', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'storeRfi'])->middleware('permission:rfi.manage')->name('rfis.store');
        Route::post('/instructions', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'storeInstruction'])->middleware('permission:site_instructions.manage')->name('instructions.store');
        Route::get('/materials', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'materials'])->middleware('permission:materials.manage')->name('materials');
        Route::post('/materials', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'storeMaterial'])->middleware('permission:materials.manage')->name('materials.store');
        Route::post('/material-requests', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'storeMaterialRequest'])->middleware('permission:material_requests.create')->name('material-requests.store');
        Route::post('/material-consumptions', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'storeConsumption'])->middleware('permission:materials.manage')->name('material-consumptions.store');
        Route::get('/contractors', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'contractors'])->middleware('permission:contractors.manage')->name('contractors');
        Route::post('/contractors', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'storeContractor'])->middleware('permission:contractors.manage')->name('contractors.store');
        Route::post('/subcontracts', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'storeSubcontract'])->middleware('permission:subcontracts.manage')->name('subcontracts.store');
        Route::get('/commercial', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'commercial'])->middleware('permission:construction.finance')->name('commercial');
        Route::post('/measurements', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'storeMeasurement'])->middleware('permission:measurements.create')->name('measurements.store');
        Route::post('/certificates', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'storeCertificate'])->middleware('permission:certificates.create')->name('certificates.store');
        Route::post('/certificates/{certificate}/invoice', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'invoiceCertificate'])->middleware('permission:certificates.approve')->name('certificates.invoice');
        Route::post('/variations', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'storeVariation'])->middleware('permission:variations.create')->name('variations.store');
        Route::get('/quality', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'quality'])->middleware('permission:quality.manage')->name('quality');
        Route::post('/inspections', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'storeInspection'])->middleware('permission:quality.manage')->name('inspections.store');
        Route::post('/defects', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'storeDefect'])->middleware('permission:defects.manage')->name('defects.store');
        Route::get('/safety', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'safety'])->middleware('permission:safety.manage')->name('safety');
        Route::post('/incidents', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'storeIncident'])->middleware('permission:safety.manage')->name('incidents.store');
        Route::get('/equipment', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'equipment'])->middleware('permission:construction.view')->name('equipment');
        Route::post('/equipment', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'storeEquipment'])->middleware('permission:construction.view')->name('equipment.store');
        Route::get('/handover', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'handover'])->middleware('permission:handover.manage')->name('handover');
        Route::post('/handovers', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'storeHandover'])->middleware('permission:handover.manage')->name('handovers.store');
        Route::get('/reports', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'reports'])->middleware('permission:construction.reports')->name('reports');
        Route::get('/reports/{type}.csv', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'reportCsv'])->whereIn('type', ['projects', 'boqs', 'materials', 'certificates', 'site-reports'])->middleware('permission:construction.reports')->name('reports.csv');
        Route::get('/mobile', [\Modules\Construction\Controllers\ConstructionOperationsController::class, 'mobile'])->middleware('permission:construction.view')->name('mobile');
    });

    Route::prefix('printing-branding')->name('printing-branding.')->middleware('module.enabled:printing-branding')->group(function () {
        Route::get('/', \Modules\PrintingBranding\Controllers\PrintingDashboardController::class)->middleware('permission:printing.dashboard')->name('dashboard');
        Route::get('/estimating', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'estimates'])->middleware('permission:estimates.view')->name('estimates');
        Route::post('/estimating', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'storeEstimate'])->middleware('permission:estimates.create')->name('estimates.store');
        Route::post('/estimating/{estimate}/convert', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'convertEstimate'])->middleware('permission:estimates.approve')->name('estimates.convert');
        Route::get('/jobs', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'jobs'])->middleware('permission:production_jobs.view')->name('jobs');
        Route::post('/clients', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'storeClient'])->middleware('permission:production_jobs.create')->name('clients.store');
        Route::post('/jobs', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'storeJob'])->middleware('permission:production_jobs.create')->name('jobs.store');
        Route::post('/jobs/from-quotation/{quotation}', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'jobFromQuotation'])->middleware('permission:production_jobs.create')->name('jobs.from-quotation');
        Route::post('/jobs/{job}/status', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'updateJobStatus'])->middleware('permission:production_jobs.update')->name('jobs.status');
        Route::post('/jobs/{job}/invoice', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'invoiceJob'])->middleware('permission:job_costing.view')->name('jobs.invoice');
        Route::post('/jobs/{job}/costing', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'calculateCost'])->middleware('permission:job_costing.manage')->name('jobs.costing');
        Route::post('/jobs/{job}/reorder', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'reorder'])->middleware('permission:production_jobs.create')->name('jobs.reorder');
        Route::get('/jobs/{job}/mobile', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'mobileJob'])->middleware('permission:production.execute')->name('jobs.mobile');
        Route::get('/production-board', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'board'])->middleware('permission:production_jobs.view')->name('board');
        Route::get('/job-tickets', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'tickets'])->middleware('permission:production_jobs.view')->name('tickets');
        Route::get('/job-tickets/{job}', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'ticket'])->middleware('permission:production_jobs.view')->name('tickets.show');
        Route::get('/schedule', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'schedule'])->middleware('permission:production.schedule')->name('schedule');
        Route::post('/schedule', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'storeSchedule'])->middleware('permission:production.schedule')->name('schedule.store');
        Route::get('/artwork', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'artwork'])->middleware('permission:artwork.view')->name('artwork');
        Route::post('/artwork', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'storeArtwork'])->middleware('permission:artwork.manage')->name('artwork.store');
        Route::post('/artwork/{artwork}/proof', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'sendProof'])->middleware('permission:artwork.manage')->name('artwork.proof.send');
        Route::post('/proofs/{approval}/decision', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'approveProof'])->middleware('permission:artwork.approve')->name('proofs.decision');
        Route::get('/production', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'production'])->middleware('permission:production.execute')->name('production');
        Route::post('/production/stages', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'storeOperation'])->middleware('permission:production.execute')->name('operations.store');
        Route::post('/production/stages/{operation}', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'updateOperation'])->middleware('permission:production.execute')->name('operations.update');
        Route::get('/materials', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'materials'])->middleware('permission:inventory.view')->name('materials');
        Route::post('/materials', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'storeMaterial'])->middleware('permission:printing_settings.manage')->name('materials.store');
        Route::post('/materials/reservations/{reservation}/consume', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'consumeMaterial'])->middleware('permission:inventory.consume')->name('materials.consume');
        Route::get('/machines', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'machines'])->middleware('permission:machines.manage')->name('machines');
        Route::post('/machines', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'storeMachine'])->middleware('permission:machines.manage')->name('machines.store');
        Route::post('/machines/{machine}/maintenance', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'storeMaintenance'])->middleware('permission:machines.manage')->name('machines.maintenance.store');
        Route::match(['get', 'post'], '/quality-control', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'quality'])->middleware('permission:production.quality_control')->name('quality');
        Route::match(['get', 'post'], '/waste', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'waste'])->middleware('permission:production.execute')->name('waste');
        Route::get('/outsourcing', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'outsourcing'])->middleware('permission:production_jobs.view')->name('outsourcing');
        Route::post('/outsourcing', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'storeOutsourcing'])->middleware('permission:production_jobs.update')->name('outsourcing.store');
        Route::get('/dispatch', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'dispatch'])->middleware('permission:dispatch.manage')->name('dispatch');
        Route::post('/dispatch', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'storeDispatch'])->middleware('permission:dispatch.manage')->name('dispatch.store');
        Route::post('/dispatch/{dispatch}/delivery-note', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'deliveryNote'])->middleware('permission:dispatch.manage')->name('delivery-notes.store');
        Route::get('/job-costing', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'costing'])->middleware('permission:job_costing.view')->name('costing');
        Route::get('/reports', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'reports'])->middleware('permission:printing_reports.view')->name('reports');
        Route::get('/reports/{type}.csv', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'reportExport'])->whereIn('type', ['jobs', 'estimates', 'waste', 'daily-production'])->middleware('permission:printing_reports.view')->name('reports.csv');
        Route::get('/settings', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'settings'])->middleware('permission:printing_settings.manage')->name('settings');
        Route::post('/settings/templates', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'storeTemplate'])->middleware('permission:printing_settings.manage')->name('settings.templates.store');
        Route::post('/settings/print-methods', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'storePrintMethod'])->middleware('permission:printing_settings.manage')->name('settings.print-methods.store');
        Route::post('/settings/finishing', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'storeFinishingOption'])->middleware('permission:printing_settings.manage')->name('settings.finishing.store');
        Route::post('/settings/pricing-rules', [\Modules\PrintingBranding\Controllers\PrintingOperationsController::class, 'storePricingRule'])->middleware('permission:printing_settings.manage')->name('settings.pricing-rules.store');
    });

    Route::prefix('automotive')->name('automotive.')->middleware('module.enabled:automotive')->group(function () {
        Route::get('/', \Modules\Automotive\Controllers\AutomotiveDashboardController::class)->middleware('permission:automotive.dashboard')->name('dashboard');
        Route::get('/vehicles', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'vehicles'])->middleware('permission:vehicles.view')->name('vehicles');
        Route::post('/vehicles', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'storeVehicle'])->middleware('permission:vehicles.create')->name('vehicles.store');
        Route::get('/bookings', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'bookings'])->middleware('permission:bookings.manage')->name('bookings');
        Route::post('/bookings', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'storeBooking'])->middleware('permission:bookings.manage')->name('bookings.store');
        Route::post('/check-ins', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'checkIn'])->middleware('permission:checkin.manage')->name('check-ins.store');
        Route::get('/job-cards', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'jobCards'])->middleware('permission:job_cards.view')->name('job-cards');
        Route::post('/job-cards', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'storeJobCard'])->middleware('permission:job_cards.create')->name('job-cards.store');
        Route::post('/job-cards/{job}/status', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'updateJobStatus'])->middleware('permission:job_cards.update')->name('job-cards.status');
        Route::post('/job-cards/{job}/labour-tasks', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'storeLabourTask'])->middleware('permission:job_cards.update')->name('job-cards.labour-tasks.store');
        Route::post('/job-cards/{job}/invoice', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'invoiceJob'])->middleware('permission:automotive.finance')->name('job-cards.invoice');
        Route::get('/estimates', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'estimates'])->middleware('permission:estimates.manage')->name('estimates');
        Route::post('/estimates', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'storeEstimate'])->middleware('permission:estimates.manage')->name('estimates.store');
        Route::post('/estimates/{estimate}/approve', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'approveEstimate'])->middleware('permission:estimates.approve')->name('estimates.approve');
        Route::post('/estimates/{estimate}/quotation', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'estimateToQuotation'])->middleware('permission:estimates.approve')->name('estimates.quotation');
        Route::get('/workshop', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'workshop'])->middleware('permission:workshop.manage')->name('workshop');
        Route::post('/workshop/bays', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'storeBay'])->middleware('permission:workshop.manage')->name('bays.store');
        Route::post('/job-cards/{job}/diagnostics', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'storeDiagnostic'])->middleware('permission:workshop.manage')->name('diagnostics.store');
        Route::get('/labour-operations', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'labourOperations'])->middleware('permission:technicians.manage')->name('labour-operations');
        Route::post('/labour-operations', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'storeLabourOperation'])->middleware('permission:technicians.manage')->name('labour-operations.store');
        Route::get('/technicians', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'technicians'])->middleware('permission:technicians.manage')->name('technicians');
        Route::get('/inspections', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'inspections'])->middleware('permission:inspections.create')->name('inspections');
        Route::post('/inspections', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'storeInspection'])->middleware('permission:inspections.create')->name('inspections.store');
        Route::post('/inspections/{inspection}/estimate', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'inspectionToEstimate'])->middleware('permission:estimates.manage')->name('inspections.estimate');
        Route::get('/parts', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'parts'])->middleware('permission:parts.view')->name('parts');
        Route::post('/parts', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'storePart'])->middleware('permission:automotive.inventory')->name('parts.store');
        Route::post('/job-cards/{job}/part-requests', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'storePartRequest'])->middleware('permission:parts.issue')->name('part-requests.store');
        Route::post('/part-request-items/{item}/issue', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'issuePart'])->middleware('permission:parts.issue')->name('parts.issue');
        Route::post('/part-request-items/{item}/return', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'returnPart'])->middleware('permission:parts.return')->name('parts.return');
        Route::get('/quality', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'quality'])->middleware('permission:quality_control.manage')->name('quality');
        Route::post('/job-cards/{job}/quality', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'storeQuality'])->middleware('permission:quality_control.manage')->name('quality.store');
        Route::get('/road-tests', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'roadTests'])->middleware('permission:quality_control.manage')->name('road-tests');
        Route::post('/job-cards/{job}/road-tests', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'storeRoadTest'])->middleware('permission:quality_control.manage')->name('road-tests.store');
        Route::get('/vehicle-release', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'vehicleRelease'])->middleware('permission:job_cards.complete')->name('vehicle-release');
        Route::post('/job-cards/{job}/release', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'releaseVehicle'])->middleware('permission:job_cards.complete')->name('releases.store');
        Route::get('/warranty', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'warranty'])->middleware('permission:warranty.manage')->name('warranty');
        Route::post('/warranties', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'storeWarranty'])->middleware('permission:warranty.manage')->name('warranties.store');
        Route::post('/job-cards/{job}/comebacks', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'storeComeback'])->middleware('permission:warranty.manage')->name('comebacks.store');
        Route::get('/fleet', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'fleet'])->middleware('permission:fleet.manage')->name('fleet');
        Route::post('/fleet', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'storeFleet'])->middleware('permission:fleet.manage')->name('fleet.store');
        Route::get('/job-costing', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'jobCosting'])->middleware('permission:automotive.finance')->name('job-costing');
        Route::post('/job-cards/{job}/costing', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'costJob'])->middleware('permission:automotive.finance')->name('job-cards.costing');
        Route::get('/service-reminders', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'serviceReminders'])->middleware('permission:vehicles.update')->name('service-reminders');
        Route::post('/service-reminders', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'storeServiceReminder'])->middleware('permission:vehicles.update')->name('service-reminders.store');
        Route::get('/vehicle-sales', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'sales'])->middleware('permission:vehicle_sales.manage')->name('sales');
        Route::post('/vehicle-sales', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'storeVehicleSale'])->middleware('permission:vehicle_sales.manage')->name('sales.store');
        Route::get('/specialty/{type}', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'specialty'])->whereIn('type', ['tyres', 'body-paint', 'insurance-repairs'])->middleware('permission:automotive.view')->name('specialty');
        Route::post('/specialty/{type}', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'storeSpecialty'])->whereIn('type', ['tyres', 'body-paint', 'insurance-repairs'])->middleware('permission:automotive.view')->name('specialty.store');
        Route::get('/customer-service', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'customerService'])->middleware('permission:automotive.view')->name('customer-service');
        Route::post('/feedback', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'storeFeedback'])->middleware('permission:automotive.view')->name('feedback.store');
        Route::post('/complaints', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'storeComplaint'])->middleware('permission:automotive.view')->name('complaints.store');
        Route::get('/reports', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'reports'])->middleware('permission:automotive.reports')->name('reports');
        Route::get('/reports/{type}.csv', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'reportCsv'])->whereIn('type', ['vehicles', 'job-cards', 'parts', 'estimates', 'job-costing', 'service-reminders', 'specialty'])->middleware('permission:automotive.reports')->name('reports.csv');
        Route::get('/mobile', [\Modules\Automotive\Controllers\AutomotiveOperationsController::class, 'mobile'])->middleware('permission:job_cards.update')->name('mobile');
    });

    Route::resource('quotations', QuotationController::class);
    Route::get('/quotations/{quotation}/download', [QuotationController::class, 'download'])->name('quotations.download');
    Route::get('/quotations/{quotation}/email', [QuotationController::class, 'emailForm'])->name('quotations.email');
    Route::post('/quotations/{quotation}/email', [QuotationController::class, 'sendEmail'])->name('quotations.email.send');
    Route::post('/quotations/{quotation}/convert', [QuotationController::class, 'convert'])->name('quotations.convert');

    Route::resource('invoices', InvoiceController::class);
    Route::post('/invoices/advanced', [InvoiceController::class, 'storeAdvancedInvoice'])->name('invoices.advanced.store');
    Route::get('/invoices/{invoice}/download', [InvoiceController::class, 'download'])->name('invoices.download');
    Route::get('/invoices/{invoice}/email', [InvoiceController::class, 'emailForm'])->name('invoices.email');
    Route::post('/invoices/{invoice}/email', [InvoiceController::class, 'sendEmail'])->name('invoices.email.send');
    Route::post('/invoices/{invoice}/payments', [InvoiceController::class, 'recordPayment'])->name('invoices.payments.store');
    Route::post('/invoices/{invoice}/part-payments', [InvoiceController::class, 'storePartPayment'])->name('invoices.part-payments.store');

    Route::get('/receipts', [ReceiptController::class, 'index'])->name('receipts.index');
    Route::get('/receipts/{receipt}', [ReceiptController::class, 'show'])->name('receipts.show');
    Route::get('/receipts/{receipt}/download', [ReceiptController::class, 'download'])->name('receipts.download');
    Route::get('/receipts/{receipt}/email', [ReceiptController::class, 'emailForm'])->name('receipts.email');
    Route::post('/receipts/{receipt}/email', [ReceiptController::class, 'sendEmail'])->name('receipts.email.send');
    });
});
