<?php
namespace Tests\Feature;
use App\Models\Business;use App\Models\Invoice;use App\Models\JournalEntry;use App\Models\Payment;use App\Models\User;use App\Services\FinanceService;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Validation\ValidationException;use Tests\TestCase;
class FinanceTest extends TestCase {use RefreshDatabase;private User $user;private int $clientId;
 protected function setUp():void{parent::setUp();$business=Business::where('slug','bama')->firstOrFail();$this->user=User::factory()->create(['role'=>'admin','is_active'=>true]);$this->actingAs($this->user)->withSession(['active_business_id'=>$business->id]);$this->clientId=\DB::table('clients')->insertGetId(['business_id'=>$business->id,'name'=>'Ledger Client','created_at'=>now(),'updated_at'=>now()]);}
 public function test_invoice_and_payment_post_balanced_double_entries():void{$invoice=Invoice::create(['client_id'=>$this->clientId,'invoice_number'=>'INV-GL-1','invoice_date'=>now(),'subtotal'=>1000,'tax_total'=>160,'total'=>1160,'balance'=>1160]);$journal=JournalEntry::where('source_type',Invoice::class)->firstOrFail();$this->assertEquals(1160,$journal->total_debit);$this->assertEquals($journal->total_debit,$journal->total_credit);$payment=Payment::create(['invoice_id'=>$invoice->id,'amount'=>500,'payment_date'=>now()]);$paymentJournal=JournalEntry::where('source_type',Payment::class)->firstOrFail();$this->assertEquals(500,$paymentJournal->total_debit);$this->assertEquals(500,$paymentJournal->total_credit);}
 public function test_unbalanced_journal_is_rejected():void{$service=app(FinanceService::class);$service->seedAccounts();$this->expectException(ValidationException::class);$service->post(['entry_date'=>now(),'description'=>'Bad'],[['finance_account_id'=>$service->account('1000')->id,'debit'=>100,'credit'=>0],['finance_account_id'=>$service->account('3000')->id,'debit'=>0,'credit'=>90]]);}
 public function test_reversal_preserves_original_and_swaps_debits_and_credits():void{$s=app(FinanceService::class);$entry=$s->post(['entry_date'=>now(),'description'=>'Capital'],[['finance_account_id'=>$s->account('1000')->id,'debit'=>100,'credit'=>0],['finance_account_id'=>$s->account('3000')->id,'debit'=>0,'credit'=>100]]);$reversal=$s->reverse($entry->load('lines'),'Correction');$this->assertSame('Reversed',$entry->fresh()->status);$this->assertEquals(100,$reversal->total_debit);$this->assertDatabaseCount('journal_entries',2);}
 public function test_finance_manager_can_unreverse_and_viewer_cannot():void{$s=app(FinanceService::class);$entry=$s->post(['entry_date'=>now(),'description'=>'Restore me'],[['finance_account_id'=>$s->account('1000')->id,'debit'=>100,'credit'=>0],['finance_account_id'=>$s->account('3000')->id,'debit'=>0,'credit'=>100]]);$reversal=$s->reverse($entry->load('lines'),'Mistake');$iam=app(\App\Services\IamService::class);$iam->bootstrap();$business=Business::where('slug','bama')->firstOrFail();$financeManager=\App\Models\IamRole::where('business_id',$business->id)->where('slug','finance-manager')->firstOrFail();\DB::table('business_user')->where('business_id',$business->id)->where('user_id',$this->user->id)->update(['iam_role_id'=>$financeManager->id]);$this->post(route('finance.journals.unreverse',$entry),['reason'=>'Entry was valid'])->assertRedirect();$this->assertSame('Posted',$entry->fresh()->status);$this->assertSame('Reversed',$reversal->fresh()->status);$viewer=User::factory()->create(['role'=>'admin','is_active'=>true]);$viewerRole=\App\Models\IamRole::where('business_id',$business->id)->where('slug','viewer')->firstOrFail();\DB::table('business_user')->insert(['business_id'=>$business->id,'user_id'=>$viewer->id,'iam_role_id'=>$viewerRole->id,'status'=>'Active','created_at'=>now(),'updated_at'=>now()]);$this->actingAs($viewer)->withSession(['active_business_id'=>$business->id])->post(route('finance.journals.unreverse',$entry),['reason'=>'Not allowed'])->assertForbidden();}
 public function test_closed_period_blocks_posting():void{$business=Business::where('slug','bama')->first();\DB::table('finance_periods')->insert(['business_id'=>$business->id,'name'=>'Locked','starts_at'=>'2026-01-01','ends_at'=>'2026-12-31','status'=>'Closed','created_at'=>now(),'updated_at'=>now()]);$s=app(FinanceService::class);$this->expectException(ValidationException::class);$s->post(['entry_date'=>'2026-05-01','description'=>'Blocked'],[['finance_account_id'=>$s->account('1000')->id,'debit'=>10,'credit'=>0],['finance_account_id'=>$s->account('3000')->id,'debit'=>0,'credit'=>10]]);}
 public function test_finance_dashboard_and_reports_render():void{$this->get(route('finance.index'))->assertOk()->assertSee('General Ledger')->assertSee('Trial Balance')->assertSee('Receivable aging')->assertSee('Industry Finance')->assertSee('Cash movement this month')->assertSee('Control cockpit');}
 public function test_finance_cockpit_groups_industry_revenue_and_controls():void{Invoice::create(['client_id'=>$this->clientId,'invoice_number'=>'INV-PRINT-1','industry_module'=>'printing_branding','industry_reference'=>'JOB-2026-00001','invoice_date'=>now(),'due_date'=>now()->subDay(),'subtotal'=>2000,'tax_total'=>0,'total'=>2000,'balance'=>2000,'payment_status'=>'unpaid']);$this->get(route('finance.index'))->assertOk()->assertSee('Printing &amp; Branding',false)->assertSee('JOB-2026-00001')->assertSee('Invoice pipeline')->assertSee('Overdue receivables')->assertSee('Working Capital');}
 public function test_chart_of_accounts_supports_enterprise_categories_and_safe_deactivation():void{$iam=app(\App\Services\IamService::class);$iam->bootstrap();$business=Business::where('slug','bama')->firstOrFail();$financeManager=\App\Models\IamRole::where('business_id',$business->id)->where('slug','finance-manager')->firstOrFail();\DB::table('business_user')->where('business_id',$business->id)->where('user_id',$this->user->id)->update(['iam_role_id'=>$financeManager->id]);$this->post(route('finance.accounts.store'),['code'=>'5700','name'=>'Installation Materials','type'=>'Cost of Sales','subtype'=>'Direct Cost','description'=>'Direct project material costs','tax_treatment'=>'VAT Input','opening_balance'=>1250])->assertRedirect();$account=\App\Models\FinanceAccount::where('code','5700')->firstOrFail();$this->assertSame('Cost of Sales',$account->type);$this->assertSame('VAT Input',$account->tax_treatment);$this->put(route('finance.accounts.update',$account),['code'=>'5700','name'=>'Installation Materials Updated','type'=>'Cost of Sales','subtype'=>'Direct Cost','description'=>'Updated','tax_treatment'=>'VAT Input','opening_balance'=>1250])->assertRedirect();$this->post(route('finance.accounts.deactivate',$account))->assertRedirect();$this->assertFalse($account->fresh()->is_active);}
 public function test_chart_of_accounts_management_requires_permission():void{$iam=app(\App\Services\IamService::class);$iam->bootstrap();$business=Business::where('slug','bama')->firstOrFail();$viewer=User::factory()->create(['role'=>'admin','is_active'=>true]);$viewerRole=\App\Models\IamRole::where('business_id',$business->id)->where('slug','viewer')->firstOrFail();\DB::table('business_user')->insert(['business_id'=>$business->id,'user_id'=>$viewer->id,'iam_role_id'=>$viewerRole->id,'status'=>'Active','created_at'=>now(),'updated_at'=>now()]);$this->actingAs($viewer)->withSession(['active_business_id'=>$business->id])->post(route('finance.accounts.store'),['code'=>'9999','name'=>'Blocked','type'=>'Expense'])->assertForbidden();}
}
