@extends('layouts.app')
@section('title','Real Estate Reports')
@section('content')
@php($money=fn($v)=>'KES '.number_format((float)$v,2))
<div class="d-flex justify-content-between mb-4"><div><h1 class="h5 mb-1">Real Estate Reports</h1><p class="text-muted mb-0">Portfolio, property, unit, lease, sales, commission, maintenance, valuation, land, and ETIMS-ready billing reports.</p></div><a class="btn btn-outline-dark" href="{{ route('real-estate.dashboard') }}">Dashboard</a></div>
<div class="row g-3 mb-4">@foreach([['Portfolio Value',$money($metrics['portfolio_value'])],['Occupancy',$metrics['occupancy_rate'].'%'],['Outstanding Rent',$money($metrics['outstanding_rent'])],['Sales Pipeline',$money($metrics['sales_pipeline'])]] as [$label,$value])<div class="col-md-3"><div class="card p-3"><span class="text-muted small">{{ $label }}</span><strong>{{ $value }}</strong></div></div>@endforeach</div>
<div class="card p-3 mb-3"><h2 class="h6">Exports</h2><div class="d-flex flex-wrap gap-2">@foreach(['properties','units','leases','sales','tenant-payments','tenant-ledger','utility-billing','lease-billing','outstanding-balances','move-outs','archived-tenants','tenant-history','vacancy'] as $type)<a class="btn btn-sm btn-outline-warning" href="{{ route('real-estate.reports.csv',$type) }}"><i class="bi bi-download"></i> {{ str($type)->headline() }} CSV</a>@endforeach</div></div>
<div class="row g-3">
<div class="col-lg-6"><div class="card p-3"><h2 class="h6">Lease Report</h2><table class="table"><thead><tr><th>Lease</th><th>Tenant</th><th>Rent</th><th>Status</th></tr></thead><tbody>@foreach($leases as $lease)<tr><td>{{ $lease->lease_number }}</td><td>{{ $lease->tenant?->client?->name }}</td><td>{{ $money($lease->rent_amount) }}</td><td>{{ $lease->status }}</td></tr>@endforeach</tbody></table></div></div>
<div class="col-lg-6"><div class="card p-3"><h2 class="h6">Commission Report</h2><table class="table"><thead><tr><th>Commission</th><th>Agent</th><th>Earned</th><th>Status</th></tr></thead><tbody>@foreach($commissions as $commission)<tr><td>{{ $commission->commission_number }}</td><td>{{ $commission->agent?->name }}</td><td>{{ $money($commission->earned_amount) }}</td><td>{{ $commission->status }}</td></tr>@endforeach</tbody></table></div></div>
<div class="col-lg-6"><div class="card p-3"><h2 class="h6">Utility Billing Report</h2><table class="table"><thead><tr><th>Bill</th><th>Tenant</th><th>Utility</th><th>Amount</th></tr></thead><tbody>@foreach($utilityBills as $bill)<tr><td>{{ $bill->bill_number }}</td><td>{{ $bill->tenant?->client?->name }}</td><td>{{ $bill->utilityType?->name }}</td><td>{{ $money($bill->amount) }}</td></tr>@endforeach</tbody></table></div></div>
<div class="col-lg-6"><div class="card p-3"><h2 class="h6">Tenant Statement Report</h2><table class="table"><thead><tr><th>Statement</th><th>Tenant</th><th>Charges</th><th>Balance</th></tr></thead><tbody>@foreach($statements as $statement)<tr><td>{{ $statement->statement_number }}</td><td>{{ $statement->tenant?->client?->name }}</td><td>{{ $money($statement->current_charges) }}</td><td>{{ $money($statement->outstanding_balance) }}</td></tr>@endforeach</tbody></table></div></div>
<div class="col-12"><div class="card p-3"><h2 class="h6">Tenant Ledger Report</h2><table class="table"><thead><tr><th>Date</th><th>Tenant</th><th>Type</th><th>Debit</th><th>Credit</th><th>Balance</th></tr></thead><tbody>@foreach($ledgerRows as $entry)<tr><td>{{ $entry->entry_date?->toDateString() }}</td><td>{{ $entry->tenant?->client?->name }}</td><td>{{ $entry->entry_type }}</td><td>{{ $money($entry->debit) }}</td><td>{{ $money($entry->credit) }}</td><td>{{ $money($entry->running_balance) }}</td></tr>@endforeach</tbody></table></div></div>
<div class="col-12"><div class="card p-3"><h2 class="h6">Maintenance Report</h2><table class="table"><thead><tr><th>Request</th><th>Property</th><th>Unit</th><th>Status</th><th>Cost</th></tr></thead><tbody>@foreach($maintenance as $request)<tr><td>{{ $request->request_number }}</td><td>{{ $request->property?->property_name }}</td><td>{{ $request->unit?->unit_number }}</td><td>{{ $request->status }}</td><td>{{ $money($request->actual_cost) }}</td></tr>@endforeach</tbody></table></div></div>
</div>
@endsection
