@extends('layouts.app')
@section('title', 'Construction - '.$title)

@section('content')
<style>
    .ops-shell{display:grid;gap:16px}
    .ops-head{display:flex;justify-content:space-between;gap:1rem;align-items:flex-start}
    .ops-card{background:#fff;border:1px solid #e5e7eb;border-radius:10px;padding:18px;box-shadow:0 10px 28px rgba(15,23,42,.05)}
    .ops-kicker{color:#007a3b;font-size:.72rem;font-weight:800;text-transform:uppercase;letter-spacing:.08em}
    .ops-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}
    .ops-two{display:grid;grid-template-columns:1fr 1fr;gap:14px}
    .ops-pill{display:inline-flex;border-radius:999px;padding:.22rem .58rem;background:#e9fff2;color:#007a3b;font-size:.72rem;font-weight:800}
    @media(max-width:1100px){.ops-grid,.ops-two{grid-template-columns:1fr 1fr}}
    @media(max-width:720px){.ops-head{display:block}.ops-grid,.ops-two{grid-template-columns:1fr}}
</style>
<div class="ops-shell">
    <div class="ops-head">
        <div>
            <div class="ops-kicker">Construction</div>
            <h1 class="mb-1">{{ $title }}</h1>
            <p class="text-muted mb-0">{{ $description }}</p>
        </div>
        <a class="btn btn-dark" href="{{ route('construction.dashboard') }}">Dashboard</a>
    </div>

    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif

    @if($section === 'projects')
        <div class="ops-card"><h2 class="h5">New construction project</h2><form method="post" action="{{ route('construction.projects.store') }}" class="row g-2">@csrf
            <div class="col-md-3"><select class="form-select" name="client_id"><option value="">Client</option>@foreach($clients as $client)<option value="{{ $client->id }}">{{ $client->name }}</option>@endforeach</select></div>
            <div class="col-md-3"><input class="form-control" name="project_name" placeholder="Project name" required></div>
            <div class="col-md-2"><input class="form-control" name="contract_type" placeholder="Contract type"></div>
            <div class="col-md-2"><input class="form-control" type="number" step="0.01" name="contract_value" placeholder="Contract value"></div>
            <div class="col-md-2"><select class="form-select" name="status">@foreach(['Tendering','Awarded','Mobilization','Active','Suspended','Near Completion','Practical Completion','Defects Liability','Final Completion','Closed','Cancelled'] as $status)<option>{{ $status }}</option>@endforeach</select></div>
            <div class="col-md-3"><input class="form-control" type="date" name="start_date"></div>
            <div class="col-md-3"><input class="form-control" type="date" name="planned_completion"></div>
            <div class="col-md-3"><input class="form-control" name="location" placeholder="Location"></div>
            <div class="col-md-3"><input class="form-control" type="number" step="0.01" name="retention_percentage" placeholder="Retention %"></div>
            <div class="col-12"><button class="btn btn-success">Create Project</button></div>
        </form></div>
        <div class="ops-card"><h2 class="h5">Projects</h2><div class="table-responsive"><table class="table"><thead><tr><th>No.</th><th>Project</th><th>Client</th><th>Status</th><th>Contract</th><th>Due</th></tr></thead><tbody>@forelse($profiles as $profile)<tr><td>{{ $profile->project_number }}</td><td>{{ $profile->project?->project_name }}</td><td>{{ $profile->client?->name }}</td><td><span class="ops-pill">{{ $profile->status }}</span></td><td>{{ number_format((float)$profile->contract_value,2) }}</td><td>{{ $profile->planned_completion?->format('d M Y') }}</td></tr>@empty<tr><td colspan="6" class="text-muted">No projects yet.</td></tr>@endforelse</tbody></table></div>{{ $profiles->links() }}</div>
    @endif

    @if($section === 'boqs')
        <div class="ops-two">
            <div class="ops-card"><h2 class="h5">Create BOQ</h2><form method="post" action="{{ route('construction.boqs.store') }}" class="row g-2">@csrf
                <select class="form-select" name="project_id"><option value="">Project</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->project_name }}</option>@endforeach</select>
                <select class="form-select" name="client_id"><option value="">Client</option>@foreach($clients as $client)<option value="{{ $client->id }}">{{ $client->name }}</option>@endforeach</select>
                <input class="form-control" name="title" placeholder="BOQ title" required>
                <select class="form-select" name="type"><option>Tender BOQ</option><option>Client BOQ</option><option>Internal Cost BOQ</option></select>
                <div class="row g-2"><div class="col"><input class="form-control" type="number" step="0.01" name="preliminaries" placeholder="Preliminaries"></div><div class="col"><input class="form-control" type="number" step="0.01" name="contingency" placeholder="Contingency"></div><div class="col"><input class="form-control" type="number" step="0.01" name="tax" placeholder="Tax"></div></div>
                <button class="btn btn-success">Create BOQ</button>
            </form></div>
            <div class="ops-card"><h2 class="h5">Create Estimate</h2><form method="post" action="{{ route('construction.estimates.store') }}" class="row g-2">@csrf
                <select class="form-select" name="client_id"><option value="">Client</option>@foreach($clients as $client)<option value="{{ $client->id }}">{{ $client->name }}</option>@endforeach</select>
                <select class="form-select" name="project_id"><option value="">Project</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->project_name }}</option>@endforeach</select>
                <select class="form-select" name="boq_id"><option value="">BOQ</option>@foreach($boqs as $boq)<option value="{{ $boq->id }}">{{ $boq->boq_number }} - {{ $boq->title }}</option>@endforeach</select>
                <input class="form-control" name="title" placeholder="Estimate title" required>
                <div class="row g-2"><div class="col"><input class="form-control" type="number" step="0.01" name="direct_cost" placeholder="Direct cost" required></div><div class="col"><input class="form-control" type="number" step="0.01" name="overhead_percentage" placeholder="Overhead %"></div><div class="col"><input class="form-control" type="number" step="0.01" name="profit_percentage" placeholder="Profit %"></div></div>
                <button class="btn btn-success">Create Estimate</button>
            </form></div>
        </div>
        <div class="ops-card"><h2 class="h5">BOQs</h2><div class="table-responsive"><table class="table"><thead><tr><th>BOQ</th><th>Title</th><th>Project</th><th>Total</th><th>Add item</th></tr></thead><tbody>@forelse($boqs as $boq)<tr><td>{{ $boq->boq_number }}</td><td>{{ $boq->title }}</td><td>{{ $boq->project?->project_name }}</td><td>{{ number_format((float)$boq->grand_total,2) }}</td><td><form method="post" action="{{ route('construction.boqs.items.store',$boq) }}" class="row g-1">@csrf<div class="col"><input class="form-control form-control-sm" name="description" placeholder="Item description" required></div><div class="col"><input class="form-control form-control-sm" name="unit" value="Item"></div><div class="col"><input class="form-control form-control-sm" type="number" step="0.001" name="quantity" placeholder="Qty" required></div><div class="col"><input class="form-control form-control-sm" type="number" step="0.01" name="unit_rate" placeholder="Rate"></div><div class="col-auto"><button class="btn btn-sm btn-success">Add</button></div></form></td></tr>@empty<tr><td colspan="5" class="text-muted">No BOQs yet.</td></tr>@endforelse</tbody></table></div>{{ $boqs->links() }}</div>
        <div class="ops-card"><h2 class="h5">Estimates</h2><div class="table-responsive"><table class="table"><thead><tr><th>No.</th><th>Title</th><th>Selling Price</th><th>Status</th><th>Convert</th></tr></thead><tbody>@forelse($estimates as $estimate)<tr><td>{{ $estimate->estimate_number }}</td><td>{{ $estimate->title }}</td><td>{{ number_format((float)$estimate->selling_price,2) }}</td><td>{{ $estimate->status }}</td><td><form method="post" action="{{ route('construction.estimates.to-tender',$estimate) }}" class="d-inline">@csrf<button class="btn btn-sm btn-outline-success">Tender</button></form> <form method="post" action="{{ route('construction.estimates.to-quotation',$estimate) }}" class="d-inline">@csrf<button class="btn btn-sm btn-outline-dark">Quotation</button></form></td></tr>@empty<tr><td colspan="5" class="text-muted">No estimates yet.</td></tr>@endforelse</tbody></table></div></div>
    @endif

    @if($section === 'tenders')
        <div class="ops-card"><h2 class="h5">Create tender</h2><form method="post" action="{{ route('construction.tenders.store') }}" class="row g-2">@csrf
            <div class="col-md-3"><select class="form-select" name="client_id"><option value="">Client</option>@foreach($clients as $client)<option value="{{ $client->id }}">{{ $client->name }}</option>@endforeach</select></div>
            <div class="col-md-3"><input class="form-control" name="name" placeholder="Tender name" required></div>
            <div class="col-md-2"><input class="form-control" type="number" step="0.01" name="tender_value" placeholder="Value"></div>
            <div class="col-md-2"><input class="form-control" type="date" name="closing_date"></div>
            <div class="col-md-2"><select class="form-select" name="status"><option>Identified</option><option>Reviewing</option><option>Preparing</option><option>Submitted</option><option>Awarded</option><option>Lost</option></select></div>
            <div class="col-12"><textarea class="form-control" name="requirements" placeholder="Tender requirements"></textarea></div>
            <div class="col-12"><button class="btn btn-success">Create Tender</button></div>
        </form></div>
        <div class="ops-card"><h2 class="h5">Tender register</h2><div class="table-responsive"><table class="table"><thead><tr><th>Tender</th><th>Name</th><th>Client</th><th>Closing</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($tenders as $tender)<tr><td>{{ $tender->tender_number }}</td><td>{{ $tender->name }}</td><td>{{ $tender->client?->name }}</td><td>{{ $tender->closing_date?->format('d M Y') }}</td><td><span class="ops-pill">{{ $tender->status }}</span></td><td><form method="post" action="{{ route('construction.tenders.to-project',$tender) }}">@csrf<button class="btn btn-sm btn-success">Award to Project</button></form></td></tr>@empty<tr><td colspan="6" class="text-muted">No tenders yet.</td></tr>@endforelse</tbody></table></div>{{ $tenders->links() }}</div>
    @endif

    @if($section === 'site')
        <div class="ops-two">
            <div class="ops-card"><h2 class="h5">Create site</h2><form method="post" action="{{ route('construction.sites.store') }}" class="row g-2">@csrf<select class="form-select" name="project_id" required><option value="">Project</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->project_name }}</option>@endforeach</select><input class="form-control" name="name" placeholder="Site name" required><input class="form-control" name="location" placeholder="Location"><input class="form-control" type="date" name="start_date"><button class="btn btn-success">Save Site</button></form></div>
            <div class="ops-card"><h2 class="h5">Daily report</h2><form method="post" action="{{ route('construction.site-reports.store') }}" class="row g-2">@csrf<select class="form-select" name="project_id" required><option value="">Project</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->project_name }}</option>@endforeach</select><select class="form-select" name="site_id"><option value="">Site</option>@foreach($sitesList as $site)<option value="{{ $site->id }}">{{ $site->name }}</option>@endforeach</select><input class="form-control" type="date" name="report_date" value="{{ now()->toDateString() }}" required><input class="form-control" type="number" name="workforce_count" placeholder="Workers today"><textarea class="form-control" name="work_completed" placeholder="Work completed"></textarea><button class="btn btn-success">Submit Report</button></form></div>
        </div>
        <div class="ops-card"><h2 class="h5">Site controls</h2><div class="row g-2"><form method="post" action="{{ route('construction.rfis.store') }}" class="col-md-4">@csrf<select class="form-select mb-2" name="project_id" required><option value="">Project</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->project_name }}</option>@endforeach</select><textarea class="form-control mb-2" name="question" placeholder="RFI question" required></textarea><button class="btn btn-sm btn-success">Raise RFI</button></form><form method="post" action="{{ route('construction.instructions.store') }}" class="col-md-4">@csrf<select class="form-select mb-2" name="project_id" required><option value="">Project</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->project_name }}</option>@endforeach</select><input class="form-control mb-2" type="date" name="instruction_date" value="{{ now()->toDateString() }}" required><textarea class="form-control mb-2" name="instruction" placeholder="Site instruction" required></textarea><button class="btn btn-sm btn-success">Issue Instruction</button></form><form method="post" action="{{ route('construction.diaries.store') }}" class="col-md-4">@csrf<select class="form-select mb-2" name="project_id" required><option value="">Project</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->project_name }}</option>@endforeach</select><input class="form-control mb-2" type="date" name="event_date" value="{{ now()->toDateString() }}" required><input class="form-control mb-2" name="event_type" placeholder="Event type" required><textarea class="form-control mb-2" name="description" placeholder="Diary note" required></textarea><button class="btn btn-sm btn-success">Add Diary</button></form></div></div>
        <div class="ops-card"><h2 class="h5">Daily reports</h2><div class="table-responsive"><table class="table"><thead><tr><th>No.</th><th>Date</th><th>Project</th><th>Site</th><th>Workers</th><th>Status</th></tr></thead><tbody>@forelse($dailyReports as $report)<tr><td>{{ $report->report_number }}</td><td>{{ $report->report_date?->format('d M Y') }}</td><td>{{ $report->project?->project_name }}</td><td>{{ $report->site?->name }}</td><td>{{ $report->workforce_count }}</td><td>{{ $report->status }}</td></tr>@empty<tr><td colspan="6" class="text-muted">No reports yet.</td></tr>@endforelse</tbody></table></div></div>
    @endif

    @if($section === 'materials')
        <div class="ops-three"></div>
        <div class="ops-two">
            <div class="ops-card"><h2 class="h5">Material</h2><form method="post" action="{{ route('construction.materials.store') }}" class="row g-2">@csrf<input class="form-control" name="name" placeholder="Material name" required><input class="form-control" name="category" placeholder="Category"><input class="form-control" name="unit" value="Item" required><input class="form-control" type="number" step="0.01" name="unit_cost" placeholder="Unit cost"><input class="form-control" type="number" step="0.001" name="stock_quantity" placeholder="Stock"><input class="form-control" type="number" step="0.001" name="reorder_level" placeholder="Reorder level"><button class="btn btn-success">Save Material</button></form></div>
            <div class="ops-card"><h2 class="h5">Material request</h2><form method="post" action="{{ route('construction.material-requests.store') }}" class="row g-2">@csrf<select class="form-select" name="project_id" required><option value="">Project</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->project_name }}</option>@endforeach</select><select class="form-select" name="site_id"><option value="">Site</option>@foreach($sitesList as $site)<option value="{{ $site->id }}">{{ $site->name }}</option>@endforeach</select><select class="form-select" name="material_id"><option value="">Material</option>@foreach($materialsList as $material)<option value="{{ $material->id }}">{{ $material->name }}</option>@endforeach</select><input class="form-control" name="material_name" placeholder="Requested material" required><input class="form-control" type="number" step="0.001" name="quantity" placeholder="Quantity" required><button class="btn btn-success">Request Material</button></form></div>
        </div>
        <div class="ops-card"><h2 class="h5">Record consumption</h2><form method="post" action="{{ route('construction.material-consumptions.store') }}" class="row g-2">@csrf<div class="col-md-3"><select class="form-select" name="project_id" required><option value="">Project</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->project_name }}</option>@endforeach</select></div><div class="col-md-3"><select class="form-select" name="material_id"><option value="">Material</option>@foreach($materialsList as $material)<option value="{{ $material->id }}">{{ $material->name }} ({{ $material->stock_quantity }})</option>@endforeach</select></div><div class="col-md-2"><input class="form-control" type="date" name="usage_date" value="{{ now()->toDateString() }}" required></div><div class="col-md-2"><input class="form-control" type="number" step="0.001" name="actual_quantity" placeholder="Actual qty" required></div><div class="col-md-2"><button class="btn btn-success w-100">Consume</button></div></form></div>
        <div class="ops-card"><h2 class="h5">Material requests</h2><div class="table-responsive"><table class="table"><thead><tr><th>No.</th><th>Project</th><th>Material</th><th>Qty</th><th>Status</th></tr></thead><tbody>@forelse($requests as $request)<tr><td>{{ $request->request_number }}</td><td>{{ $request->project?->project_name }}</td><td>{{ $request->material_name }}</td><td>{{ $request->quantity }}</td><td>{{ $request->status }}</td></tr>@empty<tr><td colspan="5" class="text-muted">No material requests yet.</td></tr>@endforelse</tbody></table></div></div>
    @endif

    @if($section === 'contractors')
        <div class="ops-two"><div class="ops-card"><h2 class="h5">Contractor</h2><form method="post" action="{{ route('construction.contractors.store') }}" class="row g-2">@csrf<input class="form-control" name="company_name" placeholder="Company name" required><select class="form-select" name="type"><option>Subcontractor</option><option>Main Contractor</option><option>Labour Contractor</option><option>Consultant</option></select><input class="form-control" name="trade" placeholder="Trade"><input class="form-control" name="contact_name" placeholder="Contact"><input class="form-control" name="phone" placeholder="Phone"><button class="btn btn-success">Save Contractor</button></form></div><div class="ops-card"><h2 class="h5">Subcontract</h2><form method="post" action="{{ route('construction.subcontracts.store') }}" class="row g-2">@csrf<select class="form-select" name="project_id" required><option value="">Project</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->project_name }}</option>@endforeach</select><select class="form-select" name="contractor_id" required><option value="">Contractor</option>@foreach($contractorsList as $contractor)<option value="{{ $contractor->id }}">{{ $contractor->company_name }}</option>@endforeach</select><textarea class="form-control" name="scope" placeholder="Scope"></textarea><input class="form-control" type="number" step="0.01" name="contract_sum" placeholder="Contract sum" required><button class="btn btn-success">Create Subcontract</button></form></div></div>
        <div class="ops-card"><h2 class="h5">Subcontracts</h2><div class="table-responsive"><table class="table"><thead><tr><th>No.</th><th>Project</th><th>Contractor</th><th>Sum</th><th>Status</th></tr></thead><tbody>@forelse($subcontracts as $subcontract)<tr><td>{{ $subcontract->subcontract_number }}</td><td>{{ $subcontract->project?->project_name }}</td><td>{{ $subcontract->contractor?->company_name }}</td><td>{{ number_format((float)$subcontract->contract_sum,2) }}</td><td>{{ $subcontract->status }}</td></tr>@empty<tr><td colspan="5" class="text-muted">No subcontracts yet.</td></tr>@endforelse</tbody></table></div></div>
    @endif

    @if($section === 'commercial')
        <div class="ops-grid"><form class="ops-card" method="post" action="{{ route('construction.measurements.store') }}">@csrf<h2 class="h6">Progress measurement</h2><select class="form-select mb-2" name="project_id" required><option value="">Project</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->project_name }}</option>@endforeach</select><input class="form-control mb-2" type="date" name="measurement_date" value="{{ now()->toDateString() }}" required><input class="form-control mb-2" type="number" step="0.001" name="measured_quantity" placeholder="Measured quantity" required><button class="btn btn-success">Record</button></form><form class="ops-card" method="post" action="{{ route('construction.certificates.store') }}">@csrf<h2 class="h6">Interim certificate</h2><select class="form-select mb-2" name="project_id" required><option value="">Project</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->project_name }}</option>@endforeach</select><select class="form-select mb-2" name="client_id"><option value="">Client</option>@foreach($clients as $client)<option value="{{ $client->id }}">{{ $client->name }}</option>@endforeach</select><input class="form-control mb-2" type="number" step="0.01" name="work_executed" placeholder="Work executed"><input class="form-control mb-2" type="number" step="0.01" name="retention" placeholder="Retention"><button class="btn btn-success">Create IPC</button></form><form class="ops-card" method="post" action="{{ route('construction.variations.store') }}">@csrf<h2 class="h6">Variation</h2><select class="form-select mb-2" name="project_id" required><option value="">Project</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->project_name }}</option>@endforeach</select><textarea class="form-control mb-2" name="description" placeholder="Description" required></textarea><input class="form-control mb-2" type="number" step="0.01" name="cost_impact" placeholder="Cost impact"><button class="btn btn-success">Create VO</button></form></div>
        <div class="ops-card"><h2 class="h5">Certificates</h2><div class="table-responsive"><table class="table"><thead><tr><th>No.</th><th>Project</th><th>Gross</th><th>Net</th><th>Status</th><th>Invoice</th></tr></thead><tbody>@forelse($certificates as $certificate)<tr><td>{{ $certificate->certificate_number }}</td><td>{{ $certificate->project?->project_name }}</td><td>{{ number_format((float)$certificate->gross_certified,2) }}</td><td>{{ number_format((float)$certificate->net_certificate,2) }}</td><td>{{ $certificate->status }}</td><td>@if(!$certificate->invoice_id)<form method="post" action="{{ route('construction.certificates.invoice',$certificate) }}">@csrf<button class="btn btn-sm btn-success">Invoice</button></form>@else Linked @endif</td></tr>@empty<tr><td colspan="6" class="text-muted">No certificates yet.</td></tr>@endforelse</tbody></table></div></div>
    @endif

    @if($section === 'quality')
        <div class="ops-two"><form class="ops-card" method="post" action="{{ route('construction.inspections.store') }}">@csrf<h2 class="h5">Inspection</h2><select class="form-select mb-2" name="project_id" required><option value="">Project</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->project_name }}</option>@endforeach</select><input class="form-control mb-2" name="inspection_type" placeholder="Inspection type" required><input class="form-control mb-2" type="date" name="inspection_date" value="{{ now()->toDateString() }}" required><select class="form-select mb-2" name="result"><option>Pass</option><option>Conditional Pass</option><option>Fail</option></select><button class="btn btn-success">Save Inspection</button></form><form class="ops-card" method="post" action="{{ route('construction.defects.store') }}">@csrf<h2 class="h5">Defect</h2><select class="form-select mb-2" name="project_id" required><option value="">Project</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->project_name }}</option>@endforeach</select><input class="form-control mb-2" name="location" placeholder="Location"><textarea class="form-control mb-2" name="description" placeholder="Defect description" required></textarea><input class="form-control mb-2" type="date" name="target_date"><button class="btn btn-success">Report Defect</button></form></div>
        <div class="ops-card"><h2 class="h5">Defects</h2><div class="table-responsive"><table class="table"><tbody>@forelse($defects as $defect)<tr><td>{{ $defect->defect_number }}</td><td>{{ $defect->project?->project_name }}</td><td>{{ $defect->description }}</td><td>{{ $defect->status }}</td></tr>@empty<tr><td class="text-muted">No defects yet.</td></tr>@endforelse</tbody></table></div></div>
    @endif

    @if($section === 'safety')
        <div class="ops-card"><h2 class="h5">Safety incident</h2><form method="post" action="{{ route('construction.incidents.store') }}" class="row g-2">@csrf<div class="col-md-3"><select class="form-select" name="project_id" required><option value="">Project</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->project_name }}</option>@endforeach</select></div><div class="col-md-2"><input class="form-control" type="date" name="incident_date" value="{{ now()->toDateString() }}" required></div><div class="col-md-2"><select class="form-select" name="severity"><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select></div><div class="col-md-5"><input class="form-control" name="description" placeholder="Description" required></div><div class="col-12"><button class="btn btn-success">Log Incident</button></div></form></div>
        <div class="ops-card"><h2 class="h5">Incident register</h2><div class="table-responsive"><table class="table"><tbody>@forelse($incidents as $incident)<tr><td>{{ $incident->incident_number }}</td><td>{{ $incident->project?->project_name }}</td><td>{{ $incident->severity }}</td><td>{{ $incident->status }}</td></tr>@empty<tr><td class="text-muted">No incidents yet.</td></tr>@endforelse</tbody></table></div></div>
    @endif

    @if($section === 'equipment')
        <div class="ops-card"><h2 class="h5">Equipment</h2><form method="post" action="{{ route('construction.equipment.store') }}" class="row g-2">@csrf<div class="col-md-2"><input class="form-control" name="equipment_code" placeholder="Code" required></div><div class="col-md-3"><input class="form-control" name="name" placeholder="Name" required></div><div class="col-md-2"><input class="form-control" name="equipment_type" placeholder="Type"></div><div class="col-md-2"><input class="form-control" type="number" step="0.01" name="cost_per_hour" placeholder="Cost/hr"></div><div class="col-md-2"><select class="form-select" name="status"><option>Available</option><option>Assigned</option><option>Operating</option><option>Maintenance</option><option>Breakdown</option><option>Idle</option><option>Retired</option></select></div><div class="col-md-1"><button class="btn btn-success">Save</button></div></form></div>
        <div class="ops-card"><div class="table-responsive"><table class="table"><tbody>@forelse($equipment as $item)<tr><td>{{ $item->equipment_code }}</td><td>{{ $item->name }}</td><td>{{ $item->equipment_type }}</td><td>{{ $item->status }}</td></tr>@empty<tr><td class="text-muted">No equipment yet.</td></tr>@endforelse</tbody></table></div></div>
    @endif

    @if($section === 'handover')
        <div class="ops-card"><h2 class="h5">Project handover</h2><form method="post" action="{{ route('construction.handovers.store') }}" class="row g-2">@csrf<div class="col-md-4"><select class="form-select" name="project_id" required><option value="">Project</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->project_name }}</option>@endforeach</select></div><div class="col-md-2"><input class="form-control" type="date" name="practical_completion_date"></div><div class="col-md-2"><input class="form-control" type="date" name="handover_date"></div><div class="col-md-2"><input class="form-control" type="date" name="dlp_end_date"></div><div class="col-md-2"><button class="btn btn-success">Create</button></div><div class="col-12"><textarea class="form-control" name="notes" placeholder="Handover notes"></textarea></div></form></div>
        <div class="ops-card"><div class="table-responsive"><table class="table"><tbody>@forelse($handovers as $handover)<tr><td>{{ $handover->handover_number }}</td><td>{{ $handover->project?->project_name }}</td><td>{{ $handover->handover_date?->format('d M Y') }}</td><td>{{ $handover->status }}</td></tr>@empty<tr><td class="text-muted">No handovers yet.</td></tr>@endforelse</tbody></table></div></div>
    @endif

    @if($section === 'reports')
        <div class="ops-card"><h2 class="h5">Construction reports</h2><div class="d-flex flex-wrap gap-2 mb-3">@foreach(['projects','boqs','materials','certificates','site-reports'] as $type)<a class="btn btn-outline-dark btn-sm" href="{{ route('construction.reports.csv',$type) }}">{{ ucwords(str_replace('-',' ',$type)) }} CSV</a>@endforeach</div><div class="ops-grid">@foreach($summary as $label => $points)<div class="border rounded p-3"><div class="ops-kicker">{{ $label }}</div><strong>{{ count($points) }} series</strong></div>@endforeach</div></div>
    @endif

    @if($section === 'mobile')
        <div class="ops-card"><h2 class="h5">Mobile site quick actions</h2><div class="ops-grid">@foreach($mobileActions as $action)<a class="btn btn-outline-success text-start" href="{{ route('construction.site') }}">{{ $action }}</a>@endforeach</div></div>
        <div class="ops-card"><h2 class="h5">Sites</h2>@forelse($sites as $site)<div class="d-flex justify-content-between border-bottom py-2"><strong>{{ $site->name }}</strong><span>{{ $site->project?->project_name }}</span></div>@empty<div class="text-muted">No sites yet.</div>@endforelse</div>
    @endif
</div>
@endsection
