<?php

return [
    'name' => 'Real Estate',
    'slug' => 'real-estate',
    'type' => 'industry',
    'description' => 'Enterprise real estate management for properties, units, tenants, leases, rental billing, sales, agents, commissions, inspections, maintenance, land, valuations, development, and portfolio operations.',
    'sub_industries' => [
        ['slug' => 'standard', 'name' => 'Real Estate Standard', 'description' => 'Core property, unit, tenant, lease, billing, sales, and maintenance operations.'],
        ['slug' => 'multi-branch', 'name' => 'Multi-Branch Real Estate', 'description' => 'Branch-aware property portfolios, teams, leasing, maintenance, sales, and reports.'],
        ['slug' => 'enterprise', 'name' => 'Enterprise Real Estate', 'description' => 'Portfolio analytics, approvals, API portals, commissions, valuations, development, and compliance-ready billing.'],
    ],
    'features' => [
        'Property Management', 'Property Listings', 'Unit Management', 'Tenant Management',
        'Lease Management', 'Rental Billing', 'Payment Management', 'Property Sales',
        'Buyer Management', 'Agent Management', 'Commission Management', 'Property Inspections',
        'Property Maintenance', 'Service Requests', 'Property Valuation', 'Land Management',
        'Property Development', 'Portfolio Management', 'Customer Portal APIs', 'ETIMS Integration',
        'Utility Billing', 'Utility Meters', 'Amenities', 'Amenity Bookings', 'Tenant Ledger', 'Tenant Statements',
        'Tenant Offboarding', 'Tenant Archiving', 'Tenant Deletion Guards', 'Document Vault',
    ],
    'core_modules' => [
        'Finance', 'Accounting', 'Payments', 'CRM', 'Inventory', 'HR', 'Procurement', 'Reporting',
        'Notifications', 'Authentication', 'User Management', 'Documents', 'Audit Logs',
        'Dashboard Framework', 'Workflow Engine', 'Communication Center', 'ETIMS Compliance',
        'POS Core', 'Approval Workflows',
    ],
    'routes' => [
        'web' => [
            'dashboard' => 'real-estate.dashboard',
            'properties' => 'real-estate.dashboard',
            'listings' => 'real-estate.dashboard',
            'units' => 'real-estate.dashboard',
            'tenants' => 'real-estate.dashboard',
            'leases' => 'real-estate.dashboard',
            'rental_billing' => 'real-estate.dashboard',
            'payments' => 'real-estate.dashboard',
            'buyers' => 'real-estate.dashboard',
            'sales' => 'real-estate.dashboard',
            'agents' => 'real-estate.dashboard',
            'commissions' => 'real-estate.dashboard',
            'maintenance' => 'real-estate.dashboard',
            'service_requests' => 'real-estate.dashboard',
            'inspections' => 'real-estate.dashboard',
            'valuations' => 'real-estate.dashboard',
            'land' => 'real-estate.dashboard',
            'development' => 'real-estate.dashboard',
            'documents' => 'real-estate.dashboard',
            'portfolio' => 'real-estate.dashboard',
            'reports' => 'real-estate.reports.index',
            'settings' => 'settings.edit',
        ],
    ],
    'api' => [
        'prefix' => '/api/v1/industries/real-estate',
        'resources' => ['dashboard', 'listings', 'leases/{lease}', 'tenant-portal/{tenant}', 'tenants/archive', 'tenants/{tenant}/ledger', 'tenants/{tenant}/payments', 'tenants/{tenant}/statements', 'tenants/{tenant}/utilities', 'tenants/{tenant}/offboarding', 'buyer-portal/{buyer}', 'agent-portal/{agent}', 'service-requests', 'utility/readings', 'utility/bills'],
    ],
    'widgets' => [
        'real-estate-properties', 'real-estate-occupancy-rate', 'real-estate-rental-revenue',
        'real-estate-sales-pipeline', 'real-estate-maintenance-open', 'real-estate-portfolio-value',
        'real-estate-commissions-outstanding', 'real-estate-lease-expiries',
        'real-estate-utility-revenue', 'real-estate-amenity-revenue', 'real-estate-tenant-ledger', 'real-estate-utility-consumption',
    ],
    'reports' => [
        'Property Reports', 'Unit Reports', 'Lease Reports', 'Tenant Reports', 'Rental Reports',
        'Sales Reports', 'Commission Reports', 'Inspection Reports', 'Maintenance Reports',
        'Valuation Reports', 'Land Reports', 'Portfolio Reports', 'ETIMS Reports',
        'Water Billing Reports', 'Electricity Billing Reports', 'Utility Collection Reports',
        'Amenity Revenue Reports', 'Tenant Ledger Reports', 'Tenant Statement Reports',
        'Outstanding Balance Reports', 'Aging Reports', 'Utility Consumption Reports',
        'Move-Out Reports', 'Archived Tenant Reports', 'Tenant History Reports', 'Vacancy Reports',
    ],
    'workflows' => [
        'Lease Approval', 'Listing Approval', 'Sale Approval', 'Maintenance Approval',
        'Valuation Approval', 'Commission Approval',
    ],
    'templates' => [
        'Lease Agreement', 'Sale Agreement', 'Inspection Report', 'Valuation Report',
        'Ownership Document', 'Land Title', 'Maintenance Work Order',
    ],
    'permissions' => [
        'real-estate.view', 'real-estate.manage', 'real-estate.reports',
        'real-estate.properties.view', 'real-estate.properties.manage',
        'real-estate.units.view', 'real-estate.units.manage',
        'real-estate.tenants.view', 'real-estate.tenants.manage', 'real-estate.tenants.offboard', 'real-estate.tenants.delete',
        'real-estate.leases.view', 'real-estate.leases.manage',
        'real-estate.billing.view', 'real-estate.billing.manage',
        'real-estate.listings.view', 'real-estate.listings.manage', 'real-estate.listings.approve',
        'real-estate.buyers.view', 'real-estate.buyers.manage',
        'real-estate.sales.view', 'real-estate.sales.manage',
        'real-estate.agents.view', 'real-estate.agents.manage',
        'real-estate.commissions.view', 'real-estate.commissions.manage', 'real-estate.commissions.approve',
        'real-estate.maintenance.view', 'real-estate.maintenance.manage',
        'real-estate.service-requests.view', 'real-estate.service-requests.manage',
        'real-estate.inspections.view', 'real-estate.inspections.manage',
        'real-estate.valuations.view', 'real-estate.valuations.manage',
        'real-estate.land.view', 'real-estate.land.manage',
        'real-estate.development.view', 'real-estate.development.manage',
        'real-estate.utilities.view', 'real-estate.utilities.manage',
        'real-estate.amenities.view', 'real-estate.amenities.manage',
        'real-estate.tenant-ledger.view', 'real-estate.tenant-ledger.manage',
        'real-estate.documents.view', 'real-estate.documents.manage',
    ],
    'roles' => [
        'Super Admin', 'Real Estate Director', 'Branch Manager', 'Property Manager',
        'Leasing Officer', 'Sales Agent', 'Property Agent', 'Accountant',
        'Maintenance Manager', 'Technician', 'Inspector', 'Valuer', 'Customer Service',
    ],
    'menus' => [
        ['label' => 'Dashboard', 'route' => 'real-estate.dashboard', 'icon' => 'bi-speedometer2', 'permission' => 'real-estate.view', 'tables' => ['real_estate_properties'], 'section' => 'dashboard'],
        ['label' => 'Properties', 'route' => 'real-estate.dashboard', 'icon' => 'bi-buildings', 'permission' => 'real-estate.properties.view', 'section' => 'properties'],
        ['label' => 'Listings', 'route' => 'real-estate.dashboard', 'icon' => 'bi-megaphone', 'permission' => 'real-estate.listings.view', 'section' => 'listings'],
        ['label' => 'Units', 'route' => 'real-estate.dashboard', 'icon' => 'bi-door-open', 'permission' => 'real-estate.units.view', 'section' => 'units'],
        ['label' => 'Tenants', 'route' => 'real-estate.dashboard', 'icon' => 'bi-people', 'permission' => 'real-estate.tenants.view', 'section' => 'tenants'],
        ['label' => 'Tenant Archive', 'route' => 'real-estate.dashboard', 'icon' => 'bi-archive', 'permission' => 'real-estate.tenants.view', 'section' => 'tenant-archive'],
        ['label' => 'Leases', 'route' => 'real-estate.dashboard', 'icon' => 'bi-file-earmark-text', 'permission' => 'real-estate.leases.view', 'section' => 'leases'],
        ['label' => 'Rental Billing', 'route' => 'real-estate.dashboard', 'icon' => 'bi-receipt', 'permission' => 'real-estate.billing.view', 'section' => 'rental-billing'],
        ['label' => 'Payments', 'route' => 'real-estate.dashboard', 'icon' => 'bi-bank', 'permission' => 'finance.view', 'section' => 'payments'],
        ['label' => 'Utilities', 'route' => 'real-estate.dashboard', 'icon' => 'bi-droplet-half', 'permission' => 'real-estate.utilities.view', 'section' => 'utilities'],
        ['label' => 'Amenities', 'route' => 'real-estate.dashboard', 'icon' => 'bi-stars', 'permission' => 'real-estate.amenities.view', 'section' => 'amenities'],
        ['label' => 'Tenant Ledger', 'route' => 'real-estate.dashboard', 'icon' => 'bi-journal-text', 'permission' => 'real-estate.tenant-ledger.view', 'section' => 'tenant-ledger'],
        ['label' => 'Collections', 'route' => 'real-estate.dashboard', 'icon' => 'bi-wallet2', 'permission' => 'real-estate.tenant-ledger.view', 'section' => 'collections'],
        ['label' => 'Consumption', 'route' => 'real-estate.dashboard', 'icon' => 'bi-graph-up', 'permission' => 'real-estate.utilities.view', 'section' => 'consumption'],
        ['label' => 'Buyers', 'route' => 'real-estate.dashboard', 'icon' => 'bi-person-check', 'permission' => 'real-estate.buyers.view', 'section' => 'buyers'],
        ['label' => 'Sales', 'route' => 'real-estate.dashboard', 'icon' => 'bi-cash-stack', 'permission' => 'real-estate.sales.view', 'section' => 'sales'],
        ['label' => 'Agents', 'route' => 'real-estate.dashboard', 'icon' => 'bi-person-badge', 'permission' => 'real-estate.agents.view', 'section' => 'agents'],
        ['label' => 'Commissions', 'route' => 'real-estate.dashboard', 'icon' => 'bi-percent', 'permission' => 'real-estate.commissions.view', 'section' => 'commissions'],
        ['label' => 'Maintenance', 'route' => 'real-estate.dashboard', 'icon' => 'bi-tools', 'permission' => 'real-estate.maintenance.view', 'section' => 'maintenance'],
        ['label' => 'Service Requests', 'route' => 'real-estate.dashboard', 'icon' => 'bi-life-preserver', 'permission' => 'real-estate.service-requests.view', 'section' => 'service-requests'],
        ['label' => 'Inspections', 'route' => 'real-estate.dashboard', 'icon' => 'bi-clipboard-check', 'permission' => 'real-estate.inspections.view', 'section' => 'inspections'],
        ['label' => 'Valuations', 'route' => 'real-estate.dashboard', 'icon' => 'bi-graph-up-arrow', 'permission' => 'real-estate.valuations.view', 'section' => 'valuations'],
        ['label' => 'Land Management', 'route' => 'real-estate.dashboard', 'icon' => 'bi-map', 'permission' => 'real-estate.land.view', 'section' => 'land'],
        ['label' => 'Property Development', 'route' => 'real-estate.dashboard', 'icon' => 'bi-building-gear', 'permission' => 'real-estate.development.view', 'section' => 'development'],
        ['label' => 'Documents', 'route' => 'real-estate.dashboard', 'icon' => 'bi-folder2-open', 'permission' => 'real-estate.documents.view', 'section' => 'documents'],
        ['label' => 'Portfolio', 'route' => 'real-estate.dashboard', 'icon' => 'bi-pie-chart', 'permission' => 'real-estate.view', 'section' => 'portfolio'],
        ['label' => 'Reports', 'route' => 'real-estate.reports.index', 'icon' => 'bi-bar-chart', 'permission' => 'real-estate.reports'],
        ['label' => 'Settings', 'route' => 'settings.edit', 'icon' => 'bi-gear'],
    ],
    'integrations' => [
        'crm' => 'Tenants, buyers, and investors extend existing Clients and Contacts.',
        'finance' => 'Rental and sale invoices are generated through shared Invoices, Payments, Finance, and Accounting.',
        'utility_billing' => 'Utility readings, utility bills, amenity bookings, and tenant statements generate shared invoices and ledger rows without replacing Finance, Payments, or Accounting.',
        'etims' => 'Rental and property-sale invoices remain compatible with shared ETIMS submissions.',
        'documents' => 'Lease agreements, sale agreements, inspection reports, valuations, land titles, and contracts use shared Documents.',
        'communication' => 'Tenant, agent, branch, and internal messages use the shared Communication Center.',
        'workflow' => 'Listing, lease, sale, maintenance, valuation, and commission approvals use shared approval workflows.',
        'procurement' => 'Vendors and maintenance supplier assignment reuse shared Suppliers and Procurement.',
        'audit' => 'Material records are business-scoped and compatible with shared audit logging.',
    ],
    'tenant_isolated' => true,
    'role_permissions' => true,
    'dynamic_menus' => true,
    'dashboard_widgets' => true,
    'api_endpoints' => true,
    'subscription_activated' => true,
];
