<?php

$modules = [
    'Farm Management', 'Livestock Management', 'Crop Planning', 'Harvest Tracking',
    'Input Management', 'Equipment Tracking', 'Agricultural Finance', 'Farm Inventory',
    'Farm Procurement', 'Farm Workers', 'Field Management', 'Irrigation Management',
    'Farm Activities', 'Produce Management', 'Sales & Buyers', 'Warehouse / Storage',
    'Weather Records', 'Pest & Disease Management', 'Fertilizer Management',
    'Feed Management', 'Veterinary Management', 'Breeding Management',
    'Farm Compliance', 'Agricultural Reports', 'Farm Analytics', 'Traceability',
    'Document Management', 'Contract Farming', 'Outgrower Management',
];

$subIndustries = [
    ['slug' => 'standard', 'name' => 'Agriculture Standard', 'modules' => ['Farm Management', 'Field Management', 'Crop Planning', 'Input Management', 'Harvest Tracking', 'Produce Management', 'Equipment Tracking', 'Agricultural Finance']],
    ['slug' => 'multi-branch', 'name' => 'Multi-Branch Agriculture', 'modules' => ['Farm Management', 'Field Management', 'Farm Workers', 'Crop Planning', 'Input Management', 'Harvest Tracking', 'Equipment Tracking', 'Farm Procurement', 'Agricultural Reports']],
    ['slug' => 'enterprise', 'name' => 'Enterprise Agriculture', 'modules' => $modules],
    ['slug' => 'crop-farming', 'name' => 'Crop Farming', 'modules' => ['Farm Management', 'Field Management', 'Crop Planning', 'Input Management', 'Harvest Tracking', 'Equipment Tracking', 'Irrigation Management', 'Produce Management', 'Agricultural Finance']],
    ['slug' => 'livestock-farming', 'name' => 'Livestock Farming', 'modules' => ['Farm Management', 'Livestock Management', 'Veterinary Management', 'Breeding Management', 'Feed Management', 'Equipment Tracking', 'Agricultural Finance']],
    ['slug' => 'mixed-farming', 'name' => 'Mixed Farming', 'modules' => $modules],
    ['slug' => 'dairy-farming', 'name' => 'Dairy Farming', 'modules' => ['Livestock Management', 'Veterinary Management', 'Breeding Management', 'Feed Management', 'Farm Inventory', 'Agricultural Finance']],
    ['slug' => 'poultry-farming', 'name' => 'Poultry Farming', 'modules' => ['Livestock Management', 'Feed Management', 'Veterinary Management', 'Breeding Management', 'Sales & Buyers', 'Agricultural Finance']],
    ['slug' => 'horticulture', 'name' => 'Horticulture', 'modules' => ['Farm Management', 'Field Management', 'Crop Planning', 'Input Management', 'Irrigation Management', 'Harvest Tracking', 'Produce Management', 'Sales & Buyers']],
    ['slug' => 'greenhouse-farming', 'name' => 'Greenhouse Farming', 'modules' => ['Farm Management', 'Field Management', 'Crop Planning', 'Input Management', 'Irrigation Management', 'Pest & Disease Management', 'Harvest Tracking', 'Produce Management']],
    ['slug' => 'floriculture', 'name' => 'Floriculture', 'modules' => ['Farm Management', 'Crop Planning', 'Irrigation Management', 'Pest & Disease Management', 'Harvest Tracking', 'Sales & Buyers', 'Traceability']],
    ['slug' => 'aquaculture', 'name' => 'Aquaculture', 'modules' => ['Farm Management', 'Livestock Management', 'Feed Management', 'Veterinary Management', 'Harvest Tracking', 'Produce Management', 'Irrigation Management', 'Agricultural Finance']],
    ['slug' => 'beekeeping', 'name' => 'Beekeeping', 'modules' => ['Farm Management', 'Livestock Management', 'Feed Management', 'Harvest Tracking', 'Produce Management', 'Sales & Buyers']],
    ['slug' => 'coffee-farming', 'name' => 'Coffee Farming', 'modules' => ['Farm Management', 'Crop Planning', 'Input Management', 'Harvest Tracking', 'Produce Management', 'Warehouse / Storage', 'Traceability']],
    ['slug' => 'tea-farming', 'name' => 'Tea Farming', 'modules' => ['Farm Management', 'Crop Planning', 'Input Management', 'Harvest Tracking', 'Produce Management', 'Farm Workers', 'Traceability']],
    ['slug' => 'grain-farming', 'name' => 'Grain Farming', 'modules' => ['Farm Management', 'Field Management', 'Crop Planning', 'Equipment Tracking', 'Harvest Tracking', 'Warehouse / Storage', 'Sales & Buyers']],
    ['slug' => 'fruit-farming', 'name' => 'Fruit Farming', 'modules' => ['Farm Management', 'Crop Planning', 'Pest & Disease Management', 'Irrigation Management', 'Harvest Tracking', 'Produce Management']],
    ['slug' => 'vegetable-farming', 'name' => 'Vegetable Farming', 'modules' => ['Farm Management', 'Crop Planning', 'Input Management', 'Irrigation Management', 'Harvest Tracking', 'Produce Management']],
    ['slug' => 'plantation-farming', 'name' => 'Plantation Farming', 'modules' => ['Farm Management', 'Farm Workers', 'Crop Planning', 'Equipment Tracking', 'Harvest Tracking', 'Agricultural Finance', 'Farm Compliance']],
    ['slug' => 'agribusiness', 'name' => 'Agribusiness', 'modules' => ['Farm Procurement', 'Farm Inventory', 'Produce Management', 'Sales & Buyers', 'Warehouse / Storage', 'Contract Farming', 'Outgrower Management', 'Agricultural Finance']],
    ['slug' => 'agricultural-cooperative', 'name' => 'Agricultural Cooperative', 'modules' => ['Outgrower Management', 'Contract Farming', 'Produce Management', 'Warehouse / Storage', 'Sales & Buyers', 'Agricultural Finance']],
    ['slug' => 'agricultural-input-supplier', 'name' => 'Agricultural Input Supplier', 'modules' => ['Input Management', 'Farm Inventory', 'Farm Procurement', 'Sales & Buyers', 'Warehouse / Storage']],
    ['slug' => 'agricultural-produce-aggregator', 'name' => 'Agricultural Produce Aggregator', 'modules' => ['Outgrower Management', 'Produce Management', 'Warehouse / Storage', 'Traceability', 'Sales & Buyers', 'Agricultural Finance']],
];

return [
    'name' => 'Agriculture',
    'slug' => 'agriculture',
    'type' => 'industry',
    'description' => 'Full agriculture ERP for farms, fields, crop cycles, livestock, inputs, workers, equipment, produce, storage, buyers, compliance, traceability, analytics, and finance.',
    'features' => $modules,
    'modules' => $modules,
    'core_modules' => ['CRM', 'Projects', 'Finance', 'Accounting', 'Documents', 'Reporting', 'HR', 'Administration', 'Portal', 'Notifications', 'Inventory', 'Procurement', 'Audit Logs'],
    'routes' => [
        'web' => ['dashboard' => 'agriculture.dashboard', 'reports' => 'agriculture.reports.index'],
    ],
    'api' => [
        'prefix' => '/api/v1/industries/agriculture',
        'resources' => ['dashboard', 'records/{type}', 'reports/{type}/export', 'traceability/{batch}'],
    ],
    'widgets' => ['agriculture-overview', 'agriculture-farm-utilization', 'agriculture-crop-calendar', 'agriculture-harvest-trends', 'agriculture-livestock-health', 'agriculture-input-stock', 'agriculture-equipment-availability', 'agriculture-risk-alerts'],
    'reports' => ['Farm Performance', 'Acreage Utilization', 'Field Utilization', 'Crop Performance', 'Yield Analysis', 'Crop Profitability', 'Crop Cycle Report', 'Planting Report', 'Harvest Forecast', 'Livestock Inventory', 'Birth Report', 'Mortality Report', 'Vaccination Report', 'Production Report', 'Feed Consumption', 'Animal Profitability', 'Input Purchases', 'Input Consumption', 'Fertilizer Usage', 'Chemical Usage', 'Input Cost by Crop', 'Equipment Utilization', 'Fuel Consumption', 'Maintenance Cost', 'Downtime', 'Farm Profitability', 'Seasonal Profitability', 'Cost per Acre', 'Cost per Kg', 'Revenue by Product', 'Buyer Sales', 'Farm Budget vs Actual'],
    'workflows' => ['Crop Planning Approval', 'Input Issue', 'Activity Scheduling', 'Harvest Processing', 'Produce Traceability', 'Livestock Health Review', 'Equipment Maintenance Reminder', 'Compliance Expiry Alert', 'Budget Threshold Alert'],
    'templates' => ['Farm License', 'Organic Certificate', 'Soil Test Report', 'Veterinary Report', 'Produce Quality Report', 'Supply Contract', 'Export Document', 'Farm Map', 'Equipment Document'],
    'permissions' => [
        'agriculture.view', 'agriculture.manage', 'agriculture.reports', 'agriculture.settings',
        'farms.manage', 'fields.manage', 'crops.manage', 'crop_plans.manage', 'farm_activities.manage',
        'harvests.manage', 'livestock.manage', 'veterinary.manage', 'breeding.manage', 'inputs.manage',
        'equipment.manage', 'agriculture.procurement', 'agriculture.finance', 'agriculture.documents.manage',
    ],
    'roles' => ['Agriculture Administrator', 'Farm Manager', 'Farm Supervisor', 'Agronomist', 'Livestock Manager', 'Veterinarian', 'Field Officer', 'Store Keeper', 'Equipment Manager', 'Farm Accountant', 'Farm Worker', 'Agriculture Viewer'],
    'menus' => [
        ['label' => 'Dashboard', 'route' => 'agriculture.dashboard', 'icon' => 'bi-speedometer2', 'permission' => 'agriculture.view', 'tables' => ['agriculture_farms'], 'section' => 'dashboard'],
        ['label' => 'Farms', 'route' => 'agriculture.dashboard', 'icon' => 'bi-flower1', 'permission' => 'agriculture.view', 'section' => 'farms'],
        ['label' => 'Crops', 'route' => 'agriculture.dashboard', 'icon' => 'bi-calendar2-week', 'permission' => 'crops.manage', 'section' => 'crops'],
        ['label' => 'Harvest', 'route' => 'agriculture.dashboard', 'icon' => 'bi-basket', 'permission' => 'harvests.manage', 'section' => 'harvest'],
        ['label' => 'Livestock', 'route' => 'agriculture.dashboard', 'icon' => 'bi-heart-pulse', 'permission' => 'livestock.manage', 'section' => 'livestock'],
        ['label' => 'Inputs', 'route' => 'agriculture.dashboard', 'icon' => 'bi-droplet', 'permission' => 'inputs.manage', 'section' => 'inputs'],
        ['label' => 'Equipment', 'route' => 'agriculture.dashboard', 'icon' => 'bi-truck', 'permission' => 'equipment.manage', 'section' => 'equipment'],
        ['label' => 'Irrigation', 'route' => 'agriculture.dashboard', 'icon' => 'bi-water', 'permission' => 'fields.manage', 'section' => 'irrigation'],
        ['label' => 'Workers', 'route' => 'agriculture.dashboard', 'icon' => 'bi-people', 'permission' => 'farms.manage', 'section' => 'workers'],
        ['label' => 'Procurement', 'route' => 'erp.procurement', 'icon' => 'bi-cart-check', 'permission' => 'agriculture.procurement'],
        ['label' => 'Storage', 'route' => 'agriculture.dashboard', 'icon' => 'bi-box-seam', 'permission' => 'harvests.manage', 'section' => 'storage'],
        ['label' => 'Buyers & Sales', 'route' => 'agriculture.dashboard', 'icon' => 'bi-cash-stack', 'permission' => 'agriculture.finance', 'section' => 'sales'],
        ['label' => 'Compliance', 'route' => 'agriculture.dashboard', 'icon' => 'bi-shield-check', 'permission' => 'agriculture.settings', 'section' => 'compliance'],
        ['label' => 'Documents', 'route' => 'agriculture.dashboard', 'icon' => 'bi-folder2-open', 'permission' => 'agriculture.documents.manage', 'section' => 'documents'],
        ['label' => 'Finance', 'route' => 'agriculture.dashboard', 'icon' => 'bi-bank', 'permission' => 'agriculture.finance', 'section' => 'finance'],
        ['label' => 'Reports', 'route' => 'agriculture.reports.index', 'icon' => 'bi-bar-chart', 'permission' => 'agriculture.reports'],
        ['label' => 'Settings', 'route' => 'settings.edit', 'icon' => 'bi-gear', 'permission' => 'agriculture.settings'],
    ],
    'menu_structure' => ['Dashboard', 'Farms', 'Fields', 'Plots', 'Seasons', 'Crop Master', 'Crop Plans', 'Farm Activities', 'Crop Calendar', 'Harvest Records', 'Produce Batches', 'Yield Analysis', 'Animals', 'Herds / Flocks', 'Health', 'Vaccination', 'Breeding', 'Production', 'Inputs', 'Stock', 'Usage', 'Fertilizers', 'Chemicals', 'Equipment', 'Equipment Usage', 'Equipment Maintenance', 'Irrigation', 'Workers', 'Procurement', 'Storage', 'Buyers & Sales', 'Compliance', 'Finance', 'Reports', 'Settings'],
    'integrations' => [
        'crm' => 'Farmers, outgrowers, cooperatives, and produce buyers link to shared Clients and Contacts.',
        'finance' => 'Produce sales create shared invoices and post through the existing Finance engine.',
        'inventory' => 'Inputs, feed, and produce batches reuse shared Products and Stock movements where products are linked.',
        'procurement' => 'Farm supplier purchase flows use shared Suppliers, Purchase Orders, Goods Received, Supplier Invoices, and Payments.',
        'documents' => 'Farm licenses, certificates, soil tests, veterinary reports, export documents, and maps use document templates and agriculture document records.',
        'cost_accounting' => 'Farm, field, crop plan, livestock, equipment, and harvest costs are captured for shared cost reporting.',
    ],
    'dashboard_features' => ['Executive KPIs', 'Farm Management Dashboard', 'Livestock Management Dashboard', 'Crop Planning Dashboard', 'Harvest Tracking Dashboard', 'Risk Alerts', 'Workflow Performance', 'Compliance Status'],
    'sub_industries' => array_map(fn ($sub) => $sub + [
        'description' => 'Agriculture operating profile with dynamic module activation for '.$sub['name'].'.',
        'dashboard_features' => ['Executive KPIs', 'Risk Alerts', 'Workflow Performance', 'Compliance Status'],
    ], $subIndustries),
    'registration_sub_industries' => array_column($subIndustries, 'slug'),
    'tenant_isolated' => true,
    'role_permissions' => true,
    'dynamic_menus' => true,
    'dashboard_widgets' => true,
    'api_endpoints' => true,
    'subscription_activated' => true,
];
