<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
 public function up(): void {
  Schema::create('finance_accounts', function(Blueprint $t){$t->id();$t->foreignId('business_id')->constrained()->cascadeOnDelete();$t->foreignId('parent_id')->nullable()->constrained('finance_accounts')->nullOnDelete();$t->string('code',30);$t->string('name');$t->string('type',30);$t->string('subtype')->nullable();$t->boolean('is_system')->default(false);$t->boolean('is_active')->default(true);$t->timestamps();$t->unique(['business_id','code']);});
  Schema::create('finance_periods', function(Blueprint $t){$t->id();$t->foreignId('business_id')->constrained()->cascadeOnDelete();$t->string('name');$t->date('starts_at');$t->date('ends_at');$t->string('status')->default('Open');$t->foreignId('closed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('closed_at')->nullable();$t->timestamps();});
  Schema::create('journal_entries', function(Blueprint $t){$t->id();$t->foreignId('business_id')->constrained()->cascadeOnDelete();$t->string('entry_number');$t->date('entry_date');$t->string('description');$t->string('source_type')->nullable();$t->unsignedBigInteger('source_id')->nullable();$t->string('status')->default('Draft');$t->foreignId('reversal_of_id')->nullable()->constrained('journal_entries')->nullOnDelete();$t->text('reason')->nullable();$t->boolean('is_recurring')->default(false);$t->string('recurrence')->nullable();$t->date('next_run_at')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('approved_by')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('reversed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('approved_at')->nullable();$t->timestamp('reversed_at')->nullable();$t->timestamps();$t->unique(['business_id','entry_number']);$t->unique(['business_id','source_type','source_id']);});
  Schema::create('journal_lines', function(Blueprint $t){$t->id();$t->foreignId('journal_entry_id')->constrained()->cascadeOnDelete();$t->foreignId('finance_account_id')->constrained()->restrictOnDelete();$t->foreignId('department_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('cost_center_id')->nullable()->constrained()->nullOnDelete();$t->unsignedBigInteger('project_id')->nullable();$t->string('description')->nullable();$t->decimal('debit',15,2)->default(0);$t->decimal('credit',15,2)->default(0);$t->timestamps();});
  Schema::create('bank_accounts', function(Blueprint $t){$t->id();$t->foreignId('business_id')->constrained()->cascadeOnDelete();$t->foreignId('finance_account_id')->constrained()->restrictOnDelete();$t->string('name');$t->string('type')->default('Bank');$t->string('institution')->nullable();$t->string('account_number')->nullable();$t->string('currency',3)->default('KES');$t->decimal('opening_balance',15,2)->default(0);$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('bank_transactions', function(Blueprint $t){$t->id();$t->foreignId('business_id')->constrained()->cascadeOnDelete();$t->foreignId('bank_account_id')->constrained()->cascadeOnDelete();$t->foreignId('journal_entry_id')->nullable()->constrained()->nullOnDelete();$t->date('transaction_date');$t->string('type');$t->string('reference')->nullable();$t->text('description')->nullable();$t->decimal('amount',15,2);$t->boolean('is_reconciled')->default(false);$t->timestamp('reconciled_at')->nullable();$t->foreignId('reconciled_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
  Schema::create('bank_statement_lines', function(Blueprint $t){$t->id();$t->foreignId('business_id')->constrained()->cascadeOnDelete();$t->foreignId('bank_account_id')->constrained()->cascadeOnDelete();$t->foreignId('bank_transaction_id')->nullable()->constrained()->nullOnDelete();$t->date('transaction_date');$t->string('reference')->nullable();$t->text('description')->nullable();$t->decimal('amount',15,2);$t->string('match_status')->default('Unmatched');$t->timestamps();});
  Schema::create('fixed_assets', function(Blueprint $t){$t->id();$t->foreignId('business_id')->constrained()->cascadeOnDelete();$t->foreignId('asset_account_id')->constrained('finance_accounts')->restrictOnDelete();$t->foreignId('depreciation_account_id')->constrained('finance_accounts')->restrictOnDelete();$t->foreignId('expense_account_id')->constrained('finance_accounts')->restrictOnDelete();$t->string('asset_number');$t->string('name');$t->string('category');$t->date('purchase_date');$t->decimal('cost',15,2);$t->decimal('residual_value',15,2)->default(0);$t->unsignedInteger('useful_life_months');$t->string('depreciation_method')->default('Straight-line');$t->decimal('reducing_rate',5,2)->nullable();$t->string('location')->nullable();$t->string('assigned_to')->nullable();$t->string('status')->default('Active');$t->date('disposed_at')->nullable();$t->decimal('disposal_proceeds',15,2)->nullable();$t->timestamps();$t->unique(['business_id','asset_number']);});
  Schema::create('asset_depreciation_schedules', function(Blueprint $t){$t->id();$t->foreignId('fixed_asset_id')->constrained()->cascadeOnDelete();$t->foreignId('journal_entry_id')->nullable()->constrained()->nullOnDelete();$t->date('period_date');$t->decimal('opening_value',15,2);$t->decimal('depreciation',15,2);$t->decimal('closing_value',15,2);$t->string('status')->default('Scheduled');$t->timestamps();$t->unique(['fixed_asset_id','period_date']);});
  Schema::create('tax_records', function(Blueprint $t){$t->id();$t->foreignId('business_id')->constrained()->cascadeOnDelete();$t->string('tax_type');$t->date('period_start');$t->date('period_end');$t->date('due_date')->nullable();$t->decimal('input_amount',15,2)->default(0);$t->decimal('output_amount',15,2)->default(0);$t->decimal('payable_amount',15,2)->default(0);$t->string('status')->default('Draft');$t->string('filing_reference')->nullable();$t->timestamp('filed_at')->nullable();$t->timestamps();});
  if(!Schema::hasColumn('clients','credit_limit')) Schema::table('clients',fn(Blueprint $t)=>$t->decimal('credit_limit',15,2)->nullable()->after('name'));
 }
 public function down(): void {if(Schema::hasColumn('clients','credit_limit'))Schema::table('clients',fn(Blueprint $t)=>$t->dropColumn('credit_limit'));foreach(['tax_records','asset_depreciation_schedules','fixed_assets','bank_statement_lines','bank_transactions','bank_accounts','journal_lines','journal_entries','finance_periods','finance_accounts'] as $table)Schema::dropIfExists($table);}
};
