<?php

$modules = [
    'CRM',
    'Estimating',
    'Job Production',
    'Electronic Job Tickets',
    'Purchase',
    'Inventory',
    'Dispatch',
    'Invoicing',
    'Dashboards',
    'Reporting',
    'Customization',
    'Integrations',
    'Artwork Management',
    'Proof Approval',
    'Production Scheduling',
    'Machines',
    'Finishing',
    'Quality Control',
    'Materials',
    'Deliveries',
    'Costing',
    'Waste Tracking',
];

$kpis = [
    'New Leads',
    'Quotations Pending',
    'Quotes Approved',
    'Jobs Open',
    'Jobs In Production',
    'Jobs Awaiting Artwork',
    'Jobs Awaiting Client Approval',
    'Jobs Ready for Dispatch',
    'Jobs Overdue',
    'Jobs Completed Today',
    'Revenue Today',
    'Monthly Revenue',
    'Gross Margin',
    'Outstanding Invoices',
    'Stock Alerts',
    'Machines Under Maintenance',
    'Production Efficiency',
    'Waste Percentage',
];

$charts = [
    'Sales Trend',
    'Jobs by Status',
    'Revenue by Product',
    'Revenue by Client',
    'Production Volume',
    'Top Products',
    'Top Customers',
    'Material Consumption',
    'Waste Trends',
    'Machine Utilization',
];

$subIndustries = [
    ['slug' => 'standard', 'name' => 'Printing & Branding Standard', 'modules' => ['CRM', 'Estimating', 'Job Production', 'Artwork Management', 'Proof Approval', 'Inventory', 'Dispatch', 'Invoicing', 'Reporting']],
    ['slug' => 'commercial-printing', 'name' => 'Commercial Printing', 'modules' => ['Estimating', 'Job Production', 'Digital Printing', 'Offset Printing', 'Finishing', 'Inventory', 'Dispatch']],
    ['slug' => 'digital-printing', 'name' => 'Digital Printing', 'modules' => ['CRM', 'Estimating', 'Job Production', 'Artwork Management', 'Digital Printing', 'Finishing', 'Inventory', 'Dispatch', 'Finance', 'Reporting']],
    ['slug' => 'offset-printing', 'name' => 'Offset Printing', 'modules' => ['Prepress', 'Plates', 'Press Scheduling', 'Paper Stock', 'Ink', 'Finishing', 'Outsourcing']],
    ['slug' => 'large-format-printing', 'name' => 'Large Format Printing', 'modules' => ['Estimating', 'Artwork Management', 'Large Format Production', 'Materials', 'Finishing', 'Dispatch']],
    ['slug' => 'screen-printing', 'name' => 'Screen Printing', 'modules' => ['Screen Setup', 'Color Separation', 'Ink Tracking', 'Screen Production', 'Garment Inventory', 'Job Production']],
    ['slug' => 'dtf-printing', 'name' => 'DTF Printing', 'modules' => ['Garment Products', 'DTF Production', 'Artwork Management', 'Film Consumption', 'Powder Consumption', 'Heat Press', 'Garment Inventory', 'Production Jobs', 'Job Costing']],
    ['slug' => 'sublimation-printing', 'name' => 'Sublimation Printing', 'modules' => ['Artwork Management', 'Sublimation Production', 'Heat Press', 'Garment Inventory', 'Materials', 'Dispatch']],
    ['slug' => 'embroidery', 'name' => 'Embroidery', 'modules' => ['Artwork Management', 'Digitizing', 'Machines', 'Thread Tracking', 'Garment Inventory', 'Quality Control']],
    ['slug' => 'corporate-branding', 'name' => 'Corporate Branding', 'modules' => ['Apparel', 'Merchandise', 'Signage', 'Embroidery', 'Outsourcing', 'Project Jobs']],
    ['slug' => 'signage-displays', 'name' => 'Signage & Displays', 'modules' => ['Signage Production', 'Materials', 'Fabrication', 'Installation', 'Site Jobs', 'Vehicle Branding']],
    ['slug' => 'packaging-printing', 'name' => 'Packaging Printing', 'modules' => ['Packaging Products', 'Die Cutting', 'Material Sheets', 'Finishing', 'Quality Control', 'Batch Tracking']],
    ['slug' => 'labels-stickers', 'name' => 'Labels & Stickers', 'modules' => ['Estimating', 'Materials', 'Digital Printing', 'Die Cutting', 'Quality Control']],
    ['slug' => 'promotional-merchandise', 'name' => 'Promotional Merchandise', 'modules' => ['Merchandise', 'Outsourcing', 'Artwork Management', 'Inventory', 'Dispatch']],
    ['slug' => 'apparel-printing', 'name' => 'Apparel Printing', 'modules' => ['Garment Products', 'DTF Production', 'Screen Production', 'Embroidery', 'Garment Inventory']],
    ['slug' => 'publishing-book-printing', 'name' => 'Publishing & Book Printing', 'modules' => ['Estimating', 'Prepress', 'Books', 'Binding', 'Finishing', 'Dispatch']],
    ['slug' => 'photographic-printing', 'name' => 'Photographic Printing', 'modules' => ['Digital Printing', 'Artwork Management', 'Materials', 'Finishing']],
    ['slug' => 'vehicle-branding', 'name' => 'Vehicle Branding', 'modules' => ['Signage Production', 'Vehicle Branding', 'Materials', 'Installation', 'Dispatch']],
    ['slug' => 'outdoor-advertising', 'name' => 'Outdoor Advertising', 'modules' => ['Large Format Production', 'Signage Production', 'Site Jobs', 'Installation', 'Dispatch']],
    ['slug' => 'enterprise', 'name' => 'Enterprise Printing & Branding', 'modules' => array_merge($modules, ['Multi-Branch', 'Executive Dashboard', 'Advanced Reporting', 'Approval Workflows', 'Cross-Branch Production', 'Advanced Cost Accounting', 'Machine Analytics', 'Production Capacity Planning'])],
    ['slug' => 'multi-branch', 'name' => 'Multi-Branch Printing & Branding', 'modules' => array_merge($modules, ['Multi-Branch', 'Cross-Branch Production', 'Consolidated Reporting'])],
];

return [
    'name' => 'Printing & Branding',
    'slug' => 'printing_branding',
    'type' => 'industry',
    'description' => 'Complete printing and branding ERP for estimating, artwork, proof approvals, production jobs, job tickets, materials, machines, dispatch, costing, waste, and profitability.',
    'features' => $modules,
    'modules' => $modules,
    'core_modules' => ['Authentication', 'CRM', 'Clients', 'Contacts', 'Quotations', 'Invoices', 'Payments', 'Finance', 'Accounting', 'Cost Accounting', 'Procurement', 'Suppliers', 'Inventory', 'Products', 'Documents', 'Reporting', 'Notifications', 'Audit Logs', 'Client Portal', 'Communication'],
    'routes' => [
        'web' => ['dashboard' => 'printing-branding.dashboard', 'reports' => 'printing-branding.reports'],
    ],
    'api' => [
        'prefix' => '/api/v1/industries/printing-branding',
        'resources' => ['dashboard', 'records/{type}', 'mobile/jobs/{job}', 'reports/{type}/export'],
    ],
    'widgets' => ['printing-overview', 'printing-sales-trend', 'printing-jobs-by-status', 'printing-machine-utilization', 'printing-waste-trends'],
    'reports' => [
        'Sales by Client', 'Sales by Product', 'Sales by Salesperson', 'Quotations Conversion', 'Monthly Revenue',
        'Jobs by Status', 'Jobs Completed', 'Overdue Jobs', 'Production Time', 'Turnaround Time', 'Job Reprints',
        'Job Profitability', 'Estimated vs Actual Cost', 'Material Cost', 'Machine Cost', 'Waste Cost',
        'Stock Valuation', 'Material Usage', 'Low Stock', 'Dead Stock', 'Fast Moving Materials',
        'Machine Utilization', 'Machine Downtime', 'Maintenance Costs',
        'Jobs by Employee', 'Production Output', 'Design Turnaround', 'Quality Rejection Rate',
    ],
    'workflows' => ['Lead', 'Estimate', 'Quotation', 'Client Approval', 'Artwork', 'Proof Approval', 'Production Job', 'Electronic Job Ticket', 'Material Allocation', 'Production', 'Finishing', 'Quality Control', 'Dispatch', 'Invoice', 'Payment', 'Job Profitability', 'Reorder'],
    'templates' => ['Business Card 300gsm', 'A5 Flyer', 'A4 Brochure', 'Pull-Up Banner', 'PVC Banner', 'Corporate T-Shirt', 'DTF T-Shirt', 'Embroidered Polo', 'Vehicle Branding', 'A5 Notebook', 'Mug Branding'],
    'permissions' => [
        'printing.view', 'printing.dashboard',
        'estimates.view', 'estimates.create', 'estimates.approve',
        'production_jobs.view', 'production_jobs.create', 'production_jobs.update', 'production_jobs.approve',
        'artwork.view', 'artwork.manage', 'artwork.approve',
        'production.schedule', 'production.execute', 'production.quality_control',
        'machines.manage', 'inventory.consume', 'dispatch.manage',
        'job_costing.view', 'job_costing.manage',
        'printing_reports.view', 'printing_settings.manage',
    ],
    'roles' => ['Printing Administrator', 'Managing Director', 'Sales Manager', 'Sales Executive', 'Estimator', 'Graphic Designer', 'Prepress Operator', 'Production Manager', 'Machine Operator', 'Finishing Operator', 'Quality Controller', 'Store Manager', 'Procurement Officer', 'Dispatch Officer', 'Finance Officer', 'Accountant', 'Viewer'],
    'menus' => [
        ['label' => 'Dashboard', 'route' => 'printing-branding.dashboard', 'icon' => 'bi-speedometer2', 'permission' => 'printing.dashboard', 'tables' => ['printing_jobs']],
        ['label' => 'CRM', 'route' => 'clients.index', 'icon' => 'bi-people', 'permission' => 'clients.view'],
        ['label' => 'Estimating', 'route' => 'printing-branding.estimates', 'icon' => 'bi-calculator', 'permission' => 'estimates.view', 'tables' => ['printing_estimates']],
        ['label' => 'Quotations', 'route' => 'quotations.index', 'icon' => 'bi-file-earmark-text'],
        ['label' => 'Jobs', 'route' => 'printing-branding.jobs', 'icon' => 'bi-kanban', 'permission' => 'production_jobs.view', 'tables' => ['printing_jobs']],
        ['label' => 'Production Board', 'route' => 'printing-branding.board', 'icon' => 'bi-columns-gap', 'permission' => 'production_jobs.view', 'tables' => ['printing_jobs']],
        ['label' => 'Job Tickets', 'route' => 'printing-branding.tickets', 'icon' => 'bi-upc-scan', 'permission' => 'production_jobs.view', 'tables' => ['printing_job_tickets']],
        ['label' => 'Production Schedule', 'route' => 'printing-branding.schedule', 'icon' => 'bi-calendar-week', 'permission' => 'production.schedule', 'tables' => ['printing_schedules']],
        ['label' => 'Artwork', 'route' => 'printing-branding.artwork', 'icon' => 'bi-palette', 'permission' => 'artwork.view', 'tables' => ['printing_artworks']],
        ['label' => 'Production', 'route' => 'printing-branding.production', 'icon' => 'bi-printer', 'permission' => 'production.execute', 'tables' => ['printing_operations']],
        ['label' => 'Machines', 'route' => 'printing-branding.machines', 'icon' => 'bi-gear-wide-connected', 'permission' => 'machines.manage', 'tables' => ['printing_machines']],
        ['label' => 'Quality Control', 'route' => 'printing-branding.quality', 'icon' => 'bi-shield-check', 'permission' => 'production.quality_control', 'tables' => ['printing_quality_checks']],
        ['label' => 'Waste Tracking', 'route' => 'printing-branding.waste', 'icon' => 'bi-recycle', 'permission' => 'production.execute', 'tables' => ['printing_wastes']],
        ['label' => 'Inventory', 'route' => 'printing-branding.materials', 'icon' => 'bi-box-seam', 'permission' => 'inventory.view', 'tables' => ['printing_materials']],
        ['label' => 'Purchase', 'route' => 'erp.procurement', 'icon' => 'bi-cart-check'],
        ['label' => 'Outsourcing', 'route' => 'printing-branding.outsourcing', 'icon' => 'bi-box-arrow-up-right', 'permission' => 'production_jobs.view', 'tables' => ['printing_outsourcing_orders']],
        ['label' => 'Dispatch', 'route' => 'printing-branding.dispatch', 'icon' => 'bi-truck', 'permission' => 'dispatch.manage', 'tables' => ['printing_dispatches']],
        ['label' => 'Invoices', 'route' => 'invoices.index', 'icon' => 'bi-receipt'],
        ['label' => 'Job Costing', 'route' => 'printing-branding.costing', 'icon' => 'bi-cash-coin', 'permission' => 'job_costing.view', 'tables' => ['printing_job_costs']],
        ['label' => 'Reports', 'route' => 'printing-branding.reports', 'icon' => 'bi-bar-chart', 'permission' => 'printing_reports.view'],
        ['label' => 'Settings', 'route' => 'printing-branding.settings', 'icon' => 'bi-gear', 'permission' => 'printing_settings.manage'],
    ],
    'menu_structure' => ['Dashboard', 'CRM', 'Estimating', 'Quotations', 'Jobs', 'All Jobs', 'Production Board', 'Job Tickets', 'Production Schedule', 'Artwork Files', 'Proofs', 'Client Approvals', 'Production Stages', 'Machines', 'Finishing', 'Quality Control', 'Reprints', 'Materials', 'Consumables', 'Stock', 'Material Usage', 'Purchase', 'Outsourcing', 'Dispatch', 'Invoices', 'Job Costing', 'Reports', 'Settings'],
    'dashboard_features' => $kpis,
    'charts' => $charts,
    'sub_industries' => array_map(fn ($sub) => $sub + [
        'description' => 'Printing & Branding operating profile with dynamic module activation for '.$sub['name'].'.',
        'dashboard_features' => $kpis,
    ], $subIndustries),
    'registration_sub_industries' => array_column($subIndustries, 'slug'),
    'communication_channels' => ['#print-sales', '#estimating', '#design', '#production', '#finishing', '#inventory', '#procurement', '#dispatch', '#finance'],
    'alerts' => ['Job Due Today', 'Job Overdue', 'Artwork Awaiting Client', 'Proof Revision Requested', 'Material Shortage', 'Stock Below Reorder Level', 'Machine Maintenance Due', 'Production Delay', 'Quality Failure', 'Reprint Required', 'Dispatch Overdue', 'Outstanding Invoice'],
    'tenant_isolated' => true,
    'role_permissions' => true,
    'dynamic_menus' => true,
    'dashboard_widgets' => true,
    'api_endpoints' => true,
    'subscription_activated' => true,
];
