<?php

$modules = [
    'Dashboard', 'CRM', 'Vehicle Management', 'Garage Management', 'Job Cards',
    'Service Bookings', 'Inspections', 'Estimates', 'Parts & Inventory', 'Procurement',
    'Sales', 'Billing', 'Quality Control', 'Warranty', 'Fleet', 'Reports', 'Communication',
    'Workshop Bays', 'Diagnostics', 'Labour Operations', 'Technicians', 'Road Tests',
    'Vehicle Release', 'Job Costing', 'Comebacks', 'Tyres', 'Body & Paint',
    'Insurance Repairs', 'Vehicle Sales', 'Service Reminders', 'Customer Feedback',
];

$subIndustries = [
    ['slug' => 'standard', 'name' => 'Automotive Standard', 'modules' => ['Vehicles', 'Bookings', 'Job Cards', 'Inspections', 'Parts', 'Quality', 'Invoices', 'Reports']],
    ['slug' => 'multi-branch', 'name' => 'Multi-Branch Automotive', 'modules' => ['Branches', 'Workshops', 'Bays', 'Vehicles', 'Inventory', 'Reports', 'Finance']],
    ['slug' => 'enterprise', 'name' => 'Enterprise Automotive', 'modules' => array_merge($modules, ['Executive Dashboard', 'Approval Workflows', 'Branch Comparison', 'Advanced Analytics'])],
    ['slug' => 'vehicle-repair-garage', 'name' => 'Vehicle Repair Garage', 'modules' => ['Vehicles', 'Bookings', 'Inspections', 'Job Cards', 'Workshop', 'Parts', 'Estimates', 'Quality Control', 'Billing', 'Reports']],
    ['slug' => 'auto-service-center', 'name' => 'Auto Service Center', 'modules' => ['Service Packages', 'Preventive Maintenance', 'Customer Portal', 'Service Reminders', 'Job Cards', 'Parts']],
    ['slug' => 'car-dealership', 'name' => 'Car Dealership', 'modules' => ['CRM', 'Vehicle Stock', 'Sales Pipeline', 'Test Drives', 'Quotations', 'Trade-In', 'Finance', 'Delivery']],
    ['slug' => 'used-car-dealership', 'name' => 'Used Car Dealership', 'modules' => ['Vehicle Stock', 'Reconditioning', 'Trade-In', 'Sales', 'Finance']],
    ['slug' => 'spare-parts-dealer', 'name' => 'Spare Parts Dealer', 'modules' => ['Parts Catalog', 'POS', 'Inventory', 'Procurement', 'Suppliers', 'Sales', 'Finance']],
    ['slug' => 'tyre-center', 'name' => 'Tyre Center', 'modules' => ['Tyre Inventory', 'Tyre Fitment', 'Alignment', 'Balancing', 'Job Cards', 'Sales']],
    ['slug' => 'car-wash-detailing', 'name' => 'Car Wash & Detailing', 'modules' => ['Bookings', 'Service Packages', 'Vehicle Queue', 'Wash Bays', 'POS', 'Customer Loyalty']],
    ['slug' => 'auto-body-paint', 'name' => 'Auto Body & Paint', 'modules' => ['Damage Assessment', 'Insurance', 'Body Repair', 'Paint', 'Photos', 'Quality Control']],
    ['slug' => 'collision-repair-center', 'name' => 'Collision Repair Center', 'modules' => ['Insurance Repairs', 'Damage Assessment', 'Body & Paint', 'Parts', 'Quality Control']],
    ['slug' => 'fleet-service-center', 'name' => 'Fleet Service Center', 'modules' => ['Fleet', 'Vehicles', 'Maintenance Plans', 'Job Cards', 'Service Contracts', 'Fleet Reports']],
    ['slug' => 'motorcycle-workshop', 'name' => 'Motorcycle Workshop', 'modules' => ['Vehicles', 'Bookings', 'Job Cards', 'Parts', 'Service Reminders']],
    ['slug' => 'truck-heavy-vehicle-workshop', 'name' => 'Truck & Heavy Vehicle Workshop', 'modules' => ['Heavy Bays', 'Fleet', 'Job Cards', 'Parts', 'Road Tests']],
    ['slug' => 'bus-workshop', 'name' => 'Bus Workshop', 'modules' => ['Fleet', 'Preventive Maintenance', 'Job Cards', 'Inspections']],
    ['slug' => 'agricultural-machinery-workshop', 'name' => 'Agricultural Machinery Workshop', 'modules' => ['Equipment Vehicles', 'Maintenance Plans', 'Parts', 'Field Service']],
    ['slug' => 'auto-electrical-workshop', 'name' => 'Auto Electrical Workshop', 'modules' => ['Diagnostics', 'Electrical Repairs', 'Batteries', 'Job Cards']],
    ['slug' => 'battery-center', 'name' => 'Battery Center', 'modules' => ['Battery Inventory', 'Battery Installation', 'Warranty Tracking', 'Sales']],
    ['slug' => 'wheel-alignment-center', 'name' => 'Wheel Alignment Center', 'modules' => ['Alignment', 'Balancing', 'Tyres', 'Job Cards']],
    ['slug' => 'vehicle-inspection-center', 'name' => 'Vehicle Inspection Center', 'modules' => ['Digital Inspections', 'Certificates', 'Reports']],
    ['slug' => 'vehicle-rental', 'name' => 'Vehicle Rental', 'modules' => ['Fleet', 'Vehicle Availability', 'Maintenance', 'Billing']],
    ['slug' => 'fleet-management', 'name' => 'Fleet Management', 'modules' => ['Fleet', 'Maintenance Schedule', 'Service Compliance', 'Cost per Vehicle']],
    ['slug' => 'breakdown-recovery', 'name' => 'Breakdown & Recovery', 'modules' => ['Recovery Requests', 'Drivers', 'Recovery Trucks', 'Dispatch', 'Billing']],
    ['slug' => 'mobile-mechanic', 'name' => 'Mobile Mechanic', 'modules' => ['Mobile Jobs', 'Field Check-In', 'Parts', 'Invoices']],
    ['slug' => 'automotive-parts-distributor', 'name' => 'Automotive Parts Distributor', 'modules' => ['Parts Catalog', 'Warehouses', 'Procurement', 'Wholesale Sales', 'Transfers']],
];

foreach ($subIndustries as &$sub) {
    $sub['description'] = 'Automotive operating profile for '.$sub['name'].'.';
    $sub['dashboard_features'] = array_slice(array_map(fn ($module) => $module.' dashboard', $sub['modules']), 0, 6);
}
unset($sub);

return [
    'name' => 'Automotive',
    'slug' => 'automotive',
    'type' => 'industry',
    'description' => 'Run automotive workshops, garages, parts, fleet maintenance, vehicle sales, quality, warranty, and customer service workflows.',
    'modules' => $modules,
    'features' => $modules,
    'core_modules' => ['CRM', 'Clients', 'Contacts', 'Quotations', 'Invoices', 'Receipts', 'Payments', 'Finance', 'Accounting', 'Cost Accounting', 'Procurement', 'Suppliers', 'Inventory', 'Products', 'Documents', 'Reporting', 'Portal', 'Notifications', 'Communication'],
    'routes' => ['web' => 'automotive.dashboard', 'api' => '/api/v1/industries/automotive'],
    'api' => ['prefix' => '/api/v1/industries/automotive'],
    'widgets' => ['automotive-overview', 'automotive-workshop-board', 'automotive-revenue', 'automotive-parts-alerts', 'automotive-quality'],
    'reports' => [
        'Open Job Cards', 'Completed Jobs', 'Overdue Jobs', 'Jobs by Status', 'Turnaround Time', 'Jobs by Technician',
        'Labour Revenue', 'Parts Revenue', 'Revenue by Branch', 'Revenue by Service', 'Revenue by Customer', 'Monthly Revenue',
        'Job Profitability', 'Vehicle Profitability', 'Customer Profitability', 'Branch Profitability',
        'Technician Productivity', 'Technician Efficiency', 'Labour Hours', 'Comeback Jobs',
        'Inventory Valuation', 'Fast Moving Parts', 'Slow Moving Parts', 'Stockouts', 'Parts Consumption', 'Parts Margin',
        'Repeat Customers', 'New Customers', 'Customer Retention', 'Customer Satisfaction',
        'Maintenance Cost by Vehicle', 'Fleet Downtime', 'Cost per Kilometer', 'Service Compliance',
        'QC Failure', 'Comeback Rate', 'Warranty Claims',
    ],
    'workflows' => ['Customer', 'Vehicle', 'Booking', 'Check-In', 'Inspection', 'Diagnosis', 'Estimate', 'Approval', 'Job Card', 'Technician Assignment', 'Parts Reservation', 'Repair', 'Quality Control', 'Road Test', 'Invoice', 'Payment', 'Release', 'Service History', 'Warranty'],
    'templates' => ['Vehicle Inspection', 'Estimate', 'Job Card', 'Parts Request', 'Service Report', 'Warranty Certificate', 'Vehicle Release Note', 'Vehicle Sale Agreement', 'Insurance Assessment'],
    'permissions' => [
        'automotive.view', 'automotive.dashboard',
        'vehicles.view', 'vehicles.create', 'vehicles.update',
        'bookings.manage', 'checkin.manage',
        'inspections.create', 'inspections.approve',
        'job_cards.view', 'job_cards.create', 'job_cards.update', 'job_cards.assign', 'job_cards.complete',
        'estimates.manage', 'estimates.approve',
        'parts.view', 'parts.issue', 'parts.return',
        'automotive.inventory', 'automotive.procurement',
        'technicians.manage', 'workshop.manage', 'quality_control.manage',
        'warranty.manage', 'fleet.manage', 'vehicle_sales.manage',
        'automotive.finance', 'automotive.reports', 'automotive.settings',
    ],
    'menus' => [
        ['label' => 'Dashboard', 'route' => 'automotive.dashboard', 'icon' => 'bi-speedometer2', 'permission' => 'automotive.dashboard', 'tables' => ['automotive_job_cards']],
        ['label' => 'CRM', 'route' => 'clients.index', 'icon' => 'bi-people', 'permission' => 'clients.view', 'tables' => ['clients']],
        ['label' => 'Vehicle Management', 'route' => 'automotive.vehicles', 'icon' => 'bi-car-front', 'permission' => 'vehicles.view', 'tables' => ['automotive_vehicles']],
        ['label' => 'Garage Management', 'route' => 'automotive.workshop', 'icon' => 'bi-tools', 'permission' => 'workshop.manage', 'tables' => ['automotive_workshop_bays']],
        ['label' => 'Job Cards', 'route' => 'automotive.job-cards', 'icon' => 'bi-clipboard2-check', 'permission' => 'job_cards.view', 'tables' => ['automotive_job_cards']],
        ['label' => 'Service Bookings', 'route' => 'automotive.bookings', 'icon' => 'bi-calendar-check', 'permission' => 'bookings.manage', 'tables' => ['automotive_service_bookings']],
        ['label' => 'Inspections', 'route' => 'automotive.inspections', 'icon' => 'bi-search', 'permission' => 'inspections.create', 'tables' => ['automotive_inspections']],
        ['label' => 'Estimates', 'route' => 'automotive.estimates', 'icon' => 'bi-calculator', 'permission' => 'estimates.manage', 'tables' => ['automotive_estimates']],
        ['label' => 'Parts & Inventory', 'route' => 'automotive.parts', 'icon' => 'bi-nut', 'permission' => 'parts.view', 'tables' => ['automotive_parts']],
        ['label' => 'Procurement', 'route' => 'erp.procurement', 'icon' => 'bi-cart-check', 'permission' => 'automotive.procurement', 'tables' => ['suppliers']],
        ['label' => 'Sales', 'route' => 'automotive.sales', 'icon' => 'bi-tag', 'permission' => 'vehicle_sales.manage', 'tables' => ['automotive_vehicle_sales']],
        ['label' => 'Billing', 'route' => 'invoices.index', 'icon' => 'bi-receipt', 'permission' => 'automotive.finance', 'tables' => ['invoices']],
        ['label' => 'Quality Control', 'route' => 'automotive.quality', 'icon' => 'bi-patch-check', 'permission' => 'quality_control.manage', 'tables' => ['automotive_quality_checks']],
        ['label' => 'Warranty', 'route' => 'automotive.warranty', 'icon' => 'bi-shield-check', 'permission' => 'warranty.manage', 'tables' => ['automotive_warranties']],
        ['label' => 'Fleet', 'route' => 'automotive.fleet', 'icon' => 'bi-truck-front', 'permission' => 'fleet.manage', 'tables' => ['automotive_fleets']],
        ['label' => 'Reports', 'route' => 'automotive.reports', 'icon' => 'bi-bar-chart', 'permission' => 'automotive.reports', 'tables' => ['automotive_job_cards']],
        ['label' => 'Communication', 'route' => 'communication.center', 'icon' => 'bi-chat-dots', 'permission' => 'communication.view', 'tables' => ['communication_channels']],
        ['label' => 'Workshop Bays', 'route' => 'automotive.workshop', 'icon' => 'bi-columns-gap', 'permission' => 'workshop.manage', 'tables' => ['automotive_workshop_bays']],
        ['label' => 'Diagnostics', 'route' => 'automotive.workshop', 'icon' => 'bi-cpu', 'permission' => 'workshop.manage', 'tables' => ['automotive_diagnostics']],
        ['label' => 'Labour Operations', 'route' => 'automotive.labour-operations', 'icon' => 'bi-list-task', 'permission' => 'technicians.manage', 'tables' => ['automotive_labour_operations']],
        ['label' => 'Technicians', 'route' => 'automotive.technicians', 'icon' => 'bi-person-gear', 'permission' => 'technicians.manage', 'tables' => ['users']],
        ['label' => 'Road Tests', 'route' => 'automotive.road-tests', 'icon' => 'bi-signpost-split', 'permission' => 'quality_control.manage', 'tables' => ['automotive_road_tests']],
        ['label' => 'Vehicle Release', 'route' => 'automotive.vehicle-release', 'icon' => 'bi-box-arrow-right', 'permission' => 'job_cards.complete', 'tables' => ['automotive_vehicle_releases']],
        ['label' => 'Job Costing', 'route' => 'automotive.job-costing', 'icon' => 'bi-cash-coin', 'permission' => 'automotive.finance', 'tables' => ['automotive_job_costs']],
        ['label' => 'Comebacks', 'route' => 'automotive.warranty', 'icon' => 'bi-arrow-counterclockwise', 'permission' => 'warranty.manage', 'tables' => ['automotive_comebacks']],
        ['label' => 'Tyres', 'route' => 'automotive.specialty', 'params' => ['type' => 'tyres'], 'icon' => 'bi-record-circle', 'permission' => 'automotive.view', 'tables' => ['automotive_specialty_records']],
        ['label' => 'Body & Paint', 'route' => 'automotive.specialty', 'params' => ['type' => 'body-paint'], 'icon' => 'bi-palette', 'permission' => 'automotive.view', 'tables' => ['automotive_specialty_records']],
        ['label' => 'Insurance Repairs', 'route' => 'automotive.specialty', 'params' => ['type' => 'insurance-repairs'], 'icon' => 'bi-shield-plus', 'permission' => 'automotive.view', 'tables' => ['automotive_specialty_records']],
        ['label' => 'Vehicle Sales', 'route' => 'automotive.sales', 'icon' => 'bi-car-front-fill', 'permission' => 'vehicle_sales.manage', 'tables' => ['automotive_vehicle_sales']],
        ['label' => 'Service Reminders', 'route' => 'automotive.service-reminders', 'icon' => 'bi-bell', 'permission' => 'vehicles.update', 'tables' => ['automotive_service_reminders']],
        ['label' => 'Customer Feedback', 'route' => 'automotive.customer-service', 'icon' => 'bi-chat-heart', 'permission' => 'automotive.view', 'tables' => ['automotive_customer_feedback']],
        ['label' => 'Mobile Tech', 'route' => 'automotive.mobile', 'icon' => 'bi-phone', 'permission' => 'job_cards.update', 'tables' => ['automotive_job_cards']],
    ],
    'dashboard_features' => ['Jobs by Status', 'Daily Revenue', 'Labour vs Parts Revenue', 'Top Repair Services', 'Top Spare Parts', 'Technician Utilization', 'Job Profitability', 'Inventory Movement', 'Service Turnaround Time', 'Customer Satisfaction'],
    'sub_industries' => $subIndustries,
    'registration_sub_industries' => array_column($subIndustries, 'slug'),
    'roles' => ['Automotive Administrator', 'Branch Manager', 'Workshop Manager', 'Service Manager', 'Service Advisor', 'Workshop Supervisor', 'Technician', 'Master Technician', 'Diagnostic Technician', 'Auto Electrician', 'Body Repair Technician', 'Painter', 'Tyre Technician', 'Quality Controller', 'Parts Manager', 'Store Keeper', 'Procurement Officer', 'Sales Manager', 'Salesperson', 'Fleet Manager', 'Recovery Driver', 'Finance Manager', 'Accountant', 'Viewer'],
    'menu_structure' => ['Dashboard', 'CRM', 'Customers', 'Vehicles', 'Bookings', 'Workshop', 'Job Cards', 'Inspections', 'Diagnostics', 'Labour Operations', 'Technicians', 'Estimates', 'Parts', 'Procurement', 'Quality', 'Road Tests', 'Comebacks', 'Warranty', 'Fleet', 'Vehicle Sales', 'Tyres', 'Body & Paint', 'Customer Service', 'Invoices', 'Finance', 'Reports', 'Settings'],
    'tenant_isolated' => true,
    'role_permissions' => true,
    'dynamic_menus' => true,
    'dashboard_widgets' => true,
    'api_endpoints' => true,
    'subscription_activated' => true,
];
