<?php

return [
    'name' => 'Salon & Spa',
    'slug' => 'salon',
    'type' => 'industry',
    'description' => 'Manage appointments, staff schedules, services, POS, memberships, loyalty, consultations, treatments, product usage, commissions, room/chair capacity, and wellness programs.',
    'features' => [
        'Appointments',
        'Staff Scheduling',
        'Services',
        'POS',
        'Memberships',
        'Customer Loyalty',
        'Beauty Consultations',
        'Treatments',
        'Packages',
        'Gift Cards',
        'Client Profiles',
        'Inventory Usage',
        'Commission Management',
        'Chair & Room Management',
        'Wellness Programs',
        'Multi-Branch Operations',
    ],
    'core_modules' => ['CRM', 'Projects', 'Finance', 'Accounting', 'Documents', 'Reporting', 'HR', 'Administration', 'Portal', 'Notifications'],
    'routes' => [
        'web' => [
            'dashboard' => 'salon.dashboard',
            'appointments' => 'salon.appointments.index',
            'clients' => 'salon.clients.index',
            'staff_scheduling' => 'salon.staff.index',
            'services' => 'salon.services.index',
            'pos' => 'salon.pos.index',
            'memberships' => 'salon.memberships.index',
            'loyalty' => 'salon.loyalty.index',
            'consultations' => 'salon.consultations.index',
            'treatments' => 'salon.treatments.index',
            'inventory_usage' => 'salon.inventory.index',
            'commissions' => 'salon.commissions.index',
            'wellness' => 'salon.wellness.index',
            'reports' => 'salon.reports.index',
        ],
        'api' => [
            'dashboard' => 'api.v1.salon.dashboard',
            'appointments' => 'api.v1.salon.appointments.index',
            'services' => 'api.v1.salon.services.index',
            'clients' => 'api.v1.salon.clients.index',
        ],
    ],
    'api' => [
        'prefix' => '/api/v1/industries/salon',
    ],
    'widgets' => [
        'salon-overview',
        'salon-appointments',
        'salon-revenue',
        'salon-staff-utilization',
        'salon-inventory-usage',
        'salon-client-retention',
    ],
    'reports' => [
        'Appointment Utilization',
        'Service Revenue by Category',
        'Staff Commission and Productivity',
        'Membership Retention',
        'Gift Card Liability',
        'Product Consumption and Margin',
        'Client Loyalty and Repeat Visits',
        'Multi-Branch Operating Summary',
    ],
    'workflows' => [
        'Client profile intake',
        'Appointment booking',
        'Consultation approval',
        'Treatment completion',
        'POS settlement',
        'Inventory consumption',
        'Commission approval',
        'Membership renewal',
    ],
    'templates' => [
        'Default Salon Dashboard',
        'Client Consultation Form',
        'Treatment Aftercare Note',
        'Membership Agreement',
        'Gift Card Receipt',
        'Commission Statement',
        'Branch Performance Report',
    ],
    'permissions' => [
        'salon.view',
        'salon.manage',
        'salon.reports',
        'salon.appointments.view',
        'salon.appointments.manage',
        'salon.staff.view',
        'salon.staff.manage',
        'salon.services.view',
        'salon.services.manage',
        'salon.pos.view',
        'salon.pos.manage',
        'salon.memberships.view',
        'salon.memberships.manage',
        'salon.loyalty.view',
        'salon.loyalty.manage',
        'salon.consultations.view',
        'salon.consultations.manage',
        'salon.treatments.view',
        'salon.treatments.manage',
        'salon.inventory.view',
        'salon.inventory.manage',
        'salon.commissions.view',
        'salon.commissions.manage',
        'salon.wellness.view',
        'salon.wellness.manage',
    ],
    'menus' => [
        ['label' => 'Salon Dashboard', 'route' => 'salon.dashboard', 'icon' => 'bi-speedometer2', 'permission' => 'salon.view', 'tables' => ['salon_appointments']],
        ['label' => 'Appointments', 'route' => 'salon.appointments.index', 'icon' => 'bi-calendar-check', 'permission' => 'salon.appointments.view', 'tables' => ['salon_appointments', 'salon_services']],
        ['label' => 'Clients', 'route' => 'salon.clients.index', 'icon' => 'bi-person-hearts', 'permission' => 'salon.loyalty.view', 'tables' => ['salon_client_profiles']],
        ['label' => 'Staff Scheduling', 'route' => 'salon.staff.index', 'icon' => 'bi-person-workspace', 'permission' => 'salon.staff.view', 'tables' => ['salon_staff_profiles']],
        ['label' => 'Services', 'route' => 'salon.services.index', 'icon' => 'bi-scissors', 'permission' => 'salon.services.view', 'tables' => ['salon_services']],
        ['label' => 'Salon POS', 'route' => 'salon.pos.index', 'icon' => 'bi-shop-window', 'permission' => 'salon.pos.view', 'tables' => ['pos_orders']],
        ['label' => 'Memberships', 'route' => 'salon.memberships.index', 'icon' => 'bi-card-checklist', 'permission' => 'salon.memberships.view', 'tables' => ['salon_memberships']],
        ['label' => 'Loyalty & Gift Cards', 'route' => 'salon.loyalty.index', 'icon' => 'bi-gift', 'permission' => 'salon.loyalty.view', 'tables' => ['salon_loyalty_accounts', 'salon_gift_cards']],
        ['label' => 'Consultations', 'route' => 'salon.consultations.index', 'icon' => 'bi-clipboard2-pulse', 'permission' => 'salon.consultations.view', 'tables' => ['salon_consultations']],
        ['label' => 'Treatments', 'route' => 'salon.treatments.index', 'icon' => 'bi-stars', 'permission' => 'salon.treatments.view', 'tables' => ['salon_treatments']],
        ['label' => 'Product Usage', 'route' => 'salon.inventory.index', 'icon' => 'bi-box-seam', 'permission' => 'salon.inventory.view', 'tables' => ['salon_product_consumptions']],
        ['label' => 'Commissions', 'route' => 'salon.commissions.index', 'icon' => 'bi-cash-stack', 'permission' => 'salon.commissions.view', 'tables' => ['salon_commissions']],
        ['label' => 'Wellness Programs', 'route' => 'salon.wellness.index', 'icon' => 'bi-heart-pulse', 'permission' => 'salon.wellness.view', 'tables' => ['salon_wellness_programs']],
        ['label' => 'Salon Reports', 'route' => 'salon.reports.index', 'icon' => 'bi-bar-chart', 'permission' => 'salon.reports', 'tables' => ['salon_appointments']],
    ],
    'dashboard_features' => ['Appointments dashboard', 'Staff Scheduling dashboard', 'Services dashboard', 'POS dashboard', 'Client Loyalty dashboard', 'Product Usage dashboard'],
    'sub_industries' => [
        ['slug' => 'standard', 'name' => 'Salon & Spa Standard', 'description' => 'Run a single-location salon or spa with bookings, staff schedules, services, POS, memberships, loyalty, treatments, and product usage.', 'dashboard_features' => ['Appointments dashboard', 'Staff Scheduling dashboard', 'Services dashboard', 'POS dashboard', 'Client Loyalty dashboard', 'Product Usage dashboard']],
        ['slug' => 'multi-branch', 'name' => 'Multi-Branch Salon & Spa', 'description' => 'Coordinate branches, rooms, teams, permissions, consolidated reports, gift cards, and shared customer profiles.', 'dashboard_features' => ['Branch performance', 'Team workload', 'Consolidated revenue', 'Appointment capacity', 'Gift card liability', 'Cross-branch loyalty']],
        ['slug' => 'enterprise', 'name' => 'Enterprise Salon & Spa', 'description' => 'Scale salon and spa operations with executive controls, workflow templates, advanced permissions, compliance reports, and API integrations.', 'dashboard_features' => ['Executive KPIs', 'Risk alerts', 'Workflow performance', 'Compliance status', 'Commission accruals', 'Retention analytics']],
    ],
    'tenant_isolated' => true,
    'role_permissions' => true,
    'dynamic_menus' => true,
    'dashboard_widgets' => true,
    'api_endpoints' => true,
    'subscription_activated' => true,
];
