@extends('layouts.app')
@section('title', 'Cost Accounting')
@section('content')
@php
    $money = fn($value) => 'KES '.number_format((float) $value, 2);
    $tabs = ['dashboard' => 'Reports', 'structure' => 'Structure', 'budgets' => 'Budgets', 'allocations' => 'Transactions', 'audit' => 'Audit'];
    $activeTab = array_key_exists(request('tab'), $tabs) ? request('tab') : 'dashboard';
    $defaultDirection = request('direction') === 'Revenue' ? 'Revenue' : 'Expense';
@endphp
<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-4">
    <div><h2 class="h5 mb-1">Departments, Cost Centers & Projects</h2><p class="text-muted mb-0">Analytic accounting, budgets, allocations and profitability for {{ $year }}.</p></div>
    <form class="d-flex gap-2"><input class="form-control" type="number" name="year" min="2000" max="2200" value="{{ $year }}"><button class="btn btn-dark">View year</button></form>
</div>

<div class="row g-3 mb-4">
    <div class="col-md-3"><div class="card p-3"><span class="text-muted small">Revenue</span><strong class="fs-4">{{ $money($departmentRows->sum('revenue')) }}</strong></div></div>
    <div class="col-md-3"><div class="card p-3"><span class="text-muted small">Expenses</span><strong class="fs-4">{{ $money($departmentRows->sum('expenses')) }}</strong></div></div>
    <div class="col-md-3"><div class="card p-3"><span class="text-muted small">Net profit</span><strong class="fs-4 {{ $departmentRows->sum('profit') < 0 ? 'text-danger' : 'text-success' }}">{{ $money($departmentRows->sum('profit')) }}</strong></div></div>
    <div class="col-md-3"><div class="card p-3"><span class="text-muted small">Approved budgets</span><strong class="fs-4">{{ $money($budgets->where('budget.status', 'Approved')->sum(fn($row) => $row['budget']->amount)) }}</strong></div></div>
</div>
@if($budgetAlerts->isNotEmpty())
<div class="alert alert-danger"><strong>Budget notifications</strong>@foreach($budgetAlerts as $alert)<div class="d-flex justify-content-between align-items-center border-top mt-2 pt-2"><span>{{ $alert->message }}</span><form method="post" action="{{ route('accounting.alerts.acknowledge',$alert) }}">@csrf<button class="btn btn-sm btn-outline-danger">Acknowledge</button></form></div>@endforeach</div>
@endif
<div class="card p-3 mb-3"><h3 class="h6">Project accounting reports</h3><form method="get" action="{{ route('accounting.reports.show','profit-loss') }}" class="row g-2"><div class="col-md-5"><select class="form-select" name="project_id" required><option value="">Select project</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->project_name }}</option>@endforeach</select></div><div class="col-md-5"><select class="form-select" onchange="this.form.action=this.value"><option value="{{ route('accounting.reports.show','profit-loss') }}">Project P&amp;L</option><option value="{{ route('accounting.reports.show','cash-flow') }}">Cash Flow</option><option value="{{ route('accounting.reports.show','expenses') }}">Expense Report</option><option value="{{ route('accounting.reports.show','procurement') }}">Procurement Report</option><option value="{{ route('accounting.reports.show','customer-payments') }}">Customer Payments</option></select></div><div class="col-md-2"><button class="btn btn-dark w-100">Generate</button></div></form></div>

<ul class="nav nav-tabs mb-3" role="tablist">
    @foreach($tabs as $id=>$label)<li class="nav-item"><button class="nav-link {{ $activeTab === $id ? 'active' : '' }}" data-bs-toggle="tab" data-bs-target="#{{ $id }}" type="button">{{ $label }}</button></li>@endforeach
</ul>
<div class="tab-content">
<div class="tab-pane fade {{ $activeTab === 'dashboard' ? 'show active' : '' }}" id="dashboard">
    <div class="row g-3">
        <div class="col-xl-6"><div class="card p-3"><h3 class="h6">Department P&amp;L and cash flow</h3><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Department</th><th>Revenue</th><th>Expenses</th><th>Profit</th><th>Cash flow</th></tr></thead><tbody>@forelse($departmentRows as $row)<tr><td>{{ $row['department']->name }}<small class="d-block text-muted">AR {{ $money($row['receivables']) }} · AP {{ $money($row['payables']) }}</small></td><td>{{ $money($row['revenue']) }}</td><td>{{ $money($row['expenses']) }}</td><td class="fw-bold {{ $row['profit']<0?'text-danger':'text-success' }}">{{ $money($row['profit']) }}</td><td>{{ $money($row['cash_flow']) }}</td></tr>@empty<tr><td colspan="5" class="text-muted">Create a department to begin.</td></tr>@endforelse</tbody></table></div></div></div>
        <div class="col-xl-6"><div class="card p-3"><h3 class="h6">Project profitability</h3><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Project</th><th>Revenue</th><th>Cost</th><th>Margin</th></tr></thead><tbody>@foreach($projectRows->sortByDesc('profit') as $row)<tr><td><a href="{{ route('projects.show',$row['project']) }}">{{ $row['project']->project_name }}</a><small class="d-block text-muted">AR {{ $money($row['receivables']) }} · AP {{ $money($row['payables']) }}</small></td><td>{{ $money($row['revenue']) }}</td><td>{{ $money($row['expenses']) }}</td><td class="fw-bold {{ $row['profit']<0?'text-danger':'text-success' }}">{{ number_format($row['margin'],1) }}%</td></tr>@endforeach</tbody></table></div></div></div>
        <div class="col-12"><div class="card p-3"><h3 class="h6">Top cost centers</h3><div class="table-responsive"><table class="table"><thead><tr><th>Cost center</th><th>Department</th><th>Revenue</th><th>Expenses</th><th>Profit</th></tr></thead><tbody>@foreach($costCenterRows->sortByDesc('profit')->take(10) as $row)<tr><td>{{ $row['cost_center']->name }}</td><td>{{ $row['cost_center']->department?->name }}</td><td>{{ $money($row['revenue']) }}</td><td>{{ $money($row['expenses']) }}</td><td class="fw-bold {{ $row['profit']<0?'text-danger':'text-success' }}">{{ $money($row['profit']) }}</td></tr>@endforeach</tbody></table></div></div></div>
        <div class="col-12"><div class="card p-3"><h3 class="h6">Budget utilization & alerts</h3><div class="row g-3">@forelse($budgets as $row)<div class="col-md-4"><div class="border rounded p-3"><div class="d-flex justify-content-between"><strong>{{ $row['budget']->name }}</strong><span>{{ number_format($row['utilization'],1) }}%</span></div><div class="progress my-2" role="progressbar"><div class="progress-bar {{ $row['utilization']>=100?'bg-danger':($row['utilization'] >= $row['budget']->alert_threshold?'bg-warning':'bg-success') }}" style="width:{{ min(100,$row['utilization']) }}%"></div></div><small>{{ $money($row['actual']) }} of {{ $money($row['budget']->amount) }} · Variance {{ $money($row['variance']) }}</small>@if($row['utilization'] >= $row['budget']->alert_threshold)<div class="text-danger small fw-bold mt-1"><i class="bi bi-exclamation-triangle"></i> Budget threshold reached</div>@endif</div></div>@empty<p class="text-muted">No budgets for this year.</p>@endforelse</div></div></div>
    </div>
</div>
<div class="tab-pane fade {{ $activeTab === 'structure' ? 'show active' : '' }}" id="structure">
    <div class="row g-3 mb-3">
        <div class="col-lg-4"><div class="card p-3"><h3 class="h6">Industry defaults</h3><form method="post" action="{{ route('accounting.industry.store') }}" class="d-flex gap-2">@csrf<select name="industry" class="form-select" required>@foreach($industries as $industry)<option @selected(\App\Support\ActiveBusiness::current()?->industry===$industry)>{{ $industry }}</option>@endforeach</select><button class="btn btn-dark">Apply</button></form><small class="text-muted">Adds defaults without deleting custom departments.</small></div></div>
        <div class="col-lg-4"><div class="card p-3"><h3 class="h6">New department</h3><form method="post" action="{{ route('accounting.departments.store') }}" class="row g-2">@csrf<div class="col-8"><input class="form-control" name="name" placeholder="Department name" required></div><div class="col-4"><input class="form-control" name="code" placeholder="Code" required></div><div class="col-12"><select class="form-select" name="manager_id"><option value="">No manager</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select></div><div class="col-12"><button class="btn btn-warning w-100">Create department</button></div></form></div></div>
        <div class="col-lg-4"><div class="card p-3"><h3 class="h6">New cost center</h3><form method="post" action="{{ route('accounting.cost-centers.store') }}" class="row g-2">@csrf<div class="col-7"><input class="form-control" name="name" placeholder="Cost center name" required></div><div class="col-5"><input class="form-control" name="code" placeholder="Code" required></div><div class="col-6"><select class="form-select" name="department_id" required><option value="">Department</option>@foreach($departments as $department)<option value="{{ $department->id }}">{{ $department->name }}</option>@endforeach</select></div><div class="col-6"><select class="form-select" name="parent_id"><option value="">No parent</option>@foreach($costCenters as $center)<option value="{{ $center->id }}">{{ $center->name }}</option>@endforeach</select></div><div class="col-12"><button class="btn btn-warning w-100">Create cost center</button></div></form></div></div>
    </div>
    <div class="card p-3"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Department / Manager</th><th>Cost center hierarchy</th><th>Status</th><th></th></tr></thead><tbody>@foreach($departments as $department)<tr><td><strong>{{ $department->name }}</strong><small class="d-block text-muted">{{ $department->code }} · {{ $department->manager?->name ?? 'No manager' }}</small></td><td>@forelse($department->costCenters->whereNull('parent_id') as $center)<div class="mb-1"><span class="badge bg-light text-dark">{{ $center->code }}</span> {{ $center->name }} @if($center->is_project)<span class="badge bg-info">Project</span>@endif @foreach($center->children as $child)<small class="d-block ms-4 text-muted">↳ {{ $child->name }}</small>@endforeach</div>@empty<span class="text-muted">No cost centers</span>@endforelse</td><td>{{ $department->is_active?'Active':'Archived' }}</td><td><form method="post" action="{{ route('accounting.departments.archive',$department) }}">@csrf<button class="btn btn-sm btn-outline-secondary">{{ $department->is_active?'Archive':'Restore' }}</button></form></td></tr>@endforeach</tbody></table></div></div>
</div>
<div class="tab-pane fade {{ $activeTab === 'budgets' ? 'show active' : '' }}" id="budgets"><div class="row g-3"><div class="col-lg-4"><div class="card p-3"><h3 class="h6">Annual budget</h3><form method="post" action="{{ route('accounting.budgets.store') }}" class="row g-2">@csrf<input class="form-control" name="name" placeholder="Budget name" required><div class="col-6"><input class="form-control" type="number" name="fiscal_year" value="{{ $year }}" required></div><div class="col-6"><input class="form-control" type="number" step="0.01" name="amount" placeholder="KES amount" required></div><select class="form-select" name="department_id"><option value="">Whole business / department</option>@foreach($departments as $department)<option value="{{ $department->id }}">{{ $department->name }}</option>@endforeach</select><select class="form-select" name="cost_center_id"><option value="">Optional cost center</option>@foreach($costCenters as $center)<option value="{{ $center->id }}">{{ $center->name }}</option>@endforeach</select><select class="form-select" name="project_id"><option value="">Optional project</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->project_name }}</option>@endforeach</select><div class="input-group"><span class="input-group-text">Alert at</span><input class="form-control" type="number" name="alert_threshold" value="80"><span class="input-group-text">%</span></div><button class="btn btn-warning">Create draft budget</button></form></div></div><div class="col-lg-8"><div class="card p-3"><table class="table"><thead><tr><th>Budget</th><th>Scope</th><th>Amount</th><th>Status</th><th></th></tr></thead><tbody>@foreach($budgets as $row)<tr><td>{{ $row['budget']->name }}</td><td>{{ $row['budget']->project?->project_name ?? $row['budget']->costCenter?->name ?? $row['budget']->department?->name ?? 'Business' }}</td><td>{{ $money($row['budget']->amount) }}</td><td>{{ $row['budget']->status }}</td><td>@if($row['budget']->status!=='Approved')<form method="post" action="{{ route('accounting.budgets.approve',$row['budget']) }}">@csrf<button class="btn btn-sm btn-success">Approve</button></form>@endif</td></tr>@endforeach</tbody></table></div></div></div></div>
<div class="tab-pane fade {{ $activeTab === 'allocations' ? 'show active' : '' }}" id="allocations"><div class="row g-3"><div class="col-lg-4"><div class="card p-3"><h3 class="h6">Tag transaction</h3><form method="post" action="{{ route('accounting.allocations.store') }}" class="row g-2">@csrf<div class="col-6"><select class="form-select" name="direction"><option @selected($defaultDirection === 'Expense')>Expense</option><option @selected($defaultDirection === 'Revenue')>Revenue</option></select></div><div class="col-6"><input class="form-control" type="date" name="transaction_date" value="{{ now()->toDateString() }}" required></div><div class="col-7"><input class="form-control" name="transaction_type" value="{{ $defaultDirection === 'Expense' ? 'Expense' : '' }}" placeholder="Expense, Invoice, PO..." required></div><div class="col-5"><input class="form-control" type="number" name="transaction_id" placeholder="Record ID"></div><input class="form-control" name="category" placeholder="Category"><input class="form-control" name="description" placeholder="Description"><input class="form-control" type="number" step="0.01" name="amount" placeholder="Amount" required><select class="form-select" name="department_id"><option value="">Department</option>@foreach($departments as $department)<option value="{{ $department->id }}">{{ $department->name }}</option>@endforeach</select><select class="form-select" name="cost_center_id"><option value="">Cost center</option>@foreach($costCenters as $center)<option value="{{ $center->id }}">{{ $center->name }}</option>@endforeach</select><select class="form-select" name="project_id"><option value="">Project</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->project_name }}</option>@endforeach</select><button class="btn btn-warning">Save allocation</button></form></div></div><div class="col-lg-8"><div class="card p-3"><div class="table-responsive"><table class="table"><thead><tr><th>Date</th><th>Transaction</th><th>Tags</th><th>Direction</th><th>Amount</th></tr></thead><tbody>@foreach($allocations->sortByDesc('transaction_date') as $allocation)<tr><td>{{ $allocation->transaction_date->format('d M Y') }}</td><td>{{ $allocation->transaction_type }} @if($allocation->transaction_id)#{{ $allocation->transaction_id }}@endif<small class="d-block text-muted">{{ $allocation->description }}</small></td><td>{{ $allocation->department?->name }} / {{ $allocation->costCenter?->name }} / {{ $allocation->project?->project_name }}</td><td><span class="badge {{ $allocation->direction==='Revenue'?'bg-success':'bg-danger' }}">{{ $allocation->direction }}</span></td><td>{{ $money($allocation->amount) }}</td></tr>@endforeach</tbody></table></div></div></div></div></div>
<div class="tab-pane fade {{ $activeTab === 'audit' ? 'show active' : '' }}" id="audit"><div class="card p-3"><h3 class="h6">Change & approval history</h3><table class="table"><thead><tr><th>When</th><th>Event</th><th>Record</th><th>User</th></tr></thead><tbody>@forelse($auditLogs as $log)<tr><td>{{ $log->created_at?->format('d M Y H:i') }}</td><td>{{ ucfirst($log->event) }}</td><td>{{ class_basename($log->auditable_type) }} #{{ $log->auditable_id }}</td><td>#{{ $log->user_id }}</td></tr>@empty<tr><td colspan="4" class="text-muted">No accounting changes yet.</td></tr>@endforelse</tbody></table></div></div>
</div>
<div class="card p-3 mt-3"><h3 class="h6">Edit accounting structure</h3><div class="row g-3"><div class="col-lg-4"><form method="post" id="department-edit-form" class="row g-2" onsubmit="this.action='{{ url('/accounting/departments') }}/'+this.department_id.value">@csrf @method('PUT')<select class="form-select" name="department_id" required><option value="">Department to edit</option>@foreach($departments as $department)<option value="{{ $department->id }}">{{ $department->name }}</option>@endforeach</select><input class="form-control" name="name" placeholder="New name" required><input class="form-control" name="code" placeholder="Code" required><select class="form-select" name="manager_id"><option value="">No manager</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select><button class="btn btn-outline-dark">Update department</button></form></div><div class="col-lg-4"><form method="post" class="row g-2" onsubmit="this.action='{{ url('/accounting/cost-centers') }}/'+this.cost_center_id.value">@csrf @method('PUT')<select class="form-select" name="cost_center_id" required><option value="">Cost center to edit</option>@foreach($costCenters as $center)<option value="{{ $center->id }}">{{ $center->name }}</option>@endforeach</select><input class="form-control" name="name" placeholder="New name" required><input class="form-control" name="code" placeholder="Code" required><select class="form-select" name="department_id" required>@foreach($departments as $department)<option value="{{ $department->id }}">{{ $department->name }}</option>@endforeach</select><button class="btn btn-outline-dark">Update cost center</button></form></div><div class="col-lg-4"><form method="post" class="row g-2" onsubmit="this.action='{{ url('/accounting/budgets') }}/'+this.budget_id.value">@csrf @method('PUT')<select class="form-select" name="budget_id" required><option value="">Draft budget to edit</option>@foreach($budgets->where('budget.status','Draft') as $row)<option value="{{ $row['budget']->id }}">{{ $row['budget']->name }}</option>@endforeach</select><input class="form-control" name="name" placeholder="Budget name" required><input class="form-control" name="fiscal_year" value="{{ $year }}" required><input class="form-control" name="amount" type="number" step="0.01" placeholder="Amount" required><input class="form-control" name="alert_threshold" type="number" value="80" required><button class="btn btn-outline-dark">Update budget</button></form></div></div></div>
@endsection
